import test from 'node:test';import assert from 'node:assert/strict';import {fresh,act,settle,valid,decode} from '../lib/game.mjs';import {potionRecipes} from '../lib/apothecary.mjs';import {createPersistence} from '../lib/persistence.mjs';
const run=(s,a,id=null,q=null)=>{const r=act(s,a,s.lastAt,id,{seq:s.apothecary?.seq,quantity:q});assert.ok(!r.error,r.error);assert.ok(valid(r.state));return r.state};
const started=()=>run(fresh(1000),'apothecaryOpen'),ready=()=>settle(started(),21000);
test('one explicit starter completes bootstrap sale, recipe unlock, paid brewing and separate deposit',()=>{let s=started();assert.equal(potionRecipes(s).length,0);assert.ok(act(s,'apothecaryOpen',1000).error);assert.ok(act(s,'potionStock',1000,'1001',{seq:0,quantity:1}).error);s=settle(s,21000);assert.equal(s.apothecary.sold,1);assert.equal(potionRecipes(s)[0].id,'1001');assert.equal(s.apothecary.deposit,10);assert.equal(s.gold,250);s=run(s,'potionCollect');assert.equal(s.gold,260);s=run(s,'potionStock','1001',5);assert.equal(s.gold,235);assert.equal(s.apothecary.shelves[0].price,11);s=settle(s,121000);assert.equal(s.apothecary.deposit,55);assert.equal(s.apothecary.sold,6);assert.equal(s.apothecary.shelves[0].units,0);assert.deepEqual(settle(s,121000).apothecary,s.apothecary);assert.deepEqual(decode(JSON.stringify(s)).apothecary,s.apothecary)});
test('sales gates count actual bottles; stocked price and old promises remain unchanged',()=>{let s=ready();for(let n=0;n<2;n++){s=run(s,'potionStock','1001',20);const price=s.apothecary.shelves[0].price;s=settle(s,s.lastAt+400000);assert.equal(s.apothecary.shelves[0].price,price);s=run(s,'potionCollect')}assert.equal(s.apothecary.sold,41);assert.equal(potionRecipes(s).length,2);s=run(s,'potionStock','1002',1);assert.equal(s.apothecary.shelves[0].id,'1002');assert.equal(s.apothecary.shelves[0].price,12);assert.ok(act(s,'potionStock',s.lastAt,'1003',{seq:s.apothecary.seq,quantity:1}).error)});
test('full deposit pauses stock and collection resumes future customers; wallet cap preserves remainder',()=>{let s=run(ready(),'potionStock','1001',20);s.apothecary.shelves[0].price=100;s.apothecary.deposit=490;s=settle(s,s.lastAt+1e6);assert.equal(s.apothecary.shelves[0].units,20);assert.equal(s.apothecary.sold,1);s.gold=1e9-3;s=run(s,'potionCollect');assert.equal(s.gold,1e9);assert.equal(s.apothecary.deposit,487);assert.ok(act(s,'potionCollect',s.lastAt,null,{seq:s.apothecary.seq}).error);s.gold=100;s=run(s,'potionCollect');s=settle(s,s.lastAt+19999);assert.equal(s.apothecary.sold,1);s=settle(s,s.lastAt+1);assert.equal(s.apothecary.sold,2)});
test('three shelf capacity, ownership gates, malformed queues and insufficient budgets reject safely',()=>{let s=ready();s.apothecary.sold=600;for(const id of ['1001','1002','1003'])s=run(s,'potionStock',id,1);assert.equal(s.apothecary.shelves.length,3);assert.ok(act(s,'potionStock',s.lastAt,'1004',{seq:s.apothecary.seq,quantity:1}).error);for(const edit of [a=>a.policyVersion=2,a=>a.deposit=2000,a=>a.shelves[0].id='10001',a=>a.shelves[0].price=0,a=>a.shelves[0].units=21,a=>a.shelves.push({...a.shelves[0]})]){const b=structuredClone(s);edit(b.apothecary);assert.equal(valid(b),false);assert.throws(()=>decode(JSON.stringify(b)))}s=ready();s.gold=4;assert.ok(act(s,'potionStock',s.lastAt,'1001',{seq:s.apothecary.seq,quantity:1}).error)});
test('failed paid stocking write and stale collection cannot repeat money or stock',()=>{let raw=JSON.stringify(ready()),full=false;const p=createPersistence(()=>({getItem:()=>raw,setItem:(_,v)=>{if(full)throw Error('quota');raw=v}}));p.load(21000);const before=p.current;full=true;assert.throws(()=>p.commit(run(before,'potionStock','1001',5)));assert.equal(p.current.gold,before.gold);full=false;p.load(21000);p.commit(run(p.current,'potionStock','1001',5));assert.equal(p.current.apothecary.shelves[0].units,5);const seq=p.current.apothecary.seq;p.commit(run(p.current,'potionCollect'));assert.ok(act(p.current,'potionCollect',21000,null,{seq}).error)});
test('counter bootstraps even with zero village gold and earns reusable brewing funds',()=>{let s=fresh(1000);s.gold=0;s=run(s,'apothecaryOpen');s=settle(s,21000);s=run(s,'potionCollect');assert.equal(s.gold,10);s=run(s,'potionStock','1001',1);s=settle(s,41000);s=run(s,'potionCollect');assert.equal(s.gold,16);assert.equal(s.apothecary.sold,2)});
