import test from 'node:test';import assert from 'node:assert/strict';import {fresh,act,settle,valid,decode,totalRate} from '../lib/game.mjs';import {banquetState,banquetPurchasePlan,BANQUET_ORE} from '../lib/banquets.mjs';import {createPersistence} from '../lib/persistence.mjs';
const card='Item_Gcoin_YieldPack_1',ore=BANQUET_ORE,club='Item_Weapon_Equipment_1_1';
const run=(s,a,id=null,q=null)=>{const r=act(s,a,s.lastAt,id,{seq:banquetState(s).seq,quantity:q});assert.equal(r.error,undefined,r.error);assert.ok(valid(r.state),a);return r.state;};
const earned=()=>{let s=run({...fresh(1000),banquets:{policyVersion:1,seq:0,coins:0,popularity:0,pantry:{Item_Ceremony_03:1,Item_Ceremony_04:1},run:null,history:[],shop:{day:0,bought:{}}}},'banquetHost','fine');s=settle(s,41000);return run(s,'banquetClaim',s.banquets.run.id);};
test('earned800coins→20Ore and50Cards→two upgrades and actual income, with precise source receipts',()=>{let s=earned();const history=structuredClone(s.banquets.history);s=run(s,'banquetBuy',ore,'max');assert.equal(s.artifacts.ore,20);assert.equal(s.banquets.coins,200);s=run(s,'banquetBuy',card,'max');assert.equal(s.inventory[card],50);assert.equal(s.banquets.coins,100);assert.deepEqual(s.banquets.purchases.map(r=>[r.quantity,r.unitPrice,r.paid,r.destination]),[[20,30,600,'forge'],[50,2,100,'bag']]);s=act(s,'claimAllGear',s.lastAt).state;s=act(s,'equip',s.lastAt,'hero_15',club).state;s=act(s,'upgradeArtifactMax',s.lastAt,'hero_15').state;assert.equal(s.fellows.hero_15.gearLevel,3);assert.equal(s.fellows.hero_15.gearOreSpent,20);assert.equal(s.artifacts.ore,0);const before=s.gold,rate=totalRate(s);assert.ok(rate>0);s=act(s,'useConsumable',s.lastAt,card,{count:1}).state;assert.equal(s.gold,before+Math.floor(rate*60));assert.equal(s.inventory[card],49);assert.deepEqual(s.banquets.history,history);assert.deepEqual(decode(JSON.stringify(s)),s);});
test('max respects destination capacities and allowance while existing1/5 batches stay exact',()=>{let s=earned();s.artifacts={ore:1e9-3,bag:{}};assert.deepEqual(banquetPurchasePlan(s,ore,'max'),{quantity:3,cost:90});assert.equal(banquetPurchasePlan(s,ore,5).quantity,0);s=run(s,'banquetBuy',ore,'max');assert.equal(s.artifacts.ore,1e9);assert.equal(banquetPurchasePlan(s,ore,'max').quantity,0);s.inventory[card]=1e6-2;assert.equal(banquetPurchasePlan(s,card,5).quantity,0);s=run(s,'banquetBuy',card,'max');assert.equal(s.inventory[card],1e6);assert.equal(s.banquets.shop.bought[card],2);for(const q of [0,2,-1,100,'all'])assert.equal(banquetPurchasePlan(s,card,q).quantity,0);});
test('daily reset opens new quota, retains past prices and cannot reuse old exchange sequence',()=>{let s=run(earned(),'banquetBuy',ore,'max');s.banquets.purchases[0].unitPrice=31;s.banquets.purchases[0].paid=620;s.banquets.coins-=20;const old=structuredClone(s.banquets.purchases),seq=s.banquets.seq;assert.ok(valid(s));assert.equal(banquetPurchasePlan(s,ore,1).quantity,0);s=settle(s,86400001);s=run(s,'banquetBuy',ore,1);assert.deepEqual(s.banquets.purchases.slice(0,1),old);assert.equal(s.banquets.shop.bought[ore],1);assert.equal(s.banquets.purchases[1].unitPrice,30);assert.ok(act(s,'banquetBuy',s.lastAt,ore,{seq,quantity:1}).error);assert.deepEqual(decode(JSON.stringify(s)),s);});
test('legacy purchases need no reconstructed receipts; new malformed receipts are rejected',()=>{let s=run(earned(),'banquetBuy','Item_Talent_Hero_1',1);delete s.banquets.purchases;const legacy=structuredClone(s);assert.ok(valid(s));s=run(s,'banquetBuy',card,5);assert.equal(s.banquets.purchases.length,1);assert.equal(s.inventory.Item_Talent_Hero_1,legacy.inventory.Item_Talent_Hero_1);for(const f of [b=>b.purchases[0].paid++,b=>b.purchases[0].destination='forge',b=>b.purchases[0].id=b.history[0].id,b=>b.purchases.push({...b.purchases[0]}),b=>b.purchases[0].day++,b=>b.shop.bought[card]=0]){const bad=structuredClone(s);f(bad.banquets);assert.equal(valid(bad),false);assert.throws(()=>decode(JSON.stringify(bad)));}});
test('failed whole batch write retains coins, quota, destination and receipts until explicit retry',()=>{for(const id of [ore,card]){const s=earned();let raw=JSON.stringify(s),fail=false;const p=createPersistence(()=>({getItem:()=>raw,setItem:(_,v)=>{if(fail)throw Error('quota');raw=v}}));p.load(s.lastAt);fail=true;assert.throws(()=>p.commit(run(p.current,'banquetBuy',id,'max')));assert.deepEqual(p.current,s);fail=false;p.load(s.lastAt);p.commit(run(p.current,'banquetBuy',id,'max'));assert.equal(p.current.banquets.purchases.length,1);const receipt=structuredClone(p.current.banquets.purchases);p.load(s.lastAt);assert.deepEqual(p.current.banquets.purchases,receipt);assert.equal(banquetPurchasePlan(p.current,id,'max').quantity,0);}});
