import {LEGACY_ITEMS} from '../lib/adventure.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {fresh,act,decode,valid,totalRate} from '../lib/game.mjs';import {teamPower} from '../lib/adventure.mjs';import {supplied} from './gear-fixtures.mjs';
const run=(s,a,t=null,v=null)=>act(s,a,s.lastAt,t,v);
test('v5 migration preserves inventory, progression and currency with empty bonds',()=>{const s=fresh(1000);s.version=5;delete s.bonds;s.inventory=Object.fromEntries(Object.entries(s.inventory).filter(([id])=>id.startsWith('gift')||LEGACY_ITEMS.some(i=>i.id===id)));s.crystals=123;s.inventory.local_skill_scroll=7;const n=decode(JSON.stringify(s));assert.equal(n.version,10);assert.deepEqual(n.bonds,{});assert.equal(n.crystals,123);assert.equal(n.inventory.local_skill_scroll,7);assert.ok(valid(n));});
test('bond training consumes points once, increases Power and income, persists and transfers',()=>{let s=run(fresh(1000),'welcome').state;s.family.wife_2.points=100;s=run(s,'bondAssign','wife_2','hero_15').state;const income=totalRate(s),power=teamPower(s);s=run(s,'bondTrain','wife_2').state;assert.equal(s.family.wife_2.points,80);assert.ok(totalRate(s)>income);assert.ok(teamPower(s)>power);assert.deepEqual(decode(JSON.stringify(s)),s);s=run(s,'recruit','hero_101').state;s=run(s,'bondAssign','wife_2','hero_101').state;assert.equal(s.bonds.wife_2.level,1);assert.equal(teamPower(s),power);assert.equal(totalRate(s),income);});
test('unowned targets and insufficient points cannot create bonuses',()=>{let s=run(fresh(1000),'welcome').state;assert.ok(run(s,'bondAssign','wife_2','hero_101').error);s=run(s,'bondAssign','wife_2','hero_15').state;assert.ok(run(s,'bondTrain','wife_2').error);assert.equal(s.bonds.wife_2.level,0);const corrupt=structuredClone(s);corrupt.bonds.wife_2.level=11;assert.throws(()=>decode(JSON.stringify(corrupt)));});
// ECON-15: the free `sandboxSupplies` refill is deleted. The invariant it guarded -- adding gifts must
// not disturb equipment or training stock -- now runs through buyGift, the priced door that remains.
test('buying a gift preserves all equipment and training resources',()=>{let s=supplied(fresh(1000));s={...s,gold:s.gold+1000};const before={...s.inventory};s=run(s,'buyGift','gift2').state;assert.equal(s.inventory.gift2,before.gift2+1);for(const [id,n] of Object.entries(before))if(!id.startsWith('gift'))assert.equal(s.inventory[id],n);assert.ok(valid(s));assert.deepEqual(decode(JSON.stringify(s)),s);
 assert.throws(()=>run(s,'sandboxSupplies'),/Unknown action/,'the free refill is gone, not merely hidden');});
test('targeted free recruitment is unique and rejects invalid IDs',()=>{const s=fresh(1000),r=run(s,'recruit','hero_101');assert.equal(r.recruited,'hero_101');assert.ok(!r.state.fellows.hero_1);assert.ok(run(r.state,'recruit','hero_101').error);assert.ok(run(s,'recruit','bad').error);});
