import test from 'node:test';import assert from 'node:assert/strict';import {fresh,act,valid,decode,totalRate} from '../lib/game.mjs';import {FELLOWS} from '../lib/catalog.mjs';import {talentRule,talentCap,talentTrainingPlan} from '../lib/talents.mjs';import {createPersistence} from '../lib/persistence.mjs';import {bondedPower} from '../lib/adventure.mjs';import source from '../lib/default-talent-source.json' with {type:'json'};
const run=(s,a,t=null,v=null)=>{const r=act(s,a,s.lastAt,t,v);assert.ok(!r.error,r.error);assert.ok(valid(r.state),a);return r.state};
test('all admitted identities preserve old paid gains then use source rows through300',()=>{let n=0;for(const {id} of FELLOWS){const r=talentRule(id);if(!r)continue;n++;assert.equal(source.costs[source.heroes[id]],r.cost);let s=fresh(1000);if(!s.fellows[id])s=run(s,'recruit',id);s.inventory.Item_Talent_Hero_1=1000;s=run(s,'trainTalent',id,'max');assert.equal(s.fellows[id].talentLevel,r.cap);const before=structuredClone(s.fellows[id]);s=run(s,'activateOriginalProgression');assert.deepEqual(s.fellows[id],before);const power=bondedPower(s,id);s=run(s,'trainTalent',id,'max');assert.equal(s.fellows[id].talentLevel,299);assert.equal(s.fellows[id].aptitude,10+299*r.amount);assert.equal(s.fellows[id].originalTalent.baseline,r.cap);assert.equal(s.inventory.Item_Talent_Hero_1,1000-299*r.cost);assert.ok(bondedPower(s,id)>power);assert.equal(talentCap(s,id),299);assert.deepEqual(decode(JSON.stringify(s)),s);}assert.ok(n>150);});
test('quality has no paid Talent levels; max respects saved Aptitude1000 and exact fractional affordability',()=>{let s=run(fresh(1000),'activateOriginalProgression');s=run(s,'claimOriginalSupplies');s=run(s,'train','hero_15','max');s=run(s,'originalQuality','hero_15');assert.equal(s.fellows.hero_15.talentLevel,undefined);const r=talentRule('hero_15');s.fellows.hero_15.aptitude=1000-r.amount;s.inventory.Item_Talent_Hero_1=1000;assert.equal(talentTrainingPlan(s,'hero_15','max').count,1);s=run(s,'trainTalent','hero_15','max');assert.equal(s.fellows.hero_15.aptitude,1000);assert.equal(s.fellows.hero_15.talentLevel,1);assert.ok(act(s,'trainTalent',s.lastAt,'hero_15',1).error);});
test('new receipts refuse edits, preserve frozen encounters, settle previous earnings, and recover failed writes',()=>{let s=run(fresh(1000),'activateOriginalProgression');s.inventory.Item_Talent_Hero_1=1000;s=run(s,'northStart',null,{seq:0});s=run(s,'tradeBegin','veteran',{seq:0,team:['hero_15']});const north=structuredClone(s.northern),trade=structuredClone(s.tradingPost),rate=totalRate(s);const result=act(s,'trainTalent',2000,'hero_15',5);assert.ok(!result.error);assert.equal(result.state.pending,s.pending+rate);assert.deepEqual(result.state.northern,north);assert.deepEqual(result.state.tradingPost,trade);
let raw=JSON.stringify(s),fail=false;const p=createPersistence(()=>({getItem:()=>raw,setItem:(k,v)=>{if(fail)throw Error('quota');raw=v}}));p.load(1000);fail=true;assert.throws(()=>p.commit(result.state));assert.deepEqual(p.current,s);fail=false;p.load(1000);p.commit(run(p.current,'trainTalent','hero_15',5));const saved=p.current;for(const mutate of [x=>x.fellows.hero_15.originalTalent.receipts[0].cost++,x=>x.fellows.hero_15.originalTalent.baseline++,x=>delete x.fellows.hero_15.talentLevel]){const bad=structuredClone(saved);mutate(bad);assert.equal(valid(bad),false);}assert.deepEqual(decode(raw),saved);});
import {ARTIFACT_SUPPORTS} from '../lib/artifact-echo.mjs';
test('loaded equipment Family Familiar Stella remain intact at quality1 and14 when buying Talent',()=>{let s=run(fresh(1000),'recruit','hero_54');s=run(s,'activateOriginalProgression');const a=ARTIFACT_SUPPORTS[0];s=run(s,'claimAllGear');s=run(s,'equip','hero_54',a.item);s=run(s,'welcome',a.family);s=run(s,'enableArtifactEcho','hero_54');s=run(s,'adoptFamiliar','Pet_4151');s=run(s,'trainFamiliar','Pet_4151',10);s=run(s,'bindFamiliar','Pet_4151','hero_54');s=run(s,'stellaActivate','hero_54',{seq:0});s=run(s,'stellaSupply','hero_54',{seq:s.stella.seq});s=run(s,'stellaUpgrade','hero_54',{seq:s.stella.seq,count:1});s.inventory.Item_Talent_Hero_1=1000;
for(const q of [1,14]){if(q===14){s=run(s,'claimOriginalSupplies');for(let k=1;k<14;k++){while(s.fellows.hero_54.level<100+(k-1)*50){s.fellowXP=1e9;s=run(s,'train','hero_54','max');}s=run(s,'originalQuality','hero_54');}}
const before=structuredClone(s),power=bondedPower(s,'hero_54'),apt=s.fellows.hero_54.aptitude;s=run(s,'trainTalent','hero_54',5);assert.equal(s.fellows.hero_54.aptitude,apt+5*talentRule('hero_54').amount);assert.ok(bondedPower(s,'hero_54')>power);for(const key of ['family','familiars','stella','artifacts','originalProgression'])assert.deepEqual(s[key],before[key]);assert.deepEqual(decode(JSON.stringify(s)),s);}});
