import test from 'node:test';import assert from 'node:assert/strict';import {fresh,act,valid,decode} from '../lib/game.mjs';import {stageEvent,FORGE_REWARD_ITEM} from '../lib/raphael-progress.mjs';import {bondedPower} from '../lib/adventure.mjs';import {trackedCopies} from '../lib/artifacts.mjs';import {createPersistence} from '../lib/persistence.mjs';
const club='Item_Weapon_Equipment_1_1',ore=FORGE_REWARD_ITEM;
const run=(s,a,t=null,v=null,now=s.lastAt)=>{const r=act(s,a,now,t,v);assert.equal(r.error,undefined,r.error);assert.ok(valid(r.state),a);return r.state;};
const event=(s,a,t=null,count=null,now=s.lastAt)=>run(s,a,t,{seq:stageEvent(s).seq,count},now);
function earned(to=390){let s=run(fresh(1000),'stagePlace',12,{kind:'fan',id:'1',level:1});while(stageEvent(s).consumed<to){if(stageEvent(s).stamina<10)s=event(s,'stageSupply');s=event(s,'stageBegin',null,10);s=event(s,'stageComplete',s.raphaelEvent.run.id,null,s.lastAt+5000);}return s;}
test('earned390 milestone→25Ore→two upgrades→recorded recycle→offline reload conserves materials',()=>{let s=earned();assert.equal(s.artifacts,undefined);s=event(s,'stageClaim',390);const claims=structuredClone(s.raphaelEvent.claims);s=event(s,'stageForgeTransfer',ore);assert.equal(s.artifacts.ore,25);assert.equal(s.raphaelEvent.locker[ore],0);assert.deepEqual(s.raphaelEvent.claims,claims);s=run(s,'claimAllGear');s=run(s,'equip','hero_15',club);const power=bondedPower(s,'hero_15');s=run(s,'upgradeArtifactMax','hero_15');assert.equal(s.fellows.hero_15.gearLevel,3);assert.equal(s.fellows.hero_15.gearOreSpent,20);assert.equal(s.artifacts.ore,5);assert.ok(bondedPower(s,'hero_15')>power);s=run(s,'equip','hero_15',null);assert.deepEqual(trackedCopies(s,club),[{level:3,spent:20,count:1}]);s=run(s,'recycleTrackedArtifact',club,{level:3,spent:20});assert.equal(s.artifacts.ore,30);assert.equal(s.inventory[club],0);assert.deepEqual(decode(JSON.stringify(s)),s);assert.equal(s.raphaelEvent.oreTransfers[0].quantity,25);});
test('both source milestones can transfer together or separately; no duplicate or wrong-item transfer',()=>{for(const separate of [true,false]){let s=earned(1200);s=event(s,'stageClaim',390);if(separate)s=event(s,'stageForgeTransfer',ore);s=event(s,'stageClaim',1200);const seq=s.raphaelEvent.seq;s=event(s,'stageForgeTransfer',ore);assert.equal(s.artifacts.ore,75);assert.equal(s.raphaelEvent.oreTransfers.length,separate?2:1);assert.ok(act(s,'stageForgeTransfer',s.lastAt,ore,{seq}).error);assert.ok(act(s,'stageForgeTransfer',s.lastAt,ore,{seq:s.raphaelEvent.seq}).error);assert.ok(act(s,'stageForgeTransfer',s.lastAt,'Item_Box_Weapon_2',{seq:s.raphaelEvent.seq}).error);assert.deepEqual(decode(JSON.stringify(s)),s);}});
test('capacity refusal retains full reward and old claimed quantities transfer without repricing',()=>{let s=event(earned(),'stageClaim',390);s.raphaelEvent.claims[0].quantity=27;s.raphaelEvent.locker[ore]=27;assert.ok(valid(s));s={...s,artifacts:{...(s.artifacts||{ore:0,bag:{}}),ore:1e9-26}};const before=structuredClone(s);assert.ok(act(s,'stageForgeTransfer',s.lastAt,ore,{seq:s.raphaelEvent.seq}).error);assert.deepEqual(s,before);s.artifacts.ore=1e9-27;s=event(s,'stageForgeTransfer',ore);assert.equal(s.artifacts.ore,1e9);assert.equal(s.raphaelEvent.oreTransfers[0].quantity,27);assert.equal(s.raphaelEvent.claims[0].quantity,27);assert.ok(valid(s));});
test('malformed transfers, source conservation and missing claims are rejected without affecting old saves',()=>{const old=event(earned(),'stageClaim',390);assert.deepEqual(decode(JSON.stringify(old)),old);const s=event(old,'stageForgeTransfer',ore);for(const mutate of [e=>e.oreTransfers[0].id=0,e=>e.oreTransfers[0].id=e.history[0].id,e=>e.oreTransfers[0].quantity++,e=>e.oreTransfers[0].itemId='bad',e=>e.oreTransfers.push({...e.oreTransfers[0]}),e=>e.locker[ore]++,e=>e.claims=[null],e=>e.oreTransfers[0].at=s.lastAt+1]){const bad=structuredClone(s);mutate(bad.raphaelEvent);assert.equal(valid(bad),false);assert.throws(()=>decode(JSON.stringify(bad)));}});
test('failed transfer write leaves locker/Forge/receipt unchanged and explicit reload retry credits once',()=>{const s=event(earned(),'stageClaim',390);let raw=JSON.stringify(s),fail=false;const p=createPersistence(()=>({getItem:()=>raw,setItem:(_,v)=>{if(fail)throw Error('quota');raw=v}}));p.load(s.lastAt);fail=true;assert.throws(()=>p.commit(event(p.current,'stageForgeTransfer',ore)));assert.deepEqual(p.current.raphaelEvent,s.raphaelEvent);assert.equal(p.current.artifacts,undefined);fail=false;p.load(s.lastAt);p.commit(event(p.current,'stageForgeTransfer',ore));const saved=raw;p.load(s.lastAt);assert.equal(raw,saved);assert.equal(p.current.artifacts.ore,25);assert.equal(p.current.raphaelEvent.oreTransfers.length,1);assert.ok(act(p.current,'stageForgeTransfer',p.current.lastAt,ore,{seq:p.current.raphaelEvent.seq}).error);});
