import test from 'node:test';import assert from 'node:assert/strict';import {act,fresh,valid,decode} from '../lib/game.mjs';import {expoState,expoStartKey,expoStepKey,expoLocker,expoVisitors,expoRating,EXPO_STALLS,EXPO_STAGES} from '../lib/expo.mjs';import {createPersistence} from '../lib/persistence.mjs';
const run=(s,a,t=null,v=null)=>{const r=act(s,a,s.lastAt,t,v);assert.ok(!r.error,r.error);assert.ok(valid(r.state),'valid after '+a);return r.state};
function prepared(strong=true){let s=fresh(1000);if(strong)s.fellows.hero_15.aptitude=1000;s=run(s,'claimExpoStall','Stall001');return run(s,'assignExpo','Stall001','hero_15')}
function finish(s){while(s.expo.active)s=run(s,'serveExpo',expoStepKey(s));return s}
test('old saves and evidence scope; claim/assignment ownership and stage slots enforced',()=>{const s=fresh(1000);assert.ok(valid(s));assert.deepEqual(decode(JSON.stringify(s)),s);assert.equal(EXPO_STALLS.length,35);assert.equal(EXPO_STAGES.length,5);let n=prepared();assert.ok(act(n,'claimExpoStall',1000,'Stall001').error);assert.ok(act(n,'assignExpo',1000,'Stall101','hero_15').error);n=run(n,'claimExpoStall','Stall101');n=run(n,'assignExpo','Stall101','hero_15');assert.deepEqual(n.expo.assigned,{Stall101:'hero_15'});});
test('mid-run snapshot survives roster changes and reload; stale visitor and start keys refused',()=>{let s=prepared();const start=expoStartKey(s);s=run(s,'startExpo',start);const snap=structuredClone(s.expo.active);assert.ok(act(s,'startExpo',1000,start).error);const key=expoStepKey(s);s=run(s,'serveExpo',key);assert.ok(act(s,'serveExpo',1000,key).error);s.fellows.hero_15.aptitude=10;s=decode(JSON.stringify(s));assert.deepEqual(s.expo.active.slots,snap.slots);assert.deepEqual(s.expo.active.rewards,snap.rewards);s=finish(s);assert.equal(s.expo.clears.length,1);assert.equal(expoLocker(s).Item_Talent_Hero_1,2);assert.ok(act(s,'serveExpo',1000,key).error);});
test('weak route can fail without clear rewards; five stage loop grants source rewards once and spends coins',()=>{let weak=prepared(false);weak=run(weak,'startExpo',expoStartKey(weak));weak=finish(weak);assert.equal(expoRating(weak.expo.last),0);assert.equal(weak.expo.clears.length,0);assert.equal(expoLocker(weak).Item_Talent_Hero_1,0);let s=prepared();for(let n=0;n<5;n++){s=run(s,'startExpo',expoStartKey(s));s=finish(s);assert.equal(s.expo.clears.length,n+1);}assert.ok(act(s,'startExpo',1000,expoStartKey(s)).error);assert.ok(expoLocker(s).item_TowerDefense_2>=100);s=run(s,'claimExpoStall','Stall101');const before=expoLocker(s).item_TowerDefense_2;s=run(s,'upgradeExpo','Stall101',1);assert.equal(expoLocker(s).item_TowerDefense_2,before-100);assert.ok(act(s,'upgradeExpo',1000,'Stall101',1).error);assert.ok(act(s,'upgradeExpo',1000,'Stall001',1).error);s=decode(JSON.stringify(s));const n=expoLocker(s).Item_Talent_Hero_1,k=`pearls:${n}:0`,bag=s.inventory.Item_Talent_Hero_1;s=run(s,'takeExpoPearls',k);assert.equal(s.inventory.Item_Talent_Hero_1,bag+n);assert.ok(act(s,'takeExpoPearls',1000,k).error);});
test('customer goods matching matters; malformed restore and overflow refused',()=>{let s=prepared();s=run(s,'startExpo',expoStartKey(s));const r=structuredClone(s.expo.active);r.step=1;r.customers[0]={goods:'Beverage',funds:5000};r.slots=[{stall:'Stall101',fellow:'hero_15',power:1000,bonus:0,sales:1000,goods:'Food'}];assert.equal(expoVisitors(r)[0].satisfied,false);r.slots[0].goods='Beverage';assert.equal(expoVisitors(r)[0].satisfied,true);for(const mutate of [x=>x.expo.active.slots=[null],x=>x.expo.active.step=6,x=>x.expo.active.customers=null,x=>x.expo.active.rewards=[null],x=>x.expo.active.sequence=99,x=>x.expo.spentCoins=1]){const bad=structuredClone(s);mutate(bad);assert.equal(valid(bad),false);assert.throws(()=>decode(JSON.stringify(bad)));}s=finish(s);s.inventory.Item_Talent_Hero_1=1e6;assert.ok(act(s,'takeExpoPearls',1000,'pearls:2:0').error);assert.equal(expoLocker(s).Item_Talent_Hero_1,2);});
test('failed final write retains the prior customer and no reward; retry/reload grants once',()=>{let s=run(prepared(),'startExpo',expoStartKey(prepared()));for(let i=0;i<4;i++)s=run(s,'serveExpo',expoStepKey(s));let raw=JSON.stringify(s),full=false;const p=createPersistence(()=>({getItem:()=>raw,setItem:(k,v)=>{if(full)throw Error('quota');raw=v}}));p.load(1000);const before=raw,key=expoStepKey(p.current);full=true;assert.throws(()=>p.commit(run(p.current,'serveExpo',key)));assert.equal(raw,before);assert.equal(p.current.expo.active.step,4);full=false;p.load(1000);p.commit(run(p.current,'serveExpo',key));p.load(1000);assert.equal(p.current.expo.clears.length,1);assert.equal(expoLocker(p.current).Item_Talent_Hero_1,2);assert.ok(act(p.current,'serveExpo',1000,key).error);});
