import test from 'node:test';import assert from 'node:assert/strict';import {fresh,act,valid,decode,totalRate} from '../lib/game.mjs';import {newFellow,bondedPower} from '../lib/adventure.mjs';import {expoOperator,expoStartKey,expoStepKey,expoRating,expoVisitors,expoBond} from '../lib/expo.mjs';import data from '../lib/expo-bond-data.json' with {type:'json'};
const run=(s,a,t=null,v=null)=>{const r=act(s,a,s.lastAt,t,v);assert.ok(!r.error,r.error);assert.ok(valid(r.state));return r.state};
function prepared(id='hero_103'){let s=fresh(1000);s.fellows.hero_103={...newFellow(),aptitude:250};s.fellows.hero_15.aptitude=250;s=run(s,'claimExpoStall','Stall203');return run(s,'assignExpo','Stall203',id)}
const start=s=>run(s,'startExpo',expoStartKey(s));const finish=s=>{while(s.expo.active)s=run(s,'serveExpo',expoStepKey(s));return s};
test('twelve exact joins; equal investment changes customer outcome; stronger nonbonded Fellow can still win',()=>{
 assert.equal(data.records.length,12);assert.equal(data.deferred.length,16);for(const b of data.records){let s=fresh(1000);s.fellows[b.fellow]={...newFellow(),aptitude:250};assert.equal(expoOperator(s,b.stall,b.fellow).bond.percent,b.percent);assert.equal(expoOperator(s,b.stall,'hero_15').bond,null);}assert.equal(expoBond('Stall206'),null);
 const a=prepared(),n=prepared('hero_15');assert.equal(bondedPower(a,'hero_103'),bondedPower(n,'hero_15'));assert.equal(totalRate(a),totalRate(n));assert.deepEqual(a.fellows.hero_103,n.fellows.hero_15);const bound=start(a),plain=start(n);assert.equal(bound.expo.active.slots[0].sales,2959);assert.equal(plain.expo.active.slots[0].sales,2690);assert.equal(expoRating(finish(bound).expo.last),5);assert.equal(expoRating(finish(plain).expo.last),0);
 const richer=structuredClone(a);richer.fellows.hero_15.aptitude=300;assert.ok(expoOperator(richer,'Stall203','hero_15').sales>expoOperator(richer,'Stall203','hero_103').sales);
 const wrong=structuredClone(bound.expo.active);wrong.step=1;wrong.customers[0].goods='Food';assert.equal(expoVisitors(wrong)[0].satisfied,false);wrong.customers[0].goods='Beverage';assert.equal(expoVisitors(wrong)[0].satisfied,true);
});
test('policy1 active/clear inputs remain unchanged; next run uses policy2; historical numeric snapshots stay authoritative',()=>{
 let s=start(prepared());s.expo.active.policyVersion=1;for(const x of s.expo.active.slots){delete x.bond;x.power=3000;x.sales=Math.floor(x.power*(1+x.bonus/100));}s.expo.active.step=2;const old=structuredClone(s.expo.active);s=decode(JSON.stringify(s));assert.deepEqual(s.expo.active,old);s=finish(s);assert.deepEqual({...s.expo.clears[0],step:2},old);const oldClear=JSON.stringify(s.expo.clears[0]);s=start(s);assert.equal(s.expo.active.policyVersion,2);assert.equal(s.expo.active.slots[0].bond.percent,10);assert.equal(JSON.stringify(s.expo.clears[0]),oldClear);
 s.fellows.hero_103.aptitude=10;s=decode(JSON.stringify(s));assert.equal(s.expo.active.slots[0].power,2500);const x=s.expo.active.slots[0];x.bond.percent=7;x.sales=Math.floor(x.power*(1+x.bonus/100)*1.07);assert.ok(valid(s));assert.equal(decode(JSON.stringify(s)).expo.active.slots[0].bond.percent,7);
});
test('bond restore rejects mismatched ID, arithmetic, missing snapshot and policy1 backfill',()=>{const s=start(prepared());for(const mutate of [x=>x.expo.active.slots[0].bond.fellow='hero_15',x=>x.expo.active.slots[0].bond.skill='Towerskill_Stall104',x=>x.expo.active.slots[0].bond.percent=-1,x=>x.expo.active.slots[0].sales++,x=>delete x.expo.active.slots[0].bond,x=>x.expo.active.policyVersion=1]){const bad=structuredClone(s);mutate(bad);assert.equal(valid(bad),false);assert.throws(()=>decode(JSON.stringify(bad)));}});
