import test from 'node:test';import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {decode,act,valid} from '../lib/game.mjs';
import {towerState,towerKey,validTower,migrateTower} from '../lib/familiar-tower.mjs';
import {suppliesWaiting,towerIncome,familiarSupplies} from '../lib/familiar-supplies.mjs';
import {dispatchUnlocked,DISPATCH_AREAS,validFamiliarDispatch,dispatchState} from '../lib/familiar-dispatch.mjs';

// CLAUDE.md rule 12. The tower went from a 12-floor sandbox (policy 1) to the original 300 floors
// (policy 2) on 2026-09-16. Two things a save stores are DERIVED from the old floor count: the hourly
// income rate that `familiarSupplies.since` accrues against, and the dispatch gate an in-flight
// `familiarDispatch.run` was admitted under (validFamiliarDispatch re-checks it on every load).
//
// These two saves were GENERATED BY THE PREVIOUS BUILD (bafe728), not written by hand: its lib/ was
// exported with `git archive bafe728 lib`, and scripts/generate-legacy-familiar-saves.mjs was run
// against it. That script adopts all familiars, climbs the sandbox to floor 7 or 12 on earned income,
// trains the five strongest until area 1 accepts them, starts a dispatch, and stops the clock 3.5 hours
// after the last collection with income waiting. The expected figures below were printed BY THAT SAME
// OLD BUILD from those saves, so each assertion compares old-build output to new-build output.
const load=n=>readFileSync(new URL(`./familiar-save-bafe728-floor${n}.json`,import.meta.url),'utf8');
const OLD={
 7:{income:{levelUp:172,classUp:7},waiting:{levelUp:688,classUp:28,hours:4},waiting30h:{levelUp:4128,classUp:168,hours:24},unlocked:[true,true,true,true,true,true,false,false,false]},
 12:{income:{levelUp:187,classUp:8},waiting:{levelUp:748,classUp:32,hours:4},waiting30h:{levelUp:4488,classUp:192,hours:24},unlocked:[true,true,true,true,true,true,true,true,true]},
};

for(const n of [7,12])test(`a floor-${n} sandbox save from the previous build loads with the same income, waiting items and dispatch gates`,()=>{
 const raw=JSON.parse(load(n));
 assert.equal(raw.familiarTower.policyVersion,1,'fixture really is a policy-1 save');assert.equal(raw.familiarTower.cleared,n);
 assert.ok(raw.familiarDispatch.run,'fixture has a dispatch in flight');
 const s=decode(load(n));
 assert.ok(valid(s));
 const t=s.familiarTower;
 assert.equal(t.policyVersion,2);assert.equal(t.cleared,25*n,'local floor n is original floor 25n');
 assert.equal(t.attempts,raw.familiarTower.attempts);assert.deepEqual(t.party,raw.familiarTower.party);
 assert.deepEqual(t.legacy,{cleared:n,attempts:raw.familiarTower.attempts,last:raw.familiarTower.last},'the sandbox record is kept verbatim');
 // NO MINT, NO LOSS: every derived figure equals what the previous build computed from the same save.
 assert.deepEqual(towerIncome(s),OLD[n].income);
 assert.deepEqual(suppliesWaiting(s),OLD[n].waiting);
 assert.deepEqual(suppliesWaiting(s,s.lastAt+30*3600e3),OLD[n].waiting30h);
 assert.deepEqual(DISPATCH_AREAS.map(a=>dispatchUnlocked(s,a.id)),OLD[n].unlocked);
 assert.deepEqual(familiarSupplies(s),raw.familiarSupplies,'stored items and since are untouched');
 assert.deepEqual(dispatchState(s),raw.familiarDispatch,'the run in flight is untouched');assert.ok(validFamiliarDispatch(s));
 assert.deepEqual(s.familiars,raw.familiars,'every owned familiar is kept');
 // Loading twice is inert, and the migrated save round-trips.
 assert.deepEqual(decode(JSON.stringify(s)),s);
 // Collecting pays exactly the old waiting amount.
 const c=act(s,'collectFamiliarSupplies',s.lastAt);assert.equal(c.error,undefined);
 assert.equal(familiarSupplies(c.state).levelUp,raw.familiarSupplies.levelUp+OLD[n].waiting.levelUp);
 assert.equal(familiarSupplies(c.state).classUp,raw.familiarSupplies.classUp+OLD[n].waiting.classUp);
});

test('a migrated save climbs on from floor 25n+1 and its next clear is an original floor',()=>{
 const s=decode(load(7));
 const r=act(s,'towerFight',s.lastAt,towerKey(s));assert.equal(r.error,undefined);
 assert.equal(r.state.familiarTower.last.floor,176);assert.ok(valid(r.state));
 assert.deepEqual(r.state.familiarTower.legacy,s.familiarTower.legacy);
 assert.deepEqual(decode(JSON.stringify(r.state)),r.state);
 // A migrated save cannot skip the migration base: floor 300 is not claimable by editing cleared.
 const edited={...s,familiarTower:{...s.familiarTower,cleared:300}};assert.equal(validTower(edited),false,'cleared must equal 25n until a new report exists');
 const shrunk={...s,familiarTower:{...s.familiarTower,cleared:174}};assert.equal(validTower(shrunk),false,'nor fall below it');
});

test('migrateTower is exact and inert on anything but a policy-1 record',()=>{
 const legacy={policyVersion:1,cleared:3,attempts:5,party:['a'],last:{x:1}};
 assert.deepEqual(migrateTower(legacy),{policyVersion:2,cleared:75,attempts:5,party:['a'],last:null,legacy:{cleared:3,attempts:5,last:{x:1}}});
 const v2={policyVersion:2,cleared:4,attempts:4,party:[],last:null};assert.equal(migrateTower(v2),v2);
 assert.equal(migrateTower(undefined),undefined);
 assert.equal(towerState({}).policyVersion,2);
});
