import test from 'node:test';import assert from 'node:assert/strict';import {fresh,act,valid,decode} from '../lib/game.mjs';import {FAMILY_PICTURES,familyPictures,pictureGate} from '../lib/family-gallery.mjs';import {FAMILY} from '../lib/catalog.mjs';
const go=(s,a,t=null,v=null)=>{const r=act(s,a,s.lastAt,t,v);assert.ok(!r.error,r.error);assert.ok(valid(r.state));return r.state};
const start=intimacy=>{let s=go(fresh(1000),'welcome','wife_1');s.family.wife_1.intimacy=intimacy;return s};const date=s=>go(s,'date',null,(FAMILY.filter(f=>s.family[f.id]).findIndex(f=>f.id==='wife_1')+.5)/Object.keys(s.family).length);
test('source inventory counts and exact regional assets remain distinct from ownership',()=>{assert.equal(FAMILY_PICTURES.length,175);assert.equal(FAMILY_PICTURES.filter(r=>r.image).length,160);assert.equal(new Set(FAMILY_PICTURES.map(r=>r.event)).size,175);assert.equal(FAMILY_PICTURES.filter(r=>!r.image).length,15);assert.ok(FAMILY_PICTURES.some(r=>r.requiredEnglishPackage!=='Illust'&&r.image));assert.ok(FAMILY_PICTURES.filter(r=>r.clothingVariant).every(r=>pictureGate(r)));});
test('Gina threshold boundary, once per date, ordering, existing Energy and points preserved',()=>{let s=start(49);s=date(s);assert.equal(s.familyGallery,undefined);s.family.wife_1.intimacy=50;const energy=s.energy,points=s.family.wife_1.points;s=date(s);assert.deepEqual(Object.keys(s.familyGallery.owned),['Wife1_DateDialogue5']);assert.equal(s.energy,energy-1);assert.ok(s.family.wife_1.points>points);assert.equal(s.familyGallery.owned.Wife1_DateDialogue5.seen,false);s=date(s);assert.equal(Object.keys(s.familyGallery.owned).length,1);s=act(s,'galleryView',s.lastAt+180000,'Wife1_DateDialogue5').state;s.family.wife_1.intimacy=150;s=date(s);s=date(s);assert.deepEqual(Object.keys(s.familyGallery.owned),['Wife1_DateDialogue5','Wife1_DateDialogue4','Wife1_DateDialogue3']);assert.deepEqual(decode(JSON.stringify(s)),s)});
test('old aggregate dates, welcome and gifts do not invent discoveries; view and replay are neutral',()=>{let s=start(150);s.stats.dates=500;assert.equal(decode(JSON.stringify(s)).familyGallery,undefined);assert.ok(act(s,'galleryView',1000,'Wife1_DateDialogue3').error);s=date(s);const before=structuredClone(s);s=go(s,'galleryView','Wife1_DateDialogue5');assert.equal(s.familyGallery.owned.Wife1_DateDialogue5.seen,true);const {familyGallery,...rest}=s;const {familyGallery:_,...prior}=before;assert.deepEqual(rest,prior);assert.deepEqual(go(s,'galleryView','Wife1_DateDialogue5'),s);assert.ok(act(s,'galleryView',1000,'Wife6_DateDialogue2').error)});
test('auto dates discover at most one per successful sub-date without duplicate outer grant',()=>{let s=start(1000);const r=act(s,'autoDate',s.lastAt,null,[.5,.5,.5]);assert.ok(!r.error,r.error);assert.equal(Object.keys(r.state.familyGallery.owned).length,3);assert.equal(r.state.stats.dates,s.stats.dates+3);assert.equal(r.state.energy,0)});
test('unsupported, missing and malformed records rejected without rewriting old saves',()=>{const base=date(start(150));for(const edit of [s=>s.familyGallery.policyVersion=2,s=>s.familyGallery.owned=[],s=>s.familyGallery.owned.Wife1_DateDialogue5.seen=1,s=>s.familyGallery.owned.Wife1_DateDialogue5.unlockedAt=-1,s=>s.familyGallery.owned.missing={unlockedAt:1,seen:false},s=>delete s.family.wife_1]){const s=structuredClone(base);edit(s);assert.equal(valid(s),false);assert.throws(()=>decode(JSON.stringify(s)))}for(const r of FAMILY_PICTURES.filter(pictureGate)){const s=structuredClone(base);s.familyGallery.owned[r.event]={unlockedAt:1,seen:false};assert.equal(valid(s),false)}});
test('selected humanized pair changes art references only, keeps source identity and no double Family background',async()=>{const {FELLOWS}=await import('../lib/catalog.mjs');const {familyScene}=await import('../lib/family-scenes.mjs');const g=FAMILY.find(x=>x.id==='wife_1'),f=FELLOWS.find(x=>x.id==='hero_1');assert.equal(g.art,'humanized/wife_01.webp');assert.equal(f.art,'humanized/hero_01.webp');assert.equal(f.portrait,f.art);assert.equal(familyScene(g).background,null);assert.equal(familyScene(g,'date').mode,'composed');assert.equal(FAMILY.length,105);assert.equal(FELLOWS.length,154)});
