import test from 'node:test';import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {decode,act,valid} from '../lib/game.mjs';
import {towerState,towerKey,validTower,migrateTower,TOWER_DATA,floorRewardItems} from '../lib/familiar-tower.mjs';
import {suppliesWaiting,towerIncome,familiarSupplies,towerReachOf} from '../lib/familiar-supplies.mjs';
import {dispatchUnlocked,DISPATCH_AREAS,dispatchState,validFamiliarDispatch} from '../lib/familiar-dispatch.mjs';
import {exploreState,validFamiliarExplore} from '../lib/familiar-explore.mjs';
import {HELPER_TASKS} from '../lib/helper.mjs';

// The owner, 2026-09-16: "Re-do floor since I don't ever remember actually doing them." Sandbox-era towers restart
// the 300 floors at 0 (lib/familiar-tower.mjs policy 3). CLAUDE.md rule 12: every fixture below was GENERATED by an
// older build, never written by hand, and every "OLD" figure was printed by that build from the same save:
//  * familiar-save-bafe728-floor{7,12}.json  -- the 12-floor sandbox build (scripts/generate-legacy-familiar-saves.mjs)
//  * familiar-save-6b13d1a-*.json            -- the LIVE 25n build, which the owner's save has probably loaded
//                                               (scripts/generate-live-familiar-saves.mjs)
const H=3600e3;
const load=name=>readFileSync(new URL(`./familiar-save-${name}.json`,import.meta.url),'utf8');
const OLD={
 'bafe728-floor7':{waiting:{levelUp:688,classUp:28},unlocked:[true,true,true,true,true,true,false,false,false],reach:175},
 'bafe728-floor12':{waiting:{levelUp:748,classUp:32},unlocked:[true,true,true,true,true,true,true,true,true],reach:300},
 '6b13d1a-climbed180':{waiting:{levelUp:522,classUp:21},unlocked:[true,true,true,true,true,true,false,false,false],reach:180,area:2,prepaid:{from:176,to:180}},
 '6b13d1a-floor300':{waiting:{levelUp:748,classUp:32},unlocked:[true,true,true,true,true,true,true,true,true],reach:300},
};

for(const [name,old] of Object.entries(OLD))test(`${name}: resets to floor 0 once, keeps every item already earned, and loses no unlock`,()=>{
 const raw=JSON.parse(load(name)),s=decode(load(name)),t=s.familiarTower;
 assert.ok([1,2].includes(raw.familiarTower.policyVersion),'fixture is an old policy');
 if(raw.familiarTower.policyVersion===2)assert.ok(raw.familiarTower.legacy,'fixture is a live-migrated sandbox save');
 assert.ok(valid(s));
 assert.equal(t.policyVersion,3);assert.equal(t.cleared,0);assert.equal(t.last,null);
 assert.equal(t.base,raw.familiarTower.attempts);assert.equal(t.attempts,raw.familiarTower.attempts);assert.deepEqual(t.party,raw.familiarTower.party);
 assert.equal(t.redoFrom,old.reach);assert.deepEqual(t.prepaid,old.prepaid);
 // NO LOSS: the income that was waiting at the old floor's rate is settled into the store on load.
 const f=familiarSupplies(s),rf=raw.familiarSupplies;
 assert.deepEqual({levelUp:f.levelUp-rf.levelUp,classUp:f.classUp-rf.classUp},old.waiting,'waiting income banked at the old rate');
 assert.deepEqual(suppliesWaiting(s),{levelUp:0,classUp:0,hours:0},'and not waiting a second time');
 assert.deepEqual(towerIncome(s),{levelUp:0,classUp:0},'the hourly rate is that of the floor actually climbed: none yet');
 // NO LOST ACCESS: dispatch and exploring areas unlock from the floor reached before the redo.
 assert.equal(towerReachOf(s),old.reach);
 assert.deepEqual(DISPATCH_AREAS.map(a=>dispatchUnlocked(s,a.id)),old.unlocked);
 assert.deepEqual(dispatchState(s),raw.familiarDispatch,'the run already out is untouched');assert.ok(validFamiliarDispatch(s));
 if(old.area){assert.equal(exploreState(s).area,old.area);assert.ok(validFamiliarExplore(s));}
 // NO CLAWBACK: familiars, pearls, EXP.
 assert.deepEqual(s.familiars,raw.familiars);assert.equal(s.fellowXP,raw.fellowXP);assert.equal(s.inventory.Item_Talent_Hero_1,raw.inventory.Item_Talent_Hero_1);
 // EXACTLY ONCE: loading the reset save again changes nothing.
 assert.deepEqual(decode(JSON.stringify(s)),s);
 // The run out is still collectable when it is done.
 if(raw.familiarDispatch.run){const back=act(s,'dispatchCollect',raw.familiarDispatch.run.since+20*H);assert.equal(back.error,undefined);assert.equal(dispatchState(back.state).run,null);assert.ok(valid(back.state));}
});

test('a genuine live-build climb (no legacy marker) is NOT reset, and its version-10 report still replays',()=>{
 const raw=JSON.parse(load('6b13d1a-genuine40')),s=decode(load('6b13d1a-genuine40'));
 assert.equal(raw.familiarTower.policyVersion,2);assert.equal(raw.familiarTower.legacy,undefined);
 assert.deepEqual(s.familiarTower,{...raw.familiarTower,policyVersion:3,base:0});
 assert.equal(s.familiarTower.last.combatVersion,10);assert.ok(valid(s));
 // Live-build figures, printed by 6b13d1a for this save.
 assert.deepEqual(towerIncome(s),{levelUp:116,classUp:4});assert.deepEqual(suppliesWaiting(s),{levelUp:232,classUp:8,hours:2});
 assert.deepEqual(familiarSupplies(s),raw.familiarSupplies,'nothing settled: the floor did not change');
 assert.deepEqual(decode(JSON.stringify(s)),s);
 // Its next fight writes a version-11 report on floor 41.
 const r=act(s,'towerFight',s.lastAt,towerKey(s));assert.equal(r.error,undefined);assert.equal(r.state.familiarTower.last.combatVersion,11);assert.equal(r.state.familiarTower.last.floor,41);assert.ok(valid(r.state));
});

test('the redo climb pays every one-time reward once -- except floors the live build already paid -- and the tower familiars',()=>{
 let s=decode(load('6b13d1a-climbed180'));
 // Remove one tower familiar so its join is observable (the fixture adopted all 71).
 const {Pet_21131,...rest}=s.familiars;s={...s,familiars:rest,familiarTower:{...s.familiarTower,party:s.familiarTower.party.filter(id=>id!=='Pet_21131')},familiarDispatch:{...s.familiarDispatch,run:null,team:[]}};
 assert.ok(valid(s));
 const before=familiarSupplies(s),items=exploreState(s).items;
 while(towerState(s).cleared<180){const r=act(s,towerState(s).cleared<30?'towerFight':'towerAuto',s.lastAt,towerKey(s));assert.equal(r.error,undefined);assert.ok(towerState(r.state).cleared>towerState(s).cleared,`stalled at ${towerState(s).cleared}`);s=r.state;}
 s=decode(JSON.stringify(s));assert.ok(towerState(s).cleared>=180&&towerState(s).cleared<190,'auto stops within one batch of 180');
 const paid=TOWER_DATA.floors.filter(f=>f.floor<=towerState(s).cleared&&!(f.floor>=176&&f.floor<=180));
 const sum=k=>paid.reduce((n,f)=>n+(f.reward[k]||0),0);
 assert.equal(familiarSupplies(s).levelUp-before.levelUp,sum('levelUp'),'floors 176-180 were paid before the redo and pay nothing now');
 assert.equal(familiarSupplies(s).classUp-before.classUp,sum('classUp'));
 assert.equal(exploreState(s).items.Item_PetCatch2-items.Item_PetCatch2,sum('Item_PetCatch2'));
 assert.deepEqual(s.familiars.Pet_21131,{level:1,stars:0},'floor 60 familiar joins on the redo');
 assert.ok(exploreState(s).pieces.Pet_11141>=100,'floor 100 familiar already owned pays its fragments');
 assert.deepEqual(towerIncome(s),{levelUp:TOWER_DATA.floors[towerState(s).cleared-1].income[0],classUp:TOWER_DATA.floors[towerState(s).cleared-1].income[1]});
 assert.equal(towerReachOf(s),Math.max(180,towerState(s).cleared));
});

test('the helper familiarTower chore climbs a reset tower from floor 1',()=>{
 const s=decode(load('bafe728-floor12'));
 const r=HELPER_TASKS.find(t=>t.id==='familiarTower').run(s,act,s.lastAt);
 assert.ok(towerState(r.state).cleared>0,'the chore cleared floors');assert.ok(valid(r.state));
 assert.equal(towerState(r.state).cleared,towerState(r.state).attempts-towerState(r.state).base,'every recorded attempt was a win');
});

test('NEGATIVE CONTROL: the reset cannot be forged or skipped',()=>{
 const s=decode(load('bafe728-floor7')),t=s.familiarTower;
 const bad=(x,why)=>assert.equal(validTower({...s,familiarTower:x}),false,why);
 bad({...t,cleared:175},'claiming the old floor without reports');
 bad({...t,base:t.attempts+1},'a base above attempts');
 bad({...t,redoFrom:301},'a reach past the top');
 bad({...t,prepaid:{from:1,to:300}},'prepaid floors beyond the reach');
 bad({...t,policyVersion:2},'a policy-2 record without its 25n floor');
 bad({...t,legacy:{...t.legacy,cleared:12}},'a legacy record that does not replay');
 bad({...t,extra:1},'an unknown key');
 // migrateTower is exact.
 assert.deepEqual(migrateTower({policyVersion:1,cleared:3,attempts:5,party:['a'],last:{x:1}}),{policyVersion:3,cleared:0,attempts:5,base:5,party:['a'],last:null,legacy:{cleared:3,attempts:5,last:{x:1}},redoFrom:75});
 assert.deepEqual(migrateTower({policyVersion:2,cleared:80,attempts:9,party:[],last:{y:1},legacy:{cleared:3,attempts:5,last:null}}),{policyVersion:3,cleared:0,attempts:9,base:9,party:[],last:null,legacy:{cleared:3,attempts:5,last:null},redoFrom:80,prepaid:{from:76,to:80}});
 const p3={policyVersion:3,cleared:4,attempts:4,base:0,party:[],last:null};assert.equal(migrateTower(p3),p3);
 assert.equal(floorRewardItems(1).length,1);
});
