import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import data from '../lib/familiar-status-data.json' with {type:'json'};
import {putStatus,statusDamage,tickStatuses,statusTargets,statusBattle} from '../lib/familiar-status-combat.mjs';
import {towerBattle,towerSkill,towerKey} from '../lib/familiar-tower.mjs';import {fresh,act,valid,decode} from '../lib/game.mjs';import {createPersistence} from '../lib/persistence.mjs';
const unit=(id,side=0,slot=0)=>({id,side,slot,ATK:100,HP:10000,hp:10000,SPD:100,rage:100,statuses:[]});
test('17 whole source skills execute all admitted effects; no admission to old combat versions',()=>{
 assert.equal(data.skills.length,17);for(const r of data.skills){assert.match(r.sha256,/^[a-f0-9]{64}$/);assert.equal(towerSkill(r.id,3),undefined);assert.equal(towerSkill(r.id).name,r.name);const team=[unit(r.id),unit('ally',0,1),...[0,1,2].map(i=>unit('enemy'+i,1,i))];const run=statusBattle(team,1,id=>id===r.id?r:null);assert.ok(run.log.some(x=>x.attacker===r.id&&x.kind==='status'&&x.status===r.status.kind),r.id);if(['bleed','poison'].includes(r.status.kind))assert.ok(run.log.some(x=>x.attacker===r.id&&x.kind===r.status.kind&&x.damage>0),r.id);if(r.kind==='damage')assert.ok(run.log.some(x=>x.attacker===r.id&&x.kind==='damage'&&x.damage>0),r.id);assert.deepEqual(statusBattle(team,1,id=>id===r.id?r:null),run);assert.ok(team.every(x=>!x.statuses.length&&x.hp===10000));}
});
test('periodic effects skip cast round, snapshot ATK, tick exact duration and refresh same source',()=>{
 const a=unit('a'),b=unit('b',1),log=[];putStatus(b,a,{kind:'bleed',percent:200,turns:2},1,'Bleed');a.ATK=500;tickStatuses([a,b],1,log);assert.equal(log.length,0);tickStatuses([a,b],2,log);assert.equal(b.hp,9800);tickStatuses([a,b],3,log);assert.equal(b.hp,9600);tickStatuses([a,b],4,log);assert.equal(log.length,2);assert.equal(b.statuses.length,0);
 putStatus(b,a,{kind:'poison',percent:100,turns:3},4,'Poison');putStatus(b,a,{kind:'poison',percent:50,turns:2},5,'Poison');assert.equal(b.statuses.length,1);assert.equal(b.statuses[0].value,250);tickStatuses([a,b],5,log);assert.equal(b.hp,9600);tickStatuses([a,b],6,log);assert.equal(b.hp,9350);
});
test('shields conserve capacity, absorb DOT and refresh; vulnerability stacks only independent casters',()=>{
 const a=unit('a'),c=unit('c'),b=unit('b',1);putStatus(b,b,{kind:'shield',percent:300,turns:2},1,'Shield');assert.deepEqual(statusDamage(b,100),{damage:0,absorbed:100});assert.deepEqual(statusDamage(b,250),{damage:50,absorbed:200});putStatus(b,b,{kind:'shield',percent:300,turns:2},2,'Shield');assert.equal(b.statuses.filter(x=>x.kind==='shield').length,1);putStatus(b,a,{kind:'poison',percent:200,turns:2},2,'Poison');const log=[];tickStatuses([a,b],3,log);assert.equal(log[0].absorbed,200);assert.equal(b.hp,9950);
 b.statuses=[];putStatus(b,a,{kind:'vulnerable',percent:15,turns:3},3,'Weak');putStatus(b,a,{kind:'vulnerable',percent:25,turns:3},4,'Weak');putStatus(b,c,{kind:'vulnerable',percent:15,turns:3},4,'Weak');assert.equal(b.statuses.length,2);assert.deepEqual(statusDamage(b,100),{damage:140,absorbed:0});
});
test('highest/lowest/front/back/all targeting stays alive and on intended side',()=>{
 const a=unit('a'),b=unit('b',0,1),en=[0,1,2,3].map(i=>({...unit('e'+i,1,i),hp:100+i*100})),all=[a,b,...en];en[3].hp=0;
 const targets=(kind,targeting,n=5)=>statusTargets(all,a,{kind,targeting,targets:n},1,1).map(x=>x.id);
 assert.deepEqual(targets('dot','highest',1),['e2']);assert.deepEqual(targets('dot','lowest',1),['e0']);assert.deepEqual(targets('damage','back'),['e2']);assert.deepEqual(targets('shield','front'),['a','b']);assert.deepEqual(targets('dot','all'),['e0','e1','e2']);en[2].hp=0;assert.deepEqual(targets('damage','back'),['e0','e1']);
});
test('simultaneous periodic defeats tick both teams without resurrection or negative health',()=>{
 const a=unit('a'),b=unit('b',1);a.hp=10;b.hp=10;putStatus(a,b,{kind:'bleed',percent:100,turns:2},1,'B');putStatus(b,a,{kind:'poison',percent:100,turns:2},1,'P');const log=[];tickStatuses([a,b],2,log);assert.equal(a.hp,0);assert.equal(b.hp,0);assert.equal(log.length,2);tickStatuses([a,b],3,log);assert.equal(log.length,2);
});
test('legacy v1-v3 results are byte-for-byte unchanged',()=>{const team=['Pet_21121','Pet_11321','Pet_11141'].map(id=>({id,level:10,stars:0}));for(const v of [1,2,3])assert.equal(createHash('sha256').update(JSON.stringify(towerBattle(9,team,v))).digest('hex'),v===1?'55145aa8705ec06510cc9cedc51ef345374f23992bea920fbd8ede1d3f708bdd':'4e45c4f3d520fb873780cdf2e742a7f10b688b09d675e0c6ad0d07a21f9ceed6');});
test('new attempt uses current version, old snapshots stay frozen, failed write retries once and rewards survive reload',()=>{
 let s=fresh(1000);for(const id of ['Pet_21121','Pet_23331','Pet_3191']){s=act(s,'adoptFamiliar',1000,id).state;s=act(s,'towerParty',1000,id).state;}const key=towerKey(s),next=act(s,'towerFight',1000,key).state;assert.ok(valid(next));assert.equal(next.familiarTower.last.combatVersion,10);let raw=JSON.stringify(s),fail=false;const p=createPersistence(()=>({getItem:()=>raw,setItem:(_,v)=>{if(fail)throw Error('quota');raw=v}}));p.load(1000);fail=true;assert.throws(()=>p.commit(next));assert.equal(p.current.familiarTower.last,null);fail=false;p.load(1000);p.commit(act(p.current,'towerFight',1000,key).state);assert.ok(act(p.current,'towerFight',1000,key).error);const report=towerBattle(1,p.current.familiarTower.last.team,6),last=structuredClone(p.current.familiarTower.last);s=act(p.current,'trainFamiliar',1000,'Pet_21121',10).state;assert.deepEqual(s.familiarTower.last,last);assert.deepEqual(towerBattle(1,s.familiarTower.last.team,6),report);assert.deepEqual(decode(JSON.stringify(s)),s);
});
