import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,act,valid,decode,totalRate} from '../lib/game.mjs';
import {FISH_COMBINATIONS,castKey,fishingBonuses,fishingDateBonus,fishingEmployeeBonus} from '../lib/fishing.mjs';
import {educationReward,SCHOOL_TYPES} from '../lib/education.mjs';
import {pupilReward} from '../lib/school.mjs';import {createPersistence} from '../lib/persistence.mjs';
const run=(s,a,t=null,v=null)=>{const r=act(s,a,s.lastAt,t,v);assert.ok(!r.error,r.error);assert.ok(valid(r.state));return r.state};
const combos=FISH_COMBINATIONS.filter(c=>c.effect.kind==='educationXP');
function ready(type='inspiring'){let s=run(fresh(1000),'welcome','wife_2');s=run(s,'enroll','wife_2',type);for(let n=0;n<65;n++){if(!s.fishing?.bait)s=run(s,'claimBait');s=run(s,'castFish',castKey(s));}return s}
const activate=(s,list=combos)=>list.reduce((s,c)=>run(s,'activateFishCombination',c.id),s);
test('ten exact normal education scopes; typed matches and all-pupil includes legacy without leaking',()=>{assert.equal(combos.length,10);assert.equal(combos.filter(c=>c.effect.type===null).length,5);const base=ready();for(const c of combos){const s=activate(base,[c]);for(const type of [...SCHOOL_TYPES,'curious','creative']){const r=educationReward(s,{type},1);assert.equal(r.percent,c.effect.type===null||c.effect.type===type?c.effect.value:0);}assert.deepEqual(fishingBonuses(s,'hero_15'),{flat:0,aptitude:0,percent:0});assert.equal(fishingDateBonus(s),0);assert.equal(fishingEmployeeBonus(s,'Inspiring'),0);assert.equal(totalRate(s),totalRate(base));assert.equal(pupilReward(s,s.school.pupils[0]),pupilReward(base,base.school.pupils[0]));assert.equal(s.fellowXP,base.fellowXP);}});
test('additive 85% rounds each award; manual class and batch agree with fractional points and final partial batch',()=>{let s=activate(ready());s.school.points=2.5;const r=educationReward(s,s.school.pupils[0],1,2);assert.equal(r.percent,85);assert.equal(r.perAward,18);assert.equal(r.total,36);const manual=run(run(s,'educate',1,'class'),'educate',1,'class'),batch=run(s,'educateBatch',1);assert.deepEqual(batch,manual);assert.equal(batch.school.points,.5);assert.equal(batch.fellowXP,s.fellowXP+36);let near=structuredClone(s);near.school.pupils[0].progress=5;near.school.pupils[0].education=5;const last=run(near,'educateBatch',1);assert.equal(last.fellowXP,near.fellowXP+18);assert.equal(last.school.points,1.5);assert.equal(last.school.pupils[0].progress,6);assert.ok(act(last,'educateBatch',1000,1).error);});
test('free finish pays remaining awards only, cap reports actual credit, zero-credit still uses class point',()=>{let s=activate(ready());const finish=run(s,'finishSchool',1);assert.equal(finish.fellowXP,s.fellowXP+108);assert.equal(finish.school.points,s.school.points);s.fellowXP=1e9-7;let r=act(s,'educate',1000,1,'class');assert.match(r.message,/\+7 Fellow EXP/);assert.equal(r.state.fellowXP,1e9);r=act(r.state,'educate',1000,1,'class');assert.match(r.message,/\+0 Fellow EXP/);assert.equal(r.state.school.points,4);const batch=act(s,'finishSchool',1000,1);assert.match(batch.message,/\+7 Fellow EXP/);assert.equal(batch.state.fellowXP,1e9);});
test('historical quantity and activation scope survive reload; malformed policies/types rejected',()=>{let s=activate(ready(),[combos.find(c=>c.effect.type==='inspiring')]);s.fishing.combinations[0].effect.value=27;s=decode(JSON.stringify(s));assert.equal(educationReward(s,s.school.pupils[0],1).perAward,12);for(const mutate of [x=>x.fishing.combinations[0].effect.type='brave',x=>delete x.fishing.combinations[0].effect.type,x=>x.fishing.combinations[0].policyVersion=3,x=>x.fishing.combinations[0].effect.kind='employee']){const bad=structuredClone(s);mutate(bad);assert.equal(valid(bad),false);assert.throws(()=>decode(JSON.stringify(bad)));}assert.deepEqual(decode(JSON.stringify(s)),s);});
test('activation settles prior income; graduated receipts and caught history unchanged',()=>{let s=ready();s=run(s,'finishSchool',1);s=run(s,'graduate',1);const old=structuredClone(s),r=act(s,'activateFishCombination',2000,combos[0].id);assert.ok(!r.error);assert.equal(r.state.pending,s.pending+totalRate(s));assert.deepEqual(r.state.school,old.school);assert.deepEqual(r.state.fishing.catches,old.fishing.catches);assert.equal(r.state.fellowXP,old.fellowXP);});
test('failed education write preserves XP and lesson, recovery grants one award and training spends shared XP',()=>{const s=activate(ready());let raw=JSON.stringify(s),full=false;const p=createPersistence(()=>({getItem:()=>raw,setItem:(k,v)=>{if(full)throw Error('quota');raw=v}}));p.load(1000);const before=raw;full=true;assert.throws(()=>p.commit(run(p.current,'educate',1,'class')));assert.equal(raw,before);assert.equal(p.current.fellowXP,s.fellowXP);full=false;p.load(1000);p.commit(run(p.current,'educate',1,'class'));p.load(1000);assert.equal(p.current.school.pupils[0].progress,1);assert.equal(p.current.fellowXP,s.fellowXP+18);const beforeTrain=p.current;p.commit(run(beforeTrain,'train','hero_15',1));assert.equal(p.current.fellows.hero_15.level,beforeTrain.fellows.hero_15.level+1);assert.ok(p.current.fellowXP<beforeTrain.fellowXP);p.load(1000);assert.equal(p.current.school.pupils[0].progress,1);});
