import test from 'node:test';import assert from 'node:assert/strict';import {fresh,act,decode,settle} from '../lib/game.mjs';import {habitPeriod,validHabits,exportHabitTasks} from '../lib/habits.mjs';
const date=s=>new Date(s+'T12:00:00').getTime();const start=date('2026-09-07');
function add(s=fresh(start),spec={}){const r=act(s,'habitSave',s.lastAt,null,{title:'Task',...spec});assert(!r.error,r.error);return r.state}
function doAct(s,a,t=null,v=null,now=s.lastAt){const r=act(s,a,now,t,v);assert(!r.error,r.error);assert(validHabits(r.state));return r.state}
test('optional subtree round-trip preserves old save and rejects malformed tracker',()=>{const s=fresh(start);assert.deepEqual(decode(JSON.stringify(s)),s);const a=add(s);assert.deepEqual(decode(JSON.stringify(a)),a);assert.throws(()=>decode(JSON.stringify({...s,habits:{version:1}})));});
test('completion reward, uncheck/recheck and independent undo conserve Gold',()=>{let s=add();s=doAct(s,'habitComplete','h1');assert.equal(s.gold,270);s=doAct(s,'habitUncheck','h1');s=doAct(s,'habitComplete','h1');assert.equal(s.gold,270);s=doAct(s,'habitUndo');assert.equal(s.gold,270);assert.equal(s.habits.items[0].done,false);s=doAct(s,'habitComplete','h1');assert.equal(s.gold,270);});
test('initial undo reverses exact reward, later gameplay blocks undo',()=>{let s=doAct(add(),'habitComplete','h1');s=doAct(s,'habitUndo');assert.equal(s.gold,250);assert.equal(s.habits.history.length,0);s=doAct(s,'habitComplete','h1');s=doAct(s,'collect');assert.equal(s.habits.undo,null);assert(act(s,'habitUndo',s.lastAt).error);});
test('atomic batch, cap and invalid selection',()=>{let s=add(fresh(start),{diff:'hard'});s=add(s,{title:'Other',diff:'hard'});s=doAct(s,'habitSettings',null,{dailyGoldCap:40});const bad=act(s,'habitBatch',start,null,['h1','missing']);assert(bad.error);assert.equal(bad.state.gold,s.gold);s=doAct(s,'habitBatch',null,['h1','h2']);assert.equal(s.gold,290);assert.equal(s.habits.history.length,2);s=doAct(s,'habitUndo');assert.equal(s.gold,250);});
test('weekday gaps, Monday weeks, month ends and quarter recurrence',()=>{let s=add(fresh(date('2026-09-04')),{days:[1,2,3,4,5]});s=doAct(s,'habitComplete','h1');s=settle(s,date('2026-09-07'));assert.equal(s.habits.items[0].streak,1);s=doAct(s,'habitComplete','h1');assert.equal(s.habits.items[0].streak,2);s=settle(s,date('2026-09-09'));assert.equal(s.habits.items[0].streak,0);assert.equal(habitPeriod('weekly',date('2026-09-13')),'w:2026-09-07');assert.equal(habitPeriod('weekly',date('2026-09-14')),'w:2026-09-14');let m=add(fresh(date('2028-01-31')),{freq:'monthly'});m=doAct(m,'habitComplete','h1');m=settle(m,date('2028-02-29'));assert.equal(m.habits.items[0].streak,1);m=doAct(m,'habitComplete','h1');m=settle(m,date('2028-03-31'));assert.equal(m.habits.items[0].streak,2);assert.equal(habitPeriod('quarterly',date('2026-03-31')),'q:2026-1');assert.equal(habitPeriod('quarterly',date('2026-04-01')),'q:2026-2');});
test('clock rollback and frequency edits cannot pay one occurrence twice',()=>{let s=doAct(add(),'habitComplete','h1');s=doAct(s,'habitSave','h1',{freq:'weekly'});s=doAct(s,'habitComplete','h1');s=doAct(s,'habitSave','h1',{freq:'daily'});const old=s.gold;s=doAct(s,'habitComplete','h1');assert.equal(s.gold,old);s=settle(s,date('2026-09-06'));assert.equal(s.habits.lastNow,start);});
test('off-day cannot complete even through action API',()=>{const s=add(fresh(start),{days:[2]});assert(act(s,'habitComplete',start,'h1').error);});
test('merge templates preserves progress and retire list; no imported rewards',()=>{let s=doAct(add(),'habitComplete','h1');s=doAct(s,'habitImport',null,{dailies:[{title:' TASK ',notes:'new',activeDays:[1],link:'https://example.com',memo:'private'},{title:'Review',review:true,freq:'monthly'}]});assert.equal(s.gold,270);assert(s.habits.items[0].done);assert.equal(s.habits.items[0].memo,'private');const exported=exportHabitTasks(s.habits);let n=doAct(fresh(start),'habitImport',null,exported);assert.equal(n.habits.items.length,2);assert(!n.habits.items[0].done);assert.equal(n.gold,250);n=doAct(n,'habitImport',null,{tasks:[],retire:['task']});assert.equal(n.habits.items.length,1);});
test('guided plan once, trust once weekly, updated statuses do not duplicate checks',()=>{let s=doAct(fresh(start),'habitCheck','0','attention');s=doAct(s,'habitCheck','0','urgent');assert.equal(s.habits.history.length,1);s=doAct(s,'habitPlan','0','Restock');s=doAct(s,'habitFinishReview');assert.equal(s.habits.items.length,1);assert.equal(s.habits.trustWeeks.length,1);s=doAct(s,'habitFinishReview');assert.equal(s.habits.items.length,1);assert.equal(s.habits.trustWeeks.length,1);assert.equal(s.gold,250);});
test('streak protection consumes one token for a group and milestones cannot regrant',()=>{let s=add();s=add(s,{title:'Second'});s=doAct(s,'habitBatch',null,['h1','h2']);s.habits.grace=1;s=settle(s,date('2026-09-09'));assert.equal(s.habits.grace,0);assert.equal(s.habits.items[0].streak,1);assert.equal(s.habits.items[1].streak,1);});
test('hostile fields, invalid amounts and malformed imports fail atomically',()=>{const s=add();for(const value of [{goldPerPoint:-1},{dailyGoldCap:1.5},{goldPerPoint:Infinity}])assert(act(s,'habitSettings',start,null,value).error);assert(act(s,'habitImport',start,null,{tasks:[{title:'okay'},{title:''}]}).error);const x=doAct(s,'habitSave','h1',{link:'javascript:alert(1)'});assert.equal(x.habits.items[0].link,'');});
test('task backup restores definitions without issuing rewards or reusing IDs',()=>{let s=doAct(add(),'habitComplete','h1');s=doAct(s,'habitClear');assert.equal(s.habits.items.length,0);s=doAct(s,'habitRestoreTasks');assert.equal(s.habits.items.length,1);assert.equal(s.gold,270);s=add(s,{title:'Another'});assert.equal(s.habits.items[1].id,'h2');});
test('opening on each weekend day preserves the last scheduled completion',()=>{let s=add(fresh(date('2026-09-04')),{days:[1,2,3,4,5]});s=doAct(s,'habitComplete','h1');for(const d of ['2026-09-05','2026-09-06','2026-09-07']){s=settle(s,date(d));assert.equal(s.habits.items[0].streak,1)}assert.equal(s.habits.grace,0);assert(!s.habits.items[0].done);});
test('quarterly tasks always remain reachable through Reviews',()=>{const s=add(fresh(start),{freq:'quarterly',review:false});assert.equal(s.habits.items[0].review,true);});
