import test from 'node:test';import assert from 'node:assert/strict';import {fresh,act,settle,decode,valid} from '../lib/game.mjs';import {FAMILY} from '../lib/catalog.mjs';
import {ROAM_LOCATIONS,ROAM_EVENTS,ROAM_FAMILY,ROAM_REWARDS,ROAM_FAME,ROAM_RECOVERY_MS,roamingState,roamStamina,roamEncounter,roamCap,roamFamily} from '../lib/roaming.mjs';
const T=new Date('2026-09-09T12:00:00').getTime();
const seq=s=>roamingState(s).seq;
const result=(s,a,value={},now=s.lastAt)=>act(s,a,now,null,{seq:seq(s),...value});
const go=(s,a,value={},now=s.lastAt)=>{const x=result(s,a,value,now);assert.equal(x.error,undefined,x.error);assert.ok(valid(x.state),a);return x.state};
const rollFor=(s,kind)=>{for(let i=0;i<5000;i++){const roll=i/5000;if(roamEncounter(s,roll).kind===kind)return roll}throw Error('no roll for '+kind)};

test('roaming content comes from the original text and joins existing Family members',()=>{assert.equal(ROAM_LOCATIONS.length,11);assert.equal(ROAM_EVENTS.length,44);assert.equal(ROAM_FAMILY.length,10);for(const f of ROAM_FAMILY){assert.ok(FAMILY.some(x=>x.id===f.id),f.id);assert.ok(ROAM_LOCATIONS.some(l=>l.id===f.location),f.id)}for(const e of ROAM_EVENTS)assert.ok(ROAM_LOCATIONS.some(l=>l.id===e.location),e.id);assert.equal(roamFamily('wife_16').bondGoal,35);assert.equal(roamFamily('wife_54').bondGoal,50);const inv=fresh(T).inventory;for(const id of ROAM_REWARDS)assert.ok(Object.hasOwn(inv,id),id)});

test('old saves without roaming decode unchanged and start with a full stamina stock',()=>{const s=fresh(T);assert.equal(s.roaming,undefined);assert.deepEqual(decode(JSON.stringify(s)),s);const st=roamStamina(s);assert.equal(st.stamina,roamCap(s));assert.equal(st.recoverAt,null)});

test('a roam spends stamina, gives Fame, records the encounter and refuses stale requests',()=>{let s=fresh(T);const cap=roamCap(s);s=go(s,'roamGo',{roll:.5});const r=roamingState(s);assert.equal(r.stamina,cap-1);assert.equal(r.recoverAt,T+ROAM_RECOVERY_MS);assert.equal(r.fame,ROAM_FAME);assert.equal(r.travels,1);assert.equal(r.history.length,1);assert.ok(result(s,'roamGo',{roll:.5,seq:0}).error);assert.ok(result(s,'roamGo',{roll:1}).error);assert.deepEqual(decode(JSON.stringify(s)),s)});

test('stamina recovers one point every 30 minutes and stops at the cap',()=>{let s=go(fresh(T),'roamGo',{roll:.1});s=go(s,'roamGo',{roll:.2});const cap=roamCap(s),due=roamingState(s).recoverAt;assert.equal(roamStamina(settle(s,due-1)).stamina,cap-2);assert.equal(roamStamina(settle(s,due)).stamina,cap-1);const full=roamStamina(settle(s,due+ROAM_RECOVERY_MS));assert.equal(full.stamina,cap);assert.equal(full.recoverAt,null)});

test('meeting an uninvited roaming Family member builds bond until they join',()=>{let s=fresh(T);const roll=rollFor(s,'bond'),first=roamEncounter(s,roll),goal=roamFamily(first.target).bondGoal;let now=T,joined=null;for(let i=0;i<400&&!joined;i++){now+=ROAM_RECOVERY_MS*40;s=settle(s,now);const e=roamEncounter(s,rollFor(s,'bond'));const before=roamingState(s).bonds[e.target]||0;const x=result(s,'roamGo',{roll:rollFor(s,'bond')},now);assert.equal(x.error,undefined,x.error);s=x.state;assert.ok(valid(s));const after=roamingState(s);if(s.family[e.target]&&roamingState(s).history.at(-1).kind==='joined'){joined=e.target;assert.equal(after.bonds[e.target],roamFamily(e.target).bondGoal);assert.deepEqual(s.family[e.target],{intimacy:0,blessingPower:10,points:0,skill:0,relationship:1});assert.match(x.message,/joined your family/)}else assert.equal(after.bonds[e.target],before+1)}assert.ok(joined,'a roaming Family member joined');assert.ok(goal>=20);assert.deepEqual(decode(JSON.stringify(s)),s)});

test('meeting an invited Family member raises Intimacy, and Fellow events grant an item',()=>{let s=act(fresh(T),'welcome',T,'wife_3').state;const r1=rollFor(s,'intimacy'),e1=roamEncounter(s,r1),before=s.family[e1.target].intimacy;s=go(s,'roamGo',{roll:r1});assert.equal(s.family[e1.target].intimacy,before+5);const r2=rollFor(s,'event'),e2=roamEncounter(s,r2),count=s.inventory[e2.item];s=go(s,'roamGo',{roll:r2});assert.equal(s.inventory[e2.item],count+1);assert.equal(roamingState(s).history.at(-1).item,e2.item)});

test('quick roaming stops when stamina runs out, and an empty stock refuses',()=>{let s=fresh(T);const cap=roamCap(s);for(let i=0;i<Math.ceil(cap/10);i++){const left=roamStamina(s).stamina;if(!left)break;s=go(s,'roamQuick',{rolls:Array.from({length:10},(_,j)=>((i*10+j)%97)/97)})}assert.equal(roamStamina(s).stamina,0);assert.equal(roamingState(s).travels,cap);assert.match(result(s,'roamGo',{roll:.3}).error,/No Roaming Stamina/);assert.ok(result(s,'roamQuick',{rolls:Array(11).fill(.1)}).error)});

test('habits refill stamina once a day',()=>{let s=fresh(T);s=go(s,'roamQuick',{rolls:Array(8).fill(.4)});assert.match(result(s,'roamRefill').error,/daily habit/);let h=act(s,'habitSave',s.lastAt,null,{title:'Walk',freq:'daily',domain:'health'});assert.ok(!h.error,h.error);s=h.state;h=act(s,'habitComplete',s.lastAt,s.habits.items.at(-1).id);assert.ok(!h.error,h.error);s=h.state;const before=roamStamina(s).stamina;s=go(s,'roamRefill');assert.equal(roamStamina(s).stamina,before+1);assert.match(result(s,'roamRefill').error,/already used/)});

test('mutated roaming saves are rejected',()=>{const s=go(fresh(T),'roamGo',{roll:.6});for(const bad of [{stamina:61},{stamina:null,recoverAt:5},{bonds:{wife_16:36}},{bonds:{wife_3:1}},{history:[{id:0,at:T,kind:'bond',target:'wife_16',location:99}]},{refillDay:'yesterday'},{policyVersion:2}]){const m={...s,roaming:{...s.roaming,...bad}};assert.equal(valid(m),false,JSON.stringify(bad));assert.throws(()=>decode(JSON.stringify(m)),JSON.stringify(bad))}});
