import test from 'node:test';import assert from 'node:assert/strict';import {fresh,act} from '../lib/game.mjs';
import {ROAM_FAMILY,roamEncounter,roamingState} from '../lib/roaming.mjs';
import {ROAM_SCENES,roamScenesFor,roamStoryStep,roamStoryFor,roamUnlockedStories,roamAfterStory} from '../lib/roaming-story.mjs';
const T=new Date('2026-09-09T12:00:00').getTime();

test('every roaming Family member has original numbered encounter stories',()=>{assert.equal(ROAM_SCENES.length,91);for(const f of ROAM_FAMILY){const scenes=roamScenesFor(f.id);assert.ok(scenes.filter(s=>s.step!=='After').length>=4,f.id);for(const s of scenes){assert.ok(s.lines.length>=1,s.id);for(const l of s.lines){assert.equal(typeof l.text,'string');assert.match(l.sourceKey,/^Dialog:context:Wife\d+_FindDialogue\w+/)}}}assert.equal(roamScenesFor('wife_18')[0].lines[0].text.startsWith('Please pay, lady'),true)});

test('meetings play in order across the bond goal, ending on the joining meeting',()=>{for(const f of ROAM_FAMILY){const pre=roamScenesFor(f.id).filter(s=>s.step!=='After');assert.equal(roamStoryStep(f.id,1),pre[0],f.id);assert.equal(roamStoryStep(f.id,f.bondGoal),pre.at(-1),f.id);let last=-1;for(let b=1;b<=f.bondGoal;b++){const i=pre.indexOf(roamStoryStep(f.id,b));assert.ok(i>=last&&i<=last+1,`${f.id} bond ${b}`);last=i}assert.equal(last,pre.length-1)}assert.equal(roamStoryStep('wife_18',0),null);assert.equal(roamStoryStep('wife_3',1),null)});

test('roaming records point at the story they played, and reached stories unlock',()=>{let s=fresh(T);assert.deepEqual(roamUnlockedStories(s,'wife_18'),[]);let roll=0;for(let i=0;i<5000;i++){if(roamEncounter(s,i/5000).kind==='bond'){roll=i/5000;break}}const e=roamEncounter(s,roll);s=act(s,'roamGo',T,null,{seq:0,roll}).state;const h=roamingState(s).history.at(-1);assert.equal(h.kind,'bond');assert.equal(roamStoryFor(h),roamScenesFor(e.target)[0]);assert.deepEqual(roamUnlockedStories(s,e.target),[roamScenesFor(e.target)[0]]);assert.equal(roamStoryFor({kind:'event',target:'N101'}),null);const w=act(fresh(T),'welcome',T,'wife_18').state,all=roamUnlockedStories(w,'wife_18');assert.equal(all.length,roamScenesFor('wife_18').length);assert.equal(all.at(-1),roamAfterStory('wife_18'));assert.equal(roamStoryFor({kind:'intimacy',target:'wife_18',amount:5}),roamAfterStory('wife_18'))});
