import test from 'node:test';import assert from 'node:assert/strict';import {fresh,act,decode,settle,totalRate,valid} from '../lib/game.mjs';import {MILESTONES} from '../lib/progression.mjs';
function enrolled(){let s=act(fresh(0),'welcome',0).state;return act(s,'enroll',0,'wife_2','curious').state}
function educate(s){for(let i=0;i<6;i++)s=act(s,'educate',0,1,'class').state;return s}
test('v3 migration preserves family, rank, inventory and business progress',()=>{const old=act(fresh(0),'welcome',0).state;old.version=3;old.inventory=Object.fromEntries(Object.entries(old.inventory).filter(([id])=>id.startsWith('gift')));delete old.school;delete old.fellowXP;delete old.family.wife_2.relationship;old.family.wife_2.intimacy=41;old.family.wife_2.points=123;const s=decode(JSON.stringify(old));assert.equal(s.version,10);assert.equal(s.family.wife_2.relationship,1);assert.equal(s.family.wife_2.intimacy,41);assert.equal(s.family.wife_2.points,123);for(const id of Object.keys(old.inventory))assert.equal(s.inventory[id],old.inventory[id]);assert.equal(s.school.points,6);assert(valid(s))});
test('complete education consumes six points and grants rank-based Fellow EXP',()=>{const s=educate(enrolled());assert.equal(s.school.points,0);assert.equal(s.school.pupils[0].progress,6);assert.equal(s.fellowXP,310);assert(act(s,'educate',0,1,'class').error);assert.deepEqual(decode(JSON.stringify(s)),s)});
test('graduation rewards exactly once and starts income after graduation',()=>{let s=educate(enrolled());s=act(s,'graduate',1000,1).state;assert.equal(s.pending,32);assert.equal(s.school.income,1.6);assert.equal(s.school.graduates,1);assert.equal(s.inventory.gift1,6);assert.equal(s.school.pupils.length,0);assert.equal(totalRate(s),3.6);assert.equal(settle(s,2000).pending,35.6);assert(act(s,'graduate',1000,1).error);assert.deepEqual(decode(JSON.stringify(s)),s)});
test('Education recovery is one per five minutes and rollback cannot duplicate it',()=>{let s=educate(enrolled());s=settle(s,150000);assert.equal(s.school.points,.5);s=settle(s,300000);assert.equal(s.school.points,1);assert.equal(settle(s,1).school.points,1);assert.equal(settle(s,300000).school.points,1);assert.equal(settle(s,9000000).school.points,6)});
test('caretaker relationships snapshot intellect; intimacy changes affect ungraduated pupils only',()=>{let s=enrolled();s.family.wife_2.intimacy=20;s=act(s,'relationship',0,'wife_2').state;assert.equal(s.family.wife_2.relationship,2);assert.equal(s.family.wife_2.intimacy,20);assert.equal(s.school.pupils[0].intellect,10);s=act(s,'enroll',0,'wife_2','creative').state;assert.equal(s.school.pupils[1].intellect,20);s=educate(s);s=act(s,'graduate',0,1).state;const income=s.school.income;s=act(s,'gift',0,'wife_2','gift1').state;assert.equal(s.school.income,income)});
test('education methods enforce rank and high-rank progress remains valid',()=>{let s=enrolled();assert(act(s,'educate',0,1,'tutorial').error);s.claims=MILESTONES.map(m=>m.id);s=act(s,'educate',0,1,'tutorial').state;s=act(s,'educate',0,1,'tutorial').state;assert.equal(s.school.pupils[0].education,36);assert.equal(s.fellowXP,370);assert(valid(s))});
test('intake capacity and unmet prerequisites cannot grant pupils or graduation rewards',()=>{assert(act(fresh(0),'enroll',0,'wife_2','curious').error);let s=enrolled();assert(act(s,'graduate',0,1).error);assert(act(s,'enroll',0,'wife_2','unknown').error);s=act(s,'enroll',0,'wife_2','curious').state;s=act(s,'enroll',0,'wife_2','curious').state;assert(act(s,'enroll',0,'wife_2','curious').error);assert.equal(s.school.nextId,4)});
test('malformed or duplicate pupil data is rejected before loading',()=>{const s=enrolled();for(const invalid of [{...s,school:{...s.school,points:-1}},{...s,school:{...s.school,pupils:[s.school.pupils[0],s.school.pupils[0]]}},{...s,school:{...s.school,pupils:[{...s.school.pupils[0],caretaker:'unknown'}]}},{...s,fellowXP:-1}])assert.throws(()=>decode(JSON.stringify(invalid)))});
