import test from 'node:test';import assert from 'node:assert/strict';import {fresh,act,valid,decode,totalRate} from '../lib/game.mjs';import {specialEligible,specialAptitude} from '../lib/special-blessings.mjs';import {bondedPower} from '../lib/adventure.mjs';import {createPersistence} from '../lib/persistence.mjs';import data from '../lib/special-blessing-data.json' with {type:'json'};import {stockAll} from './gear-fixtures.mjs';
const run=(s,a,t='wife_1',v=null)=>{const r=act(s,a,s.lastAt,t,v);assert.ok(!r.error,r.error);assert.ok(valid(r.state),a);return r.state};
const ready=(s=run(run(fresh(1000),'welcome'),'activateOriginalProgression'),id='wife_1')=>{for(const k of ['flatBlessing','advancedBlessing'])while((s.family[id][k]||0)<700){s=run(s,'specialBlessingSupply',id);s=run(s,'trainBlessingsMax',id,k);}return s;};
test('requires both700, explicit activation, separate points and derived coefficient with no paid-Aptitude rewrite',()=>{let s=run(run(fresh(1000),'welcome'),'activateOriginalProgression');assert.equal(specialEligible(s,'wife_1'),false);assert.ok(act(s,'activateSpecialBlessing',1000,'wife_1').error);s=ready(s);assert.equal(s.family.wife_1.specialBlessing,undefined);assert.equal(specialAptitude(s,'hero_1'),0);const before=structuredClone(s);s=run(s,'activateSpecialBlessing');assert.equal(specialAptitude(s,'hero_1'),2);assert.equal(specialAptitude(s,'hero_15'),0);assert.deepEqual(s.fellows,before.fellows);assert.equal(s.family.wife_1.points,before.family.wife_1.points);assert.ok(act(s,'activateSpecialBlessing',1000,'wife_1').error);assert.deepEqual(decode(JSON.stringify(s)),s);});
test('all699 exact costs, max wallet batches,700total1400 not cumulative, no gated recipients',()=>{let s=run(ready(),'activateSpecialBlessing'),spent=0;while(s.family.wife_1.specialBlessing.level<700){s=run(s,'specialBlessingSupply');const points=s.family.wife_1.points;s=run(s,'trainSpecialBlessing');spent+=points-s.family.wife_1.points;}assert.equal(spent,4767865100);assert.equal(specialAptitude(s,'hero_1'),1400);assert.equal(s.family.wife_1.specialBlessing.level,700);assert.deepEqual(s.family.wife_1.specialBlessing.recipients,data.recipients.wife_1);assert.ok(act(s,'trainSpecialBlessing',1000,'wife_1').error);assert.deepEqual(decode(JSON.stringify(s)),s);});
test('paid mutation settles old rate, retains frozen encounters and receipts, fails atomically and rejects altered cost',()=>{let s=run(ready(),'activateSpecialBlessing');s=run(s,'specialBlessingSupply');s=run(s,'northStart',null,{seq:0});s=run(s,'tradeBegin','veteran',{seq:0,team:['hero_15']});const rate=totalRate(s),r=act(s,'trainSpecialBlessing',2000,'wife_1',1);assert.ok(!r.error);assert.equal(r.state.pending,s.pending+rate);for(const k of ['fellows','northern','tradingPost'])assert.deepEqual(r.state[k],s[k]);assert.deepEqual(r.state.family.wife_1.apkBlessings,s.family.wife_1.apkBlessings);assert.equal(r.state.family.wife_1.specialBlessing.level,2);assert.equal(r.state.family.wife_1.points,s.family.wife_1.points-10000);
let raw=JSON.stringify(s),fail=false;const p=createPersistence(()=>({getItem:()=>raw,setItem:(k,v)=>{if(fail)throw Error('quota');raw=v}}));p.load(1000);fail=true;assert.throws(()=>p.commit(r.state));assert.deepEqual(p.current,s);fail=false;p.load(1000);p.commit(run(p.current,'trainSpecialBlessing','wife_1',1));const bad=structuredClone(p.current);bad.family.wife_1.specialBlessing.receipts[0].cost++;assert.equal(valid(bad),false);assert.deepEqual(decode(raw),p.current);});
import {ARTIFACT_SUPPORTS} from '../lib/artifact-echo.mjs';
test('overlapping Family coefficient gains add once with equipment Familiar and Stella, preserving owned state',()=>{const ids=Object.keys(data.recipients).filter(id=>data.recipients[id].includes('hero_190')).slice(0,2);assert.equal(ids.length,2);let s=run(fresh(1000),'recruit','hero_190');for(const id of ids)s=run(s,'welcome',id);s=run(s,'activateOriginalProgression');const a=ARTIFACT_SUPPORTS[0];if(!s.family[a.family])s=run(s,'welcome',a.family);s=stockAll(s);s=run(s,'equip','hero_190',a.item);s=run(s,'enableArtifactEcho','hero_190');s=run(s,'adoptFamiliar','Pet_4151');s=run(s,'trainFamiliar','Pet_4151',10);s=run(s,'bindFamiliar','Pet_4151','hero_190');s=run(s,'stellaActivate','hero_190',{seq:0});s=run(s,'stellaSupply','hero_190',{seq:s.stella.seq});s=run(s,'stellaUpgrade','hero_190',{seq:s.stella.seq,count:1});for(const id of ids){s=ready(s,id);const before=structuredClone(s),power=bondedPower(s,'hero_190');s=run(s,'activateSpecialBlessing',id);assert.ok(bondedPower(s,'hero_190')>power);for(const key of ['fellows','familiars','stella','artifacts','originalProgression'])assert.deepEqual(s[key],before[key]);}assert.equal(specialAptitude(s,'hero_190'),4);assert.deepEqual(decode(JSON.stringify(s)),s);});
