import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {fresh,act,valid,decode,totalRate} from '../lib/game.mjs';import {BUSINESSES,enterpriseBreakdown} from '../lib/businesses.mjs';import {staffPrice,staffCoefficient,staffingStatus,staffingRule,staffingPlan,STAFFING} from '../lib/staffing.mjs';import {HIRE_CARDS} from '../lib/hire-cards.mjs';import {createPersistence} from '../lib/persistence.mjs';
import {funded,costOf} from './gear-fixtures.mjs';
const run=(s,a,t=null,v=null)=>{const r=act(s,a,s.lastAt,t,v);assert.ok(!r.error,r.error);assert.ok(valid(r.state),a);return r.state};
const begin=(id='Building_101',n=0)=>{let s=run(funded(fresh(1000),costOf(id)),'openEnterprise',id);s.enterprises[id].employees=n;s=run(s,'activateOriginalProgression');return run(s,'startPaidStaffing',id)};
const evidence=JSON.parse(readFileSync(new URL('../lib/staffing-independent-data.json',import.meta.url)));
const raw=JSON.parse(readFileSync(new URL('../lib/staffing-data.json',import.meta.url)));
test('independent Decimal90 source fixtures: actual batch prices differ from summed singles',()=>{for(const x of evidence.quotes){assert.equal(staffPrice('Building_101',x.staff,1),x.one);assert.equal(staffPrice('Building_101',x.staff,10),x.ten);let singles=0;for(let j=0;j<10;j++)singles+=staffPrice('Building_101',x.staff+j,1);assert.equal(singles,x.tenSingles);assert.notEqual(singles,x.ten);}});
test('budget-max and quote boundaries across all17 businesses, source bands and every quality limit',()=>{const points=new Set([0,1,4999,5000,25999,26000]);for(const b of raw.bands)for(const n of [b.staffCount[0]-1,b.staffCount[0],b.staffCount[1],b.staffCount[1]+1])if(n>=0&&n<=26000)points.add(n);for(let q=1;q<=26;q++)for(const n of [q*1000-1,q*1000])points.add(n);
 for(const id of Object.keys(STAFFING))for(const n of points){const quality=Math.min(26,Math.floor(n/1000)+1),cap=staffingRule(id,quality).cap;const s={gold:0,enterprises:{[id]:{employees:n,apkStaffing:{baselineEmployees:n,baselineQuality:quality,events:[]}}}};const k=Math.min(10,cap-n),price=staffPrice(id,n,k);if(!k){assert.deepEqual(staffingPlan(s,id,'max'),{count:0,cost:0});continue;}if(!Number.isSafeInteger(price)){s.gold=1e12;const plan=staffingPlan(s,id,'max');assert.ok(plan.cost<=s.gold);assert.ok(plan.count<k);continue;}for(const budget of [Math.max(0,price-1),price,price+1]){s.gold=budget;const plan=staffingPlan(s,id,'max');assert.ok(plan.cost<=budget);assert.equal(plan.cost,staffPrice(id,n,plan.count));assert.ok(plan.count<=cap-n);if(plan.count<cap-n)assert.ok(staffPrice(id,n,plan.count+1)>budget);if(budget===price)assert.equal(plan.count,k);}}
});
test('all17 enrolled legacy businesses keep income and staff, quality materials current row and terminal26',()=>{for(const d of BUSINESSES){let s=begin(d.id,5000);const old=enterpriseBreakdown(s,d.id).total;assert.equal(staffingStatus(d.id,s.enterprises[d.id]).quality,5);assert.equal(staffingStatus(d.id,s.enterprises[d.id]).bonus,0);assert.ok(act(s,'upgradeStaffQuality',1000,d.id).error);s={...s,staffingMaterials:{claims:1000,stock:100000}};assert.ok(valid(s));let spent=0;for(let q=5;q<26;q++){const prior=staffingRule(d.id,q),before=enterpriseBreakdown(s,d.id);s=run(s,'upgradeStaffQuality',d.id);spent+=prior.cost;const st=staffingStatus(d.id,s.enterprises[d.id]);assert.equal(st.cap,(q+1)*1000);assert.equal(st.spent,spent);assert.equal(s.staffingMaterials.stock,100000-spent);assert.equal(st.bonus,(staffingRule(d.id,q+1).yieldRise-staffingRule(d.id,5).yieldRise)/10000);assert.ok(enterpriseBreakdown(s,d.id).total>before.total);}assert.ok(enterpriseBreakdown(s,d.id).total>old);assert.ok(act(s,'upgradeStaffQuality',1000,d.id).error);assert.deepEqual(decode(JSON.stringify(s)),s);}});
test('actual paid budget purchase, exact clipping and gold refusal preserve other progress',()=>{let s=begin();assert.deepEqual(staffingPlan(s,'Building_101','max'),{count:10,cost:247});s=run(s,'paidStaffHire','Building_101','max');assert.equal(s.gold,3);assert.equal(s.enterprises.Building_101.employees,10);assert.ok(act(s,'paidStaffHire',1000,'Building_101',1).error);assert.ok(act(s,'paidStaffHire',1000,'Building_101','max').error);s=begin('Building_101',999);s.gold=1e12;assert.equal(staffingPlan(s,'Building_101',10).count,1);s=run(s,'paidStaffHire','Building_101',10);assert.equal(s.enterprises.Building_101.employees,1000);assert.ok(act(s,'paidStaffHire',1000,'Building_101',1).error);s=run(s,'claimStaffingMaterials');s=run(s,'upgradeStaffQuality','Building_101');s=run(s,'paidStaffHire','Building_101',10);assert.equal(s.enterprises.Building_101.employees,1010);assert.deepEqual(decode(JSON.stringify(s)),s);});
test('free and Hire Card coverage never charges, reduces cap or grants quality income',()=>{let s=begin('Building_901',999);s=run(s,'claimStaffingMaterials');s=run(s,'upgradeStaffQuality','Building_901');const bonus=staffingStatus('Building_901',s.enterprises.Building_901).bonus;s=run(s,'hireEmployees','Building_901',800);s=run(s,'hireEmployees','Building_901',800);assert.equal(staffingStatus('Building_901',s.enterprises.Building_901).quality,3);assert.equal(staffingStatus('Building_901',s.enterprises.Building_901).bonus,bonus);s=run(s,'hireEmployees','Building_901',5000);assert.equal(s.enterprises.Building_901.employees,5000);assert.equal(staffingStatus('Building_901',s.enterprises.Building_901).quality,5);const card=HIRE_CARDS[0];s={...s,hireCards:{...s.hireCards,[card.id]:10}};assert.ok(act(s,'useHireCards',1000,card.id,{count:1,rolls:[0]}).error);while(s.staffingMaterials.stock<staffingRule('Building_901',5).cost)s=run(s,'claimStaffingMaterials');s=run(s,'upgradeStaffQuality','Building_901');s.gold=1e12;assert.ok(act(s,'paidStaffHire',1000,'Building_901',1).error);assert.deepEqual(decode(JSON.stringify(s)),s);s=begin('Building_101',5000);s=run(s,'claimStaffingMaterials');s=run(s,'upgradeStaffQuality','Building_101');s.gold=1e12;s=run(s,'paidStaffHire','Building_101',1);assert.equal(s.enterprises.Building_101.employees,5001);assert.ok(act(s,'hireEmployees',1000,'Building_101',5000).error);assert.deepEqual(decode(JSON.stringify(s)),s);
 s=begin('Building_101',999);s={...s,hireCards:{...s.hireCards,[card.id]:10}};s=run(s,'useHireCards',card.id,{count:1,rolls:[0]});s=run(s,'useHireCards',card.id,{count:1,rolls:[0]});assert.ok(s.enterprises.Building_101.employees>1000);assert.equal(staffingStatus('Building_101',s.enterprises.Building_101).quality,2);assert.equal(staffingStatus('Building_101',s.enterprises.Building_101).bonus,0);});
test('old income settles before quality, encounters frozen, failed-write reload and tamper refusal',()=>{let s=begin('Building_101',50);s=run(s,'claimStaffingMaterials');s=run(s,'northStart',null,{seq:0});s=run(s,'tradeBegin','veteran',{seq:0,team:['hero_15']});const rate=totalRate(s),r=act(s,'upgradeStaffQuality',2000,'Building_101');assert.ok(!r.error);assert.equal(r.state.pending,s.pending+rate);assert.deepEqual(r.state.northern,s.northern);assert.deepEqual(r.state.tradingPost,s.tradingPost);let raw=JSON.stringify(s),fail=false;const p=createPersistence(()=>({getItem:()=>raw,setItem:(k,v)=>{if(fail)throw Error('quota');raw=v}}));p.load(1000);fail=true;assert.throws(()=>p.commit(r.state));assert.deepEqual(p.current,s);fail=false;p.load(1000);p.commit(run(p.current,'upgradeStaffQuality','Building_101'));assert.deepEqual(decode(raw),p.current);for(const edit of [x=>x.enterprises.Building_101.employees++,x=>x.enterprises.Building_101.apkStaffing.events[0][2]++,x=>x.staffingMaterials.stock++,x=>x.enterprises.Building_101.apkStaffing.baselineQuality=6,x=>x.enterprises.Bad=x.enterprises.Building_101]){const bad=structuredClone(p.current);edit(bad);assert.equal(valid(bad),false);assert.throws(()=>decode(JSON.stringify(bad)));}});
