import test from 'node:test';import assert from 'node:assert/strict';import {fresh,act,valid,decode,settle,totalRate} from '../lib/game.mjs';import {newFellow,bondedPower} from '../lib/adventure.mjs';import {STELLA_PROFILES,stellaState,stellaEntry,stellaPlan,stellaBonus} from '../lib/stella.mjs';import {createPersistence} from '../lib/persistence.mjs';import {BUSINESSES} from '../lib/businesses.mjs';
const result=(s,a,id='hero_54',count=1)=>act(s,a,s.lastAt,id,{seq:stellaState(s).seq,count}),go=(s,a,id='hero_54',count=1)=>{const r=result(s,a,id,count);assert.equal(r.error,undefined);assert.ok(valid(r.state),a);return r.state;};
const setup=()=>{const s=fresh(1000);for(const id of ['hero_52','hero_54','hero_56','hero_190','hero_102'])s.fellows[id]=newFellow();return s;};
test('all140 source upgrade rows use exact owner fragments and cumulative effects, with full cap',()=>{for(const p of STELLA_PROFILES){let s=setup();s=go(s,'stellaActivate',p.id);for(let i=0;i<6;i++)s=go(s,'stellaSupply',p.id);const stock=s.stella.stock[p.itemId];let spent=0;for(const row of p.levels){s=go(s,'stellaUpgrade',p.id);spent+=row.cost;assert.deepEqual({level:stellaEntry(s,p.id).level,flat:stellaEntry(s,p.id).flat,percent:stellaEntry(s,p.id).percent},{level:row.level,flat:row.flat,percent:row.percent});}assert.equal(s.stella.stock[p.itemId],stock-spent);assert.equal(s.stella.history.length,p.levels.length+1);assert.ok(result(s,'stellaUpgrade',p.id).error);assert.deepEqual(decode(JSON.stringify(s)).stella,s.stella);}});
test('typed effect targets correct current and future Fellows, never increments base aptitude or levels',()=>{let s=setup();const original=structuredClone(s.fellows),unaffected=bondedPower(s,'hero_15');s=go(s,'stellaActivate');s=go(s,'stellaSupply');s=go(s,'stellaUpgrade');assert.equal(bondedPower(s,'hero_54'),Math.floor((100+500000)*1.05));assert.equal(bondedPower(s,'hero_15'),unaffected);assert.deepEqual(s.fellows,original);s=go(s,'stellaUpgrade');assert.equal(stellaEntry(s,'hero_54').flat,1000000);assert.equal(stellaBonus(s,'hero_54').percent,8);assert.equal(bondedPower(s,'hero_54'),Math.floor((100+1000000)*1.08));delete s.fellows.hero_102;s=go(s,'stellaActivate','hero_56');s.fellows.hero_102=newFellow(2);assert.equal(stellaBonus(s,'hero_102').percent,2);});
test('eligibility, activation, cross-fragment spending, stale and batch affordability boundaries',()=>{let s=fresh(1000);assert.ok(result(s,'stellaActivate').error);s=setup();assert.ok(result(s,'stellaActivate','hero_102').error);assert.ok(result(s,'stellaUpgrade').error);s=go(s,'stellaActivate');assert.ok(result(s,'stellaActivate').error);assert.ok(result(s,'stellaUpgrade').error);s=go(s,'stellaSupply','hero_52');assert.ok(result(s,'stellaUpgrade').error);s=go(s,'stellaSupply');const plan=stellaPlan(s,'hero_54',5);s=go(s,'stellaUpgrade','hero_54',5);assert.equal(stellaEntry(s,'hero_54').level,5);assert.equal(s.stella.stock.Item_Owner_HeroPiece_54,1000-plan.cost);const seq=s.stella.seq;s=go(s,'stellaUpgrade','hero_54','max');assert.ok(act(s,'stellaUpgrade',s.lastAt,'hero_54',{seq}).error);assert.ok(stellaPlan(s,'hero_54',1).rows.length===0);});
test('failed activation/upgrade persists fragments and exact retry once; receipts survive offline',()=>{let s=setup();s=go(s,'stellaSupply');let raw=JSON.stringify(s),fail=false;const p=createPersistence(()=>({getItem:()=>raw,setItem:(_,v)=>{if(fail)throw Error('quota');raw=v}}));p.load(1000);fail=true;assert.throws(()=>p.commit(go(p.current,'stellaActivate')));assert.equal(stellaEntry(p.current,'hero_54'),null);fail=false;p.load(1000);p.commit(go(p.current,'stellaActivate'));const prior=structuredClone(p.current.stella);fail=true;assert.throws(()=>p.commit(go(p.current,'stellaUpgrade','hero_54',5)));assert.deepEqual(p.current.stella,prior);fail=false;p.load(1000);p.commit(go(p.current,'stellaUpgrade','hero_54',5));const final=structuredClone(p.current.stella);p.load(86400000);assert.deepEqual(p.current.stella,final);});
test('pending Trading/Northern snapshots stay fixed and old-rate income settles before Stella',()=>{let s=setup();s=act(s,'openEnterprise',s.lastAt,BUSINESSES[0].id).state;assert.ok(s.enterprises[BUSINESSES[0].id]);s=act(s,'northStart',s.lastAt,null,{seq:0}).state;s=act(s,'tradeBegin',s.lastAt,'learner',{seq:0,team:['hero_54']}).state;const north=structuredClone(s.northern.run),trade=structuredClone(s.tradingPost.run);s=go(s,'stellaActivate');s=go(s,'stellaSupply');const oldRate=totalRate(s),expected=settle(s,s.lastAt+1000);s=act(s,'stellaUpgrade',s.lastAt+1000,'hero_54',{seq:s.stella.seq}).state;assert.equal(s.pending,expected.pending);assert.ok(totalRate(s)>oldRate);assert.deepEqual(s.northern.run,north);assert.deepEqual(s.tradingPost.run,trade);assert.ok(valid(s));});
test('malformed fragment conservation, owner, sequential level and scope rejected; old receipt values not repriced',()=>{let s=go(go(setup(),'stellaActivate'),'stellaSupply');s=go(s,'stellaUpgrade');for(const f of [t=>t.stock.Item_Owner_HeroPiece_54++,t=>t.history[1].owner='hero_102',t=>t.history[1].level=5,t=>t.history[1].type='Diligent']){const bad=structuredClone(s);f(bad.stella);assert.equal(valid(bad),false);assert.throws(()=>decode(JSON.stringify(bad)));}s.stella.history[1].paid=21;s.stella.stock.Item_Owner_HeroPiece_54--;s.stella.history[1].flat=499999;assert.deepEqual(decode(JSON.stringify(s)).stella,s.stella);});
test('authored activation is limited and versioned; unmarked v86 receipts keep exact saved benefit',async()=>{
 const {stellaActivation,STELLA_ACTIVATION_POLICY}=await import('../lib/stella.mjs');assert.equal(stellaActivation('hero_102'),null);assert.equal(stellaActivation('hero_54').percent,2);
 let s=go(setup(),'stellaActivate');assert.equal(s.stella.history[0].activationPolicy,STELLA_ACTIVATION_POLICY);delete s.stella.history[0].activationPolicy;s.stella.history[0].percent=3;const old=structuredClone(s.stella);assert.ok(valid(s));assert.deepEqual(decode(JSON.stringify(s)).stella,old);assert.equal(bondedPower(s,'hero_54'),103);
 const bad=structuredClone(s);bad.stella.history[0].activationPolicy='unverified-other-policy';assert.equal(valid(bad),false);
});
test('all159 owned Fellows receive each latest typed contribution exactly once',async()=>{
 const {FELLOWS}=await import('../lib/catalog.mjs');let s=fresh(1000);for(const f of FELLOWS)s.fellows[f.id]=newFellow();const base=structuredClone(s);for(const p of STELLA_PROFILES){s=go(s,'stellaActivate',p.id);s=go(s,'stellaSupply',p.id);s=go(s,'stellaUpgrade',p.id,5);}
 assert.equal(Object.keys(s.fellows).length,154);for(const f of FELLOWS){const owner=STELLA_PROFILES.find(p=>p.id===f.id),typed=STELLA_PROFILES.filter(p=>p.type===f.type),flat=owner?2500000:0,percent=typed.length*17;assert.equal(bondedPower(s,f.id),Math.floor((bondedPower(base,f.id)+flat)*(1+percent/100)),f.id);}
});
test('Elise has separate zero activation, 1500 paid total, cap20 and mixed historical owners',()=>{
 let s=setup();s=go(s,'stellaActivate','hero_54');delete s.stella.history[0].activationPolicy;s.stella.history[0].percent=3;const legacy=structuredClone(s.stella.history);
 s=go(s,'stellaActivate','hero_190');assert.equal(stellaEntry(s,'hero_190').activationPolicy,'private-elise-stella-activation-v1');assert.equal(stellaEntry(s,'hero_190').percent,0);assert.equal(stellaBonus(s,'hero_190').percent,3);
 for(let i=0;i<2;i++)s=go(s,'stellaSupply','hero_190');s=go(s,'stellaUpgrade','hero_190','max');assert.equal(stellaEntry(s,'hero_190').level,20);assert.equal(s.stella.stock.Item_Owner_HeroPiece_190,500);assert.equal(stellaEntry(s,'hero_190').flat,15300000);assert.equal(stellaBonus(s,'hero_190').percent,65);assert.deepEqual(s.stella.history.slice(0,1),legacy);assert.ok(result(s,'stellaUpgrade','hero_190').error);
 const bad=structuredClone(s);bad.stella.history.at(-1).level=21;assert.equal(valid(bad),false);assert.deepEqual(decode(JSON.stringify(s)).stella,s.stella);
});
test('Elise failed write, old-rate settlement and pending encounters preserve prior values',()=>{
 let s=setup();s=act(s,'openEnterprise',s.lastAt,BUSINESSES[0].id).state;s=act(s,'northStart',s.lastAt,null,{seq:0}).state;s=act(s,'tradeBegin',s.lastAt,'learner',{seq:0,team:['hero_190']}).state;s=go(s,'stellaActivate','hero_190');s=go(s,'stellaSupply','hero_190');let raw=JSON.stringify(s),fail=false;const persistence=createPersistence(()=>({getItem:()=>raw,setItem:(_,v)=>{if(fail)throw Error('quota');raw=v}}));persistence.load(s.lastAt);const old=structuredClone(persistence.current),expected=settle(old,old.lastAt+1000),rate=totalRate(old),candidate=act(old,'stellaUpgrade',old.lastAt+1000,'hero_190',{seq:old.stella.seq,count:5}).state;
 assert.equal(candidate.pending,expected.pending);assert.ok(totalRate(candidate)>rate);assert.deepEqual(candidate.northern.run,old.northern.run);assert.deepEqual(candidate.tradingPost.run,old.tradingPost.run);fail=true;assert.throws(()=>persistence.commit(candidate));assert.deepEqual(persistence.current,old);assert.equal(raw,JSON.stringify(old));fail=false;persistence.load(old.lastAt);persistence.commit(candidate);assert.deepEqual(decode(raw).stella,candidate.stella);
});
test('all four full chains coexist with144 receipts and distinct20/40 caps',()=>{let s=setup();for(const p of STELLA_PROFILES){s=go(s,'stellaActivate',p.id);for(let i=0;i<5;i++)s=go(s,'stellaSupply',p.id);s=go(s,'stellaUpgrade',p.id,'max');assert.equal(stellaEntry(s,p.id).level,p.id==='hero_190'?20:40);}assert.equal(s.stella.history.length,144);assert.deepEqual(decode(JSON.stringify(s)).stella,s.stella);});
