import {FELLOWS} from '../lib/catalog.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,decode,act,totalRate,settle,valid} from '../lib/game.mjs';
test('v1 migration preserves gold, level, uncollected earnings and elapsed-time basis',()=>{const old={version:1,gold:9876,level:14,pending:123.5,lastAt:1000,earned:333,upgrades:13};const s=decode(JSON.stringify(old));assert.equal(s.version,10);assert.equal(s.gold,9876);assert.equal(s.fellows.hero_15.level,14);assert.equal(s.pending,123.5);assert.equal(s.lastAt,1000);assert.equal(totalRate(s),21.5);assert.equal(settle(s,2000).pending,145);assert.deepEqual(decode(JSON.stringify(s)),s)});
test('free recruitment guarantees new ownership and ends without duplicates',()=>{let s=fresh(0);for(let i=1;i<FELLOWS.length;i++)s=act(s,'recruit',0).state;assert.equal(Object.keys(s.fellows).length,FELLOWS.length);assert.equal(s.gold,250);assert(act(s,'recruit',0).error);assert.equal(totalRate(s),2)});
test('unlock, assign, improve, persist and move a Fellow without double earnings',()=>{let s={...fresh(0),gold:10000};s=act(s,'recruit',0).state;s=act(s,'unlock',0,'inn').state;assert.equal(s.gold,9600);assert.equal(totalRate(s),2);s=act(s,'assign',0,'inn','hero_1').state;assert.equal(totalRate(s),4);s=act(s,'buildingUpgrade',0,'inn').state;assert.equal(totalRate(s),4.4);s=decode(JSON.stringify(s));s=act(s,'assign',1000,'fish','hero_1').state;assert.equal(s.pending,34.4);assert.equal(s.buildings.inn.fellow,null);assert.equal(s.buildings.fish.fellow,'hero_1');assert.equal(totalRate(s),2);assert(valid(s))});
test('invalid ownership, duplicate assignments and bad building levels rejected',()=>{const s=fresh(0);assert(act(s,'assign',0,'fish','hero_1').error);assert(!valid({...s,buildings:{fish:{level:1,fellow:'hero_15'},inn:{level:1,fellow:'hero_15'}}}));assert(!valid({...s,buildings:{fish:{level:11,fellow:'hero_15'}}}));assert(!valid({...s,fellows:{hero_15:{level:1},fake:{level:1}}}))});
test('locked and unaffordable actions cannot consume or grant resources',()=>{const s=fresh(0);assert(act(s,'unlock',0,'inn').error);assert(act(s,'buildingUpgrade',0,'inn').error);assert(act(s,'assign',0,'inn','hero_15').error);assert.equal(act(s,'unlock',0,'inn').state.gold,250)});
test('old source state is not mutated by actions',()=>{const s=fresh(0),copy=JSON.stringify(s);act(s,'upgrade',0);act(s,'recruit',0);act(s,'assign',0,'fish',null);assert.equal(JSON.stringify(s),copy)});
