import OpeningPanel from './opening-panel';
import EncounterAdvice from './encounter-advice';
import FrontierPanel from './frontier-panel';
import FellowChooser from './fellow-chooser';
import PanelPages from './panel-pages';
import {useState} from 'react';import {Button} from '@/components/ui/button';import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';import {FELLOWS} from '@/lib/catalog.mjs';import {STAGES,teamPower,bondedPower} from '@/lib/adventure.mjs';
export default function AdventurePanel({game,action,locked,onNavigate}:any){const [patrol,setPatrol]=useState(1),next=STAGES[game.adventure.cleared],power=teamPower(game),chosen=Math.min(patrol,Math.max(1,game.adventure.cleared)),last=game.adventure.lastBattle;return <section className="adventure-panel"><PanelPages labels={['Opening','Sandbox']}><OpeningPanel game={game} action={action} locked={locked} onNavigate={onNavigate}/><PanelPages labels={['Party','Stages','Patrol','Frontier']}><><FellowChooser game={game} locked={locked} selected={game.adventure.party} onChoose={(id:string)=>action('party',id)} status={(id:string)=>(game.adventure.party.includes(id)?'In party · ':'Add · ')+bondedPower(game,id).toLocaleString()+' Power'}/><p className="management-hint">Choose 1–3 Fellows. Party membership does not remove business assignments. Encounters currently resolve by comparing party Power with the stage requirement.</p></><><div className="chapter-track">{[1,2,3,4,5].map(c=><div key={c}><strong>Chapter {c}</strong><span>{Math.max(0,Math.min(6,game.adventure.cleared-(c-1)*6))}/6</span></div>)}</div>
 {next?<article className="school-card"><small>{next.boss?'CHAPTER BOSS':'NEXT STAGE'} · {next.id}</small><h2>{next.name}</h2><p>Required Power: <strong>{next.power.toLocaleString()}</strong> · Your party: {power.toLocaleString()}</p><p>{power<next.power?`Improve your party by ${next.power-power} Power.`:'Your party has enough Power.'}</p><p>Entry: {next.cost} gold · Victory: {next.gold} gold, {next.xp} EXP, {next.crystals} crystals, 1 Skill Pearl{next.id%3===0?', 1 Skill Scroll':''}{next.id%5===0?', 1 Limit-Break Token':''}</p><Button disabled={locked||game.gold<next.cost} onClick={()=>action('battle',next.id)}>Challenge stage {next.id}</Button><EncounterAdvice game={game} action={action} locked={locked}/><p className="small-note">Insufficient Power spends no gold. First-clear rewards are granted once.</p></article>:<article className="school-card"><h2>First five chapters complete</h2><p>All 30 opening stages cleared. Open Frontier for three more local chapters; patrols remain available.</p></article>}
 {last&&<div className="battle-result" role="status"><strong>{last.won?'Victory':'More training needed'} · Stage {last.stage}</strong><p>Party Power {last.power.toLocaleString()} · {last.kind==='patrol'?'Patrol':'Campaign'}</p></div>}
 </><article className="school-card"><h2>Patrol cleared stages</h2>{game.adventure.cleared?<><NativeSelect aria-label="Patrol stage" value={chosen} onChange={e=>setPatrol(Number(e.target.value))}>{STAGES.slice(0,game.adventure.cleared).map(s=><NativeSelectOption key={s.id} value={s.id}>Stage {s.id} · {s.power} Power</NativeSelectOption>)}</NativeSelect><p>Deposit {chosen*25} gold; returned on victory. Reward: {chosen*40} Fellow EXP. No first-clear loot repeats.</p><Button disabled={locked||game.gold<chosen*25} onClick={()=>action('patrol',chosen)}>Run patrol</Button></>:<p>Clear a stage to unlock repeatable training rewards.</p>}</article><FrontierPanel game={game} action={action} locked={locked}/></PanelPages></PanelPages><details className="rules-note"><summary>About these rules</summary><p className="balance-note">Gold and Fellow Power as exploration requirements are supported by local rules. This 30-stage campaign, party limit, comparisons, rewards and repeatable patrols are local substitutes. The Opening tab separately integrates126 recovered encounters and connected rewards with disclosed local adapters.</p></details></section>}
