import {specialEligible,specialPlan} from '@/lib/special-blessings.mjs';
import {originalProgression} from '@/lib/original-progression.mjs';
import {Button} from '@/components/ui/button';
import {affinityIds} from '@/lib/public-reference.mjs';
import {originalProfile} from '@/lib/original-catalog.mjs';
import {BLESSINGS,blessingLevel,blessingValue,nextBlessingCost,blessingPlan,blessingRecipients,nextBlessingValue} from '@/lib/blessings.mjs';
export default function BlessingPanel({game,id,action,locked}:any){
 const f=game.family[id],pairs=blessingRecipients(game,id);if(!f)return <p>Welcome this family member to train blessings.</p>;
 const value=(key:string,n:number)=>key==='flatBlessing'?`+${n.toLocaleString()} Power`:`+${(n*100).toFixed(1)}% Power`;
 return <article className="family-detail"><h2>Fellow blessings</h2><p>Blessing Points: {f.points.toLocaleString()}</p><p>{pairs.length?'Blesses '+pairs.map((p:string)=>originalProfile(p).name).join(', '):'No documented pairings available yet.'}</p>
 {Object.entries(BLESSINGS).map(([key,r])=>{const level=blessingLevel(f,key),cost=nextBlessingCost(f,key,game),plan=blessingPlan(f,key,game);return <div className="blessing-row" key={key}><h3>{r.name} · Lv. {level}</h3>{f.apkBlessings?.[key]&&<p>Retained {value(key,f.apkBlessings[key].value)} for {f.apkBlessings[key].legacyRecipients.map((p:string)=>originalProfile(p).name).join(', ')||'no earlier recipients'}. New gains follow the APK list above.</p>}<p>{value(key,blessingValue(f,key))}{cost!==null?' → '+value(key,nextBlessingValue(game,f,key)):''}</p><Button disabled={locked||!pairs.length||cost===null||f.points<cost} onClick={()=>action('trainBlessing',id,key)}>{cost===null?'Last enabled level reached':`Improve · ${cost} Blessing Points`}</Button><Button variant="outline" disabled={locked||!pairs.length||!plan.count} onClick={()=>action('trainBlessingsMax',id,key)}>Improve {plan.count} levels · {plan.cost.toLocaleString()} points</Button></div>})}
 {originalProgression(game)&&<section className="blessing-row"><h3>Special Blessing · {f.specialBlessing?`Lv. ${f.specialBlessing.level}`:'Locked'}</h3><p>Requires both earlier blessings at level 700. Adds Family Aptitude to the listed Fellows; their paid Aptitude stays unchanged.</p>{f.specialBlessing?<><p>+{2*f.specialBlessing.level} Family Aptitude · cap 700</p>{([1,5,'max'] as const).map(n=>{const plan=specialPlan(game,id,n);return <Button key={n} disabled={locked||!plan.count} onClick={()=>action('trainSpecialBlessing',id,n)}>Special {n==='max'?'max':`up to ${n}`} · +{plan.count*2} Aptitude · {plan.cost.toLocaleString()} points</Button>})}</>:<Button disabled={locked||!specialEligible(game,id)} onClick={()=>action('activateSpecialBlessing',id)}>Activate Special Blessing · Free sandbox</Button>}<p>Original activation price is unknown. Free activation here requires both tracks at 700; spirit-gated recipients remain excluded.</p><Button variant="outline" disabled={locked||f.points>=1e9} onClick={()=>action('specialBlessingSupply',id)}>Prepare 1B Blessing Points · Sandbox</Button><p>This fills only spendable points. Intimacy and Blessing Power stay yours.</p></section>}
 {f.apkBlessings&&<p>Earlier bonuses remain with their saved original recipients. New gains use the APK list above; spirit-gated and special pairings are excluded.</p>}<p>Recruit a listed Fellow to activate their bonus. Training is retained for Fellows who join later.</p><details className="rules-note"><summary>About these blessings</summary><p>Classic rules retain 36 flat and 24 advanced levels. APK growth uses recovered current-level costs through level 700, preserving earlier values and recipients. The first level retains its existing sandbox purchase price. Community values may be rounded. Source mode admits only default ungated pairings for new gains. Existing sandbox bonds remain separate and retain their training. Flat Power is added after percentage bonuses; the surrounding Power formula and adventure balance remain local. Blessings currently affect Fellow and party Power, not village earnings. Unlock requirements are waived for this private sandbox.</p></details></article>
}
