import PaidStaffing from './paid-staffing';
import {originalProgression} from '@/lib/original-progression.mjs';
import {innGiftEmployeePercent} from '@/lib/inn-guests.mjs';
import {fishingEmployeeBonus} from '@/lib/fishing.mjs';
import {fellowOperation} from '@/lib/operations.mjs';
import HireCardPanel from './hire-card-panel';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import PanelPages from './panel-pages';
import {BUSINESSES,enterpriseState,enterpriseBreakdown,employeeRateFor,operationSlots,employeeCap,sourceEmployeeYield} from '@/lib/businesses.mjs';
import {FELLOWS,BUILDINGS,fellowById} from '@/lib/catalog.mjs';
export default function BusinessPanel({game,action,locked,selectedBusiness,onBusinessSelect,onApothecary}:any){
 const [localSelected,setLocalSelected]=useState(BUSINESSES[0].id),[operator,setOperator]=useState('hero_15');
 const selected=selectedBusiness??localSelected,setSelected=onBusinessSelect??setLocalSelected;
 const definition=BUSINESSES.find(b=>b.id===selected)!,rows=enterpriseState(game),b=rows[selected],rates=enterpriseBreakdown(game,selected);
 const available=FELLOWS.filter(f=>Object.hasOwn(game.fellows,f.id));
 const workplace=(id:string)=>BUSINESSES.find(d=>rows[d.id]?.fellows.includes(id))?.name||BUILDINGS.find(d=>game.buildings[d.id]?.fellow===id)?.name||'Unassigned';
 return <section><label htmlFor="original-business">Village business</label><NativeSelect id="original-business" value={selected} onChange={e=>setSelected(e.target.value)}>{BUSINESSES.map(d=><NativeSelectOption key={d.id} value={d.id}>{d.name}{rows[d.id]?' · Open':''}</NativeSelectOption>)}</NativeSelect>
 <h2>{definition.name}</h2>{selected==='Building_201'&&<p className="small-note">Manage employees and Fellow assignments to earn village gold. Potion sales have a separate counter and deposit.</p>}{selected==='Building_201'&&onApothecary&&<Button variant="outline" onClick={onApothecary}>Open potion counter</Button>}<p>{definition.type?`${definition.type} type`:'Type not yet verified'} · {b?.staffingYield?'Mixed retained and APK employee rates':`${employeeRateFor(game,definition)} gold/s per employee`}</p>
 {!b?<><p>{definition.description}</p><Button disabled={locked} onClick={()=>action('openEnterprise',selected)}>Open · Free sandbox</Button></>:<>
 <div className="family-stats"><div><span>Employees</span><strong>{b.employees.toLocaleString()}</strong></div><div><span>Fellows</span><strong>{b.fellows.length}/{operationSlots(b.employees)}</strong></div><div><span>Gold / second</span><strong>{rates.total.toLocaleString(undefined,{maximumFractionDigits:2})}</strong></div></div>
 <PanelPages labels={['Employees','Paid growth','Hire cards','Fellows','Earnings']}><><p>Staffing opens Fellow slots at 50, 200, 800 and 5,000 employees.</p><div className="business-actions">{[1,10,50,200,800,5000].map(n=><Button key={n} variant="outline" disabled={locked||b.employees>=employeeCap} onClick={()=>action('hireEmployees',selected,n)}>Hire +{Math.max(0,Math.min(n,employeeCap-b.employees)).toLocaleString()} · Free</Button>)}</div><p className="small-note">These free grants stop at 5,000 employees. Paid growth has separate gold costs and quality limits.</p>{originalProgression(game)&&<p>Future hires: {sourceEmployeeYield(selected)} base gold/s each from APK data. Existing employees keep their earlier rate. Hire Cards follow the same rule.</p>}{b.staffingYield&&<p>Retained employees: {b.staffingYield.retainedEmployees.toLocaleString()} × {b.staffingYield.retainedRate} base gold/s. APK employees: {(b.employees-b.staffingYield.retainedEmployees).toLocaleString()} × {sourceEmployeeYield(selected)}.</p>}</><PaidStaffing game={game} id={selected} action={action} locked={locked}/><HireCardPanel game={game} action={action} locked={locked}/><>
 <label htmlFor="operating-fellow">Choose an operating Fellow</label><NativeSelect id="operating-fellow" value={operator} onChange={e=>setOperator(e.target.value)}>{available.map(f=><NativeSelectOption key={f.id} value={f.id}>{f.name} · {f.type||'Unknown type'} · {workplace(f.id)}</NativeSelectOption>)}</NativeSelect>
 <p>{fellowOperation(game,operator,definition).known?`Selected Fellow: +${fellowOperation(game,operator,definition).percent}% here when assigned.`:"Selected Fellow: operation bonus not yet verified."} {fellowOperation(game,operator,definition).next.map((e:any)=>`Level ${e.minLevel}: another +${e.percent}%.`).join(" ")}</p>
 <Button disabled={locked||b.fellows.includes(operator)||b.fellows.length>=operationSlots(b.employees)} onClick={()=>action('assignOperator',selected,operator)}>Move Fellow here</Button>
 {b.fellows.map((id:string)=><div className="worker" key={id}><span>{fellowById(id)?.name} · +{fellowOperation(game,id,definition).percent}%</span><Button variant="outline" disabled={locked} onClick={()=>action('removeOperator',selected,id)}>Remove</Button></div>)}
 <p className="small-note">Each Fellow works in one business. Moving them leaves the previous job vacant. Type restrictions are waived. Documented Fifi and Amaterasu bonuses apply to matching businesses. Other operation skills remain unverified. The roster Power contribution applies regardless of workplace.</p></><>
 <p>Legacy base per employee: {definition.employeeRate} base + {fishingEmployeeBonus(game,definition.type)} Fishing bonus; +{innGiftEmployeePercent(game,definition.type)}% Inn treasure bonus. applied across {b.employees.toLocaleString()} employees; any retained/APK base cohorts are shown in Employees.</p><p>Employee earnings: {rates.employees.toLocaleString()} gold/s</p><p>Whole-roster Power contribution: {rates.operation.toLocaleString(undefined,{maximumFractionDigits:3})} gold/s</p><p>Assigned operation + earned quality bonus: {(rates.bonus*100).toLocaleString()}% (quality: {((rates.qualityBonus||0)*100).toLocaleString()}%).</p><p>(Employee earnings + roster contribution) × {1+rates.bonus} = {rates.total.toLocaleString(undefined,{maximumFractionDigits:3})} gold/s</p>
 <p className="small-note">Earlier employee rates come from a community reference; future APK-growth hires use recovered literal business yields, preserving the older cohort. Whole-roster Power ÷ 1,000 follows community reports and the local divisor. The underlying Power formula is still reconstructed. Operation bonuses cover two documented Fellows; unknown unlocks are excluded. Service levels and operation upgrade costs remain pending.</p></></PanelPages></>}
 <details className="rules-note"><summary>Business rules</summary><p>Names and descriptions match the readable APK. Legacy employee rates and Fellow-slot thresholds use public documentation; future APK-growth hires use recovered yields. Your original three starter businesses retain their previous rules in the next tab. New business earnings join the village total and offline earnings. Opening remains free. Optional Paid growth uses recovered hiring costs and quality steps, with explicit sandbox compatibility grants.</p></details></section>;
}
