import InsightTraining from './insight-training';
import {insightRule} from '@/lib/insight.mjs';
import {useState} from 'react';
import {Button} from '@/components/ui/button';import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {characterSkills,isPlayableTalent} from '@/lib/character-skills.mjs';import {talentRule,talentLevel,talentTrainingPlan,talentCap} from '@/lib/talents.mjs';
export default function CharacterSkillGuide({id,game,action,locked}:any){
 const [open,setOpen]=useState(false),[index,setIndex]=useState(0),profile=characterSkills(id),nodes=profile?.skills||[],node=nodes[Math.min(index,Math.max(0,nodes.length-1))],playable=isPlayableTalent(id,node),rule=talentRule(id),owned=game.fellows[id],plan=talentTrainingPlan(game,id,1);
 return <><Button variant="outline" onClick={()=>setOpen(true)}>Character skill guide</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="save-dialog"><DialogTitle>{profile?.name||'Character'} · Skill guide</DialogTitle><DialogDescription>Documented skills for this exact character. Some progression is still unavailable in the sandbox.</DialogDescription>{nodes.length?<><label htmlFor="documented-skill">Documented skill</label><NativeSelect id="documented-skill" value={Math.min(index,nodes.length-1)} onChange={e=>setIndex(Number(e.target.value))}>{nodes.map((n:any,i:number)=><NativeSelectOption key={i} value={i}>{n.name}{(isPlayableTalent(id,n)||insightRule(id)?.skillId===n.id)?' · Training available':''}</NativeSelectOption>)}</NativeSelect><h3>{node.name}</h3>{node.lines.map((line:string,i:number)=><p key={i}>{line}</p>)}{owned&&insightRule(id)?.skillId===node.id?<InsightTraining id={id} game={game} action={action} locked={locked}/>:playable&&owned?<><p>Current talent level: {talentLevel(owned)} / {talentCap(game,id)} supported levels. APK growth supports 299 paid upgrades, corresponding to source levels 1–300. Existing paid gains remain yours; no initial Aptitude is added again.</p><Button disabled={locked||!plan.count} onClick={()=>action('trainTalent',id,1)}>Train documented talent · {plan.cost} pearls</Button></>:<p>Reference only. This skill’s complete costs, unlocks or effects are not implemented.</p>}</>:<p>No skill entries were published in this character’s pinned source page. This does not mean the original character has no skills.</p>}<p className="small-note">Pinned community reference; versions may differ from the APK. Costume labels do not grant costume ownership. Existing training and progress remain unchanged.</p></DialogContent></Dialog></>;
}
