import {artifactRule,artifactState,basicCopies,trackedCopies,trackedRefund} from '@/lib/artifacts.mjs';
import {useState} from 'react';import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';import {GEAR} from '@/lib/adventure.mjs';
export default function EquipmentShelf({game,action,locked}:any){
 const [query,setQuery]=useState(''),[page,setPage]=useState(0),[rarity,setRarity]=useState('all');
 const rarities=[...new Set(GEAR.map(g=>artifactRule(g.id)?.rarity).filter(Boolean))],items=GEAR.filter(g=>g.name.toLowerCase().includes(query.toLowerCase())&&(rarity==='all'||artifactRule(g.id)?.rarity===rarity)),pages=Math.max(1,Math.ceil(items.length/2)),current=Math.min(page,pages-1);
 return <><div className="roster-search"><Input aria-label="Find equipment" type="search" placeholder="Find equipment…" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/><NativeSelect aria-label="Equipment rarity" value={rarity} onChange={e=>{setRarity(e.target.value);setPage(0)}}><NativeSelectOption value="all">All rarities</NativeSelectOption>{rarities.map(r=><NativeSelectOption value={r} key={r}>{r}</NativeSelectOption>)}</NativeSelect></div><p>{items.length} artifacts · Magic Ore: {artifactState(game).ore.toLocaleString()}</p><p className="small-note">Raphael’s Stage awards earned Magic Ore at 390 and 1,200 support Stamina. Claim it under Event → Milestones and move it here.</p><div className="business-actions"><Button variant="outline" disabled={locked||artifactState(game).ore>=1e9} onClick={()=>action('claimOre')}>Take 1,000 Ore · Free</Button><Button variant="outline" disabled={locked} onClick={()=>action('claimAllGear')}>Take every artifact · Free</Button></div>
 {items.slice(current*2,current*2+2).map(g=>{const r=artifactRule(g.id)!,basic=basicCopies(game,g.id),upgraded=game.inventory[g.id]-basic;return <article className="school-card" key={g.id}><div className="identity"><h3>{g.name}</h3><strong>{r.rarity} · ×{game.inventory[g.id]}</strong></div><p>Base Aptitude +{g.aptitude} · +{r.perLevel} per level</p><p>{r.ore} Magic Ore per upgrade · {basic} level-one copies · {upgraded} upgraded copies in bag</p><Button disabled={locked||game.inventory[g.id]>=1e6||(g.price!==null&&game.crystals<g.price)} onClick={()=>action(g.price===null?'claimGear':'buySupply',g.id)}>{g.price===null?'Take for sandbox · Free':`Buy · ${g.price} crystals`}</Button>{r.recycle?<div className="business-actions"><Button variant="outline" disabled={locked||!basic||artifactState(game).ore+r.recycle>1e9} onClick={()=>action('recycleArtifact',g.id,1)}>Recycle 1 · +{r.recycle} Ore</Button><Button variant="outline" disabled={locked||!basic||artifactState(game).ore+r.recycle>1e9} onClick={()=>action('recycleArtifact',g.id,'all')}>Recycle level-one copies</Button></div>:<p>Recycle reward not verified.</p>}<TrackedRecycle game={game} id={g.id} upgraded={upgraded} action={action} locked={locked}/></article>})}
 {!items.length&&<p>No equipment matches.</p>}<nav className="album-pagination" aria-label="Equipment pages"><Button variant="outline" disabled={!current} onClick={()=>setPage(current-1)}>Previous</Button><span>{current+1} / {pages}</span><Button variant="outline" disabled={current===pages-1} onClick={()=>setPage(current+1)}>Next</Button></nav><details className="rules-note"><summary>About equipment</summary><p>Names match local item IDs; base stats, growth and recycle rewards come from the public reference. Unequipped level-one copies and upgraded copies with complete recorded investments can be recycled. The full recorded Ore investment plus the verified base reward is returned. Older upgraded copies without records remain protected; later upgrades cannot reconstruct their past spending. At equal levels, equipping prefers a recorded copy. Named Echo and three Family-supported equipment effects are available in Fellow Equipment. Random skills, other special effects, awakening and materia remain pending. Level 20 and the three shop prices are local sandbox limits/prices.</p></details></>;
}

function TrackedRecycle({game,id,upgraded,action,locked}:any){
 const [selection,setSelection]=useState(''),copies=trackedCopies(game,id),known=copies.reduce((n,c)=>n+c.count,0),selected=copies.find(c=>`${c.level}:${c.spent}`===selection)||copies[0];
 const refund=selected?trackedRefund(game,id,selected.level,selected.spent):null;
 return <details className="rules-note"><summary>Upgraded copy recovery · {known} recorded</summary>
 {upgraded>known&&<p>{upgraded-known} older copies have unknown investment and cannot be recycled.</p>}
 {selected?<><NativeSelect aria-label="Choose upgraded copy to recycle" value={`${selected.level}:${selected.spent}`} onChange={e=>setSelection(e.target.value)}>{copies.map(c=><NativeSelectOption key={`${c.level}:${c.spent}`} value={`${c.level}:${c.spent}`}>Level {c.level} · {c.spent} Ore invested · ×{c.count}</NativeSelectOption>)}</NativeSelect><p>{refund===null?'Base recycle reward not verified. This copy stays protected.':`${selected.spent} invested Ore + ${refund-selected.spent} base Ore = ${refund} Ore returned.`}</p><Button variant="outline" disabled={locked||refund===null||artifactState(game).ore+refund>1e9} onClick={()=>action('recycleTrackedArtifact',id,{level:selected.level,spent:selected.spent})}>Recycle this unequipped copy</Button></>:<p>Upgrade a level-one copy to start recording its investment, then unequip it to recycle.</p>}</details>;
}
