import {criticalBase} from '@/lib/familiar-crit-combat.mjs';
import {BASIC_HEAL,basicHealActive} from '@/lib/familiar-trigger-combat.mjs';
import {statPassive} from '@/lib/familiar-passives.mjs';
import {familiarStage} from '@/lib/familiars.mjs';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {FAMILIARS,familiarById} from '@/lib/familiars.mjs';
import {towerState,towerKey,towerBattle,towerEnemy,towerReward,towerSkill} from '@/lib/familiar-tower.mjs';
const statusNames:Record<string,string>={attack:'Attack',speed:'Speed',dealt:'Damage dealt',vulnerable:'Damage taken',bleed:'Bleed',poison:'Poison',shield:'Shield',regen:'Regeneration',crit:'Critical chance',critRes:'Critical resistance'};
export default function FamiliarTowerPanel({game,action,locked}:any){
 const t=towerState(game),owned=FAMILIARS.filter(p=>game.familiars?.[p.id]),[chosen,setChosen]=useState('');
 const id=chosen||owned[0]?.id,floor=t.cleared+1,enemy=towerEnemy(floor),reward=towerReward(floor),last=t.last&&towerBattle(t.last.floor,t.last.team,t.last.combatVersion??1);
 const passive=statPassive(id),passiveActive=!!(passive&&game.familiars?.[id]&&familiarStage(game.familiars[id].level)>=passive.stage);
 return <section aria-label="Familiar tower"><h3>Familiar Tower</h3><p>{t.cleared} / 12 floors cleared · Free attempts</p><p>First-clear rewards support Fellow training. Familiars can still be welcomed and trained freely.</p>
 {!!owned.length&&<><label htmlFor="tower-familiar">Choose a team member</label><NativeSelect id="tower-familiar" value={id} onChange={e=>setChosen(e.target.value)}>{owned.map(p=><NativeSelectOption key={p.id} value={p.id}>{p.name}{t.party.includes(p.id)?' · In team':''}</NativeSelectOption>)}</NativeSelect><Button variant="outline" disabled={locked||(!t.party.includes(id)&&t.party.length===5)} onClick={()=>action('towerParty',id)}>{t.party.includes(id)?'Remove from tower team':'Add to tower team'}</Button></>}
 <p>{id&&towerSkill(id)?`${towerSkill(id)!.name}: ${towerSkill(id)!.text}`:"Selected familiar uses a local double-damage Rage strike; its original skill is not implemented."}</p>{t.party.includes(id)&&<Button variant="outline" disabled={locked||t.party[0]===id} onClick={()=>action('towerFront',id)}>Move to first front slot</Button>}{passive&&<p>Battle passive · {passive.text} · {passiveActive?'Active at this stage':'Unlocks at Stage 2 · level 50'}. Training stats stay unchanged.</p>}{id===BASIC_HEAL.id&&<p>Stage 4 passive · {BASIC_HEAL.text} · {basicHealActive({id,...game.familiars[id]})?'Active at this stage':'Unlocks at level 150'}. Applies after Dream Eater’s own basic attack.</p>}{id&&['Pet_1191','Pet_12141','Pet_32341','Pet_42141','Pet_8041504'].includes(id)&&<details className="rules-note"><summary>Damage-over-time rules</summary><p>Effects use stats captured when cast and begin ticking after the casting round. Bleed and Poison coexist; another cast refreshes that familiar’s same effect. Different familiars can stack effects.</p><p>Rainbel and Wumeow use maximum HP for Bleed as a sandbox choice. Snowbear uses the recovered two-turn Bleed and three-turn Speed penalty. Umbradrake uses the sandbox damage-taken modifier. Front-row fallback, targeting and combat timing follow this local Tower.</p></details>}{id&&<details className="rules-note"><summary>Critical hit rules</summary><p>{criticalBase(id).critBP/100}% base critical chance · {criticalBase(id).resistanceBP/100}% base resistance. Tower guardians have a local 5% critical chance.</p><p>Active bonuses add percentage points. Enemy resistance subtracts from critical chance, with the final chance limited to 0–100%. Critical direct hits deal 150% damage before shields and damage-taken modifiers; damage over time and healing never crit.</p><p>Rolls repeat for the same saved battle. This probability rule and starting stats are sandbox choices using the declared reference values. No extra critical passives are enabled. Icyowl’s shield and critical bonus last 3 turns, following the recovered rows.</p></details>}<p>Front: {t.party.slice(0,2).map((p:string)=>familiarById(p)?.name).join(', ')||'Empty'}<br/>Back: {t.party.slice(2).map((p:string)=>familiarById(p)?.name).join(', ')||'Empty'}</p><p>Team {t.party.length}/5: {t.party.map((p:string)=>familiarById(p)?.name).join(', ')||'Welcome a familiar on Training, then add them here.'}</p>
 {floor<=12?<><p>Floor {floor} · Three guardians<br/>Each: {enemy.ATK} Attack · {enemy.HP} Health · {enemy.SPD} Speed</p><p>First clear: {reward.pearls} Skill Pearls + {reward.xp.toLocaleString()} Fellow EXP</p><Button disabled={locked||!t.party.length} onClick={()=>action('towerFight',towerKey(game))}>Challenge floor {floor}</Button></>:<p>All 12 sandbox floors cleared!</p>}
 {last&&<details open><summary>Floor {t.last.floor} · {last.won?'Victory':'Defeat'} · {last.rounds} rounds</summary><p>Remaining health: your team {last.playerHP.toLocaleString()} · guardians {last.enemyHP.toLocaleString()}</p><details><summary>Battle record</summary><ol>{last.log.map((hit:any,i:number)=><li key={i}>Round {hit.round}: {familiarById(hit.attacker)?.name||hit.attacker} → {familiarById(hit.target)?.name||hit.target} · {hit.critical?'Critical · ':''}{hit.name||(hit.skill?'Rage strike':'Attack')} · {hit.kind==='status'?`${statusNames[hit.status]||hit.status} ${['crit','critRes'].includes(hit.status)?hit.value/100:hit.value}${['vulnerable','attack','speed','dealt','crit','critRes'].includes(hit.status)?'%':''} · ${hit.turns} turns`:`${['heal','regen'].includes(hit.kind)?'healed':'damage'} ${hit.damage}${hit.absorbed?` · shield absorbed ${hit.absorbed}`:''}`}</li>)}</ol></details></details>}
 <details className="rules-note"><summary>Sandbox tower rules</summary><p>1–5 familiars act in Speed order for up to 15 rounds. Higher remaining team Health wins; ties lose. Each attempt starts fully healed. These 12 floors, rewards and damage rules are local: basic attacks deal Attack damage, Rage fills by 25 when attacking or hit, and a full meter gives a double-damage strike. Sixty-three familiars use documented active effects, including regeneration, percentage healing, Bleed, Poison, shields, Attack, Speed, damage dealt and damage taken; other strikes remain local. Speed changes affect the next round’s order. Skill amounts snapshot before their own buffs; matching modifiers add once. Status timing and stacking are local: periodic effects tick after subsequent rounds, same-caster effects refresh, and shields absorb direct and periodic damage. Version 6 resolves periodic damage before regeneration and expiry; defeated units cannot be healed. ATK-based healing snapshots the caster, while Max HP effects use the named recipient or self. Healing stops at full health. Lowest-HP% targeting uses health fraction, with slot order breaking ties. First two team slots are front row. Empty target rows fall back to surviving units on the intended side; random targeting uses a repeatable local sequence. Version 7 includes 25 documented self Attack, Max HP or Speed passives from Stage 2, applied once before temporary battle modifiers. Each initialized stat is rounded down. Stage advancement through free training is local. Version 8 adds Dream Eater’s Stage 4 healing after its own basic attacks. Living allies, including itself, recover up to 75% of its effective Attack; amounts round down and stop at full health. This timing is a local rule. Version 10 adds eight complete critical-related active skills and the local critical rules described above. Other passives, blocks, type bonuses, 200 floors and idle rewards are not included. Old battle reports retain their original combat rules.</p></details></section>;
}
