import FamilyGalleryPanel from './family-gallery-panel';
import {availableDateEnergy,tonicReserve} from '@/lib/tonics.mjs';
import FamilyArtStage from './family-art-stage';
import {dateReward} from '@/lib/dating.mjs';
import {fishingDateBonus} from '@/lib/fishing.mjs';
import CharacterSkillGuide from './character-skill-guide';
import CharacterCollection from './character-collection';
import CharacterShowcase from './character-showcase';
import BlessingPanel from './blessing-panel';
import CharacterScene from './character-scene';
import ConsumableShelf from './consumable-shelf';
import BondPanel from './bond-panel';
import PanelPages from './panel-pages';
import {Button} from '@/components/ui/button';
import {FAMILY,GIFTS} from '@/lib/catalog.mjs';
import {energyCap,blessingCost,familyBonus,ENERGY_RECOVERY_MS} from '@/lib/progression.mjs';
import {relationRequired} from '@/lib/school.mjs';
export default function FamilyPanel({game,action,selected,onSelect,locked,onReadStory}:any){const person=FAMILY.find(f=>f.id===selected)||FAMILY[0],member=game.family[person.id];return <section className="family-panel"><CharacterCollection owned={game.family} entries={FAMILY} selected={selected} onSelect={onSelect} family/>

 <PanelPages labels={['Profile','Dates','Gifts','More gifts','Bonds','Blessings','Pictures']}><article className="family-detail"><small>YOUR FAMILY</small><h2>{person.name}</h2><CharacterSkillGuide key={person.id+'-skill-guide'} id={person.id} game={game} action={action} locked={locked}/><CharacterShowcase key={person.id+'-art'} person={person}/><CharacterScene key={person.id+'-encounter'} id={person.id} locked={locked} onRead={onReadStory}/><p>{person.title} · {person.description||'No biography was recovered for this character.'}</p>{member?<><div className="family-stats"><div><span>Intimacy</span><strong>{member.intimacy}</strong></div><div><span>Blessing Power</span><strong>{member.blessingPower}</strong></div><div><span>Blessing Points</span><strong>{member.points}</strong></div></div><p className="management-hint">Blessing Power increases points earned on dates. Intimacy increases pupil graduation earnings. Improve relationships to raise the Intellect of future pupils.</p><div className="blessing-row"><h3>Relationship · Tier {member.relationship}</h3><p>Future pupil Intellect: {member.relationship*10}. Intimacy is not consumed.</p><Button disabled={locked||member.relationship>=5||member.intimacy<relationRequired(member.relationship)} onClick={()=>action('relationship',person.id)}>{member.relationship>=5?'Current tier cap reached':`Improve relationship · requires ${relationRequired(member.relationship)} Intimacy`}</Button></div><div className="blessing-row"><h3>Family skill · Lv. {member.skill}</h3><p>+{member.skill}% village earnings · {Math.round(familyBonus(game)*100)}% from all family skills</p><Button disabled={locked||member.skill>=20||member.points<blessingCost(member)} onClick={()=>action('bless',person.id)}>{member.skill>=20?'Fully upgraded':`Improve skill · ${blessingCost(member)} points`}</Button></div></>:<p>Welcome family members to begin gifts and dates.</p>}<Button className="recruit" disabled={locked||Object.keys(game.family).length===FAMILY.length} onClick={()=>action('welcome',member?null:person.id)}>{Object.keys(game.family).length===FAMILY.length?'Everyone is home':member?'Welcome family · Free':`Welcome ${person.name} · Free`}</Button><Button variant="outline" disabled={locked||Object.keys(game.family).length===FAMILY.length} onClick={()=>action('welcomeAll')}>Welcome all remaining family · Free</Button></article>
 <section><h2>Family dates</h2><div className="family-date-layout"><div className="family-date-setting"><FamilyArtStage key={person.id+'-date'} person={person} context="date"/><p>{person.name}</p></div><div className="family-date-actions"><strong>Natural Energy {Math.floor(game.energy)} / {energyCap(game)}</strong><small>Tonic reserve: {tonicReserve(game)} · spent first</small><small>{game.energy>=energyCap(game)?'Fully recovered':`Next Energy in ${Math.ceil((1-game.energy%1)*ENERGY_RECOVERY_MS/1000)}s`}</small><Button disabled={locked||availableDateEnergy(game)<1||!Object.keys(game.family).length} onClick={()=>action('date',null,Math.random())}>Random date · 1 Energy</Button><Button variant="outline" disabled={locked||availableDateEnergy(game)<1||!Object.keys(game.family).length} onClick={()=>action('autoDate')}>Auto-date · Use {availableDateEnergy(game)} Energy</Button></div></div><p className="small-note">Selected portrait: {person.name}. Random dates can choose any joined Family member.</p>{member&&<p>If dated, {person.name} gains {dateReward(game,person.id).credited.toLocaleString()} points ({member.blessingPower.toLocaleString()} base{dateReward(game,person.id).credited<dateReward(game,person.id).total?' · storage capped':''}).</p>}<details className="rules-note"><summary>Date bonuses and Energy</summary><p>Fishing combination bonus: +{fishingDateBonus(game)}% Blessing Points. Each date uses 1 Energy, even at the point storage cap. Spend points on blessings to make room.</p></details>
</section><section className="gift-bag"><h2>Gift bag</h2><p>Give to {person.name}. Buy additional gifts with village gold.</p>{GIFTS.map(g=><div className="gift-row" key={g.id}><div><strong>{g.name} <span>×{game.inventory[g.id]}</span></strong><p>+{g.amount} {g.stat==='intimacy'?'Intimacy':'Blessing Power'}</p></div><div><Button variant="outline" aria-label={'Buy '+g.name} disabled={locked||game.gold<g.price||game.inventory[g.id]>=1e6} onClick={()=>action('buyGift',g.id)}>Buy · {g.price}g</Button><Button aria-label={'Give '+g.name+' to '+person.name} disabled={locked||!member||!game.inventory[g.id]} onClick={()=>action('gift',person.id,g.id)}>Give</Button></div></div>)}</section><ConsumableShelf game={game} action={action} locked={locked} familyId={person.id}/><BondPanel game={game} id={person.id} action={action} locked={locked}/><BlessingPanel game={game} id={person.id} action={action} locked={locked}/><FamilyGalleryPanel key={person.id} game={game} person={person} action={action} locked={locked}/></PanelPages>
 <details className="rules-note"><summary>About these rules</summary><p className="balance-note">Gift effects and the separate family stats follow the readable game data. Auto-date uses available whole Energy and preserves the fractional remainder; its original rank/VIP unlock is waived. Starting stats, welcome method, date rewards, one-minute Energy recovery, shop prices and the +1% skill are local balance. Pupil formulas and relationship thresholds are local balance; Documented family–Fellow pairings are available under Bonds; their bonus strength remains local balance.</p></details>
 </section>}
