import {criticalBase} from '@/lib/familiar-crit-combat.mjs';
import {BASIC_HEAL,basicHealActive} from '@/lib/familiar-trigger-combat.mjs';
import {statPassive} from '@/lib/familiar-passives.mjs';
import {familiarStage} from '@/lib/familiars.mjs';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {cardStyle,cardRarity,rarityIcon} from '@/lib/ui-sprites.mjs';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {FAMILIARS,familiarById} from '@/lib/familiars.mjs';
import {towerState,towerKey,originalBattle,floorEnemies,towerFloor,towerSkill,TOWER_FLOORS,TOWER_AUTO_UNLOCK,TOWER_DATA} from '@/lib/familiar-tower.mjs';
import {familiarSupplies,suppliesWaiting,floorIncome} from '@/lib/familiar-supplies.mjs';
import {EXPLORE_AREAS} from '@/lib/familiar-explore.mjs';
const statusNames:Record<string,string>={attack:'Attack',speed:'Speed',dealt:'Damage dealt',vulnerable:'Damage taken',bleed:'Bleed',poison:'Poison',shield:'Shield',regen:'Regeneration',crit:'Critical chance',critRes:'Critical resistance'};
const unitName=(id:string)=>{const [slot,pet]=id.includes(':')?id.split(':'):[null,id];return (familiarById(pet)?.name||pet)+(slot?' (enemy)':'')};
/** The next floor whose Income is higher than the current one: the "milestone" the original shows. */
function nextIncomeStep(cleared:number){const now=floorIncome(cleared);for(let f=cleared+1;f<=TOWER_FLOORS;f++){const i=floorIncome(f);if(i.levelUp!==now.levelUp||i.classUp!==now.classUp)return {floor:f,income:i};}return null}
function rewardLine(floor:number){const r:any=towerFloor(floor)!.reward,parts=[];if(r.levelUp)parts.push(`${r.levelUp} level-up`);if(r.classUp)parts.push(`${r.classUp} class-up`);if(r.Item_PetCatch2)parts.push(`${r.Item_PetCatch2} Advanced Contract`);if(r.Item_PetPacify1)parts.push(`${r.Item_PetPacify1} Ordinary Mochi`);if(r.familiar)parts.push(`familiar ${familiarById(r.familiar)?.name}`);return parts.join(' + ')}
export default function FamiliarTowerPanel({game,action,locked}:any){
 const t=towerState(game),owned=FAMILIARS.filter(p=>game.familiars?.[p.id]),[chosen,setChosen]=useState('');
 const id=chosen||owned[0]?.id,floor=t.cleared+1,data=floor<=TOWER_FLOORS?towerFloor(floor)!:null,enemies=data?floorEnemies(floor):[],last=t.last&&originalBattle(t.last.floor,t.last.team);
 const passive=statPassive(id),passiveActive=!!(passive&&game.familiars?.[id]&&familiarStage(game.familiars[id].level)>=passive.stage);
 const income=floorIncome(t.cleared),step=nextIncomeStep(t.cleared),waiting=suppliesWaiting(game,Date.now()),supplies=familiarSupplies(game);
 const nextArea=EXPLORE_AREAS.find((a:any)=>a.unlock>t.cleared),nextFamiliar=TOWER_DATA.floors.find((f:any)=>f.floor>t.cleared&&f.reward.familiar);
 return <section className="familiar-tower" aria-label="Familiar tower"><h4 className="bond-ribbon">Familiar Tower · Challenge Mode</h4><div className="bond-progress"><span>Floors</span><progress value={t.cleared} max={TOWER_FLOORS} aria-label="Floors cleared"/><b>{t.cleared}/{TOWER_FLOORS}</b></div>
 <article className="tower-floor"><h4>Hourly earnings</h4><p>{t.cleared?`${income.levelUp} level-up + ${income.classUp} class-up items an hour, held up to ${TOWER_DATA.holdHours} hours.`:'Earning unlocks after completing Floor 1.'}</p>{step&&<p>Floor {step.floor} raises it to {step.income.levelUp} + {step.income.classUp}.</p>}
  <p className="item-status">{supplies.levelUp.toLocaleString()} level-up · {supplies.classUp.toLocaleString()} class-up in store{waiting.hours?` · ${waiting.levelUp.toLocaleString()} + ${waiting.classUp.toLocaleString()} waiting`:''}</p>
  <Button variant="outline" disabled={locked||!(waiting.levelUp||waiting.classUp)} onClick={()=>action('collectFamiliarSupplies')}>Collect tower items</Button></article>
 {/* Five team slots, the first two the front row, as the tower resolves them. */}
 <ol className="tower-slots" aria-label={`Tower team ${t.party.length} of 5`}>{[0,1,2,3,4].map(i=>{const pid=t.party[i],pet=pid?familiarById(pid):null;return <li key={i} className={i<2?'front':'back'}>{pet?<div className="framed-card" style={cardStyle(pet.rarity) as any}><span>{rarityIcon(cardRarity(pet.rarity))&&<img src={rarityIcon(cardRarity(pet.rarity))!} alt=""/>}</span><strong>{pet.name}</strong></div>:<div className="tower-empty">+</div>}<small>{i<2?'Front':'Back'}</small></li>})}</ol>
 {!!owned.length&&<><label htmlFor="tower-familiar">Choose a team member</label><NativeSelect id="tower-familiar" value={id} onChange={e=>setChosen(e.target.value)}>{owned.map(p=><NativeSelectOption key={p.id} value={p.id}>{p.name} · Lv. {game.familiars[p.id].level}{t.party.includes(p.id)?' · In team':''}</NativeSelectOption>)}</NativeSelect><Button variant="outline" disabled={locked||(!t.party.includes(id)&&t.party.length===5)} onClick={()=>action('towerParty',id)}>{t.party.includes(id)?'Remove from tower team':'Add to tower team'}</Button></>}
 {id&&<details className="rules-note tower-skill"><summary>Skill · {towerSkill(id)?towerSkill(id)!.name:'Rage strike'}</summary><p>{towerSkill(id)?towerSkill(id)!.text:'This familiar uses a local double-damage Rage strike; its original skill is not implemented.'}</p>{passive&&<p>Battle passive · {passive.text} · {passiveActive?'Active at this stage':'Unlocks at Stage 2 · level 50'}.</p>}{id===BASIC_HEAL.id&&<p>Stage 4 passive · {BASIC_HEAL.text} · {basicHealActive({id,...game.familiars[id]})?'Active':'Unlocks at level 150'}.</p>}<p>{criticalBase(id).critBP/100}% base critical chance · {criticalBase(id).resistanceBP/100}% resistance.</p></details>}
 {t.party.includes(id)&&<Button variant="outline" disabled={locked||t.party[0]===id} onClick={()=>action('towerFront',id)}>Move to first front slot</Button>}
 {!t.party.length&&<p className="tower-hint">{owned.length?'Add a familiar to the team.':'Contract a familiar first: choose a starter on the Familiars page.'}</p>}
 {data?<article className="tower-floor"><h4>Floor {floor}{data.boss?' · Boss':''}</h4><p>{enemies.length} {enemies.length===1?'enemy':'enemies'}</p>
  <ul className="tower-enemies">{enemies.map((e:any)=><li key={e.id}><b>{familiarById(e.pet)?.name||e.pet}</b> Lv. {e.level} · ATK {e.ATK.toLocaleString()} · HP {e.HP.toLocaleString()} · SPD {e.SPD.toLocaleString()}</li>)}</ul>
  <p className="tower-reward">First clear: {rewardLine(floor)}</p>
  <Button disabled={locked||!t.party.length} onClick={()=>action('towerFight',towerKey(game))}>Challenge floor {floor}</Button>
  <Button variant="outline" disabled={locked||!t.party.length||t.cleared<TOWER_AUTO_UNLOCK} onClick={()=>action('towerAuto',towerKey(game))}>{t.cleared<TOWER_AUTO_UNLOCK?`Auto mode unlocks after floor ${TOWER_AUTO_UNLOCK}`:'Auto · up to 10 floors'}</Button></article>:<p>All {TOWER_FLOORS} floors cleared!</p>}
 {(nextArea||nextFamiliar)&&<p className="item-status">{nextArea&&`Floor ${nextArea.unlock} opens ${nextArea.name} for exploring. `}{nextFamiliar&&`Floor ${nextFamiliar.floor} rewards ${familiarById(nextFamiliar.reward.familiar)?.name}.`}</p>}
 {last&&<details open className={'tower-result '+(last.won?'won':'lost')}><summary>Floor {t.last.floor} · {last.won?'Victory':'Defeat'} · {last.rounds} rounds</summary><p>Remaining health: your team {last.playerHP.toLocaleString()} · enemies {last.enemyHP.toLocaleString()}</p><details><summary>Battle record</summary><ol>{last.log.map((hit:any,i:number)=><li key={i}>Round {hit.round}: {unitName(hit.attacker)} → {unitName(hit.target)} · {hit.critical?'Critical · ':''}{hit.name||(hit.skill?'Rage strike':'Attack')} · {hit.kind==='status'?`${statusNames[hit.status]||hit.status} ${['crit','critRes'].includes(hit.status)?hit.value/100:hit.value}${['vulnerable','attack','speed','dealt','crit','critRes'].includes(hit.status)?'%':''} · ${hit.turns} turns`:`${['heal','regen'].includes(hit.kind)?'healed':'damage'} ${hit.damage}${hit.absorbed?` · shield absorbed ${hit.absorbed}`:''}`}</li>)}</ol></details></details>}
 {t.legacy&&<p className="item-status">Your village cleared {t.legacy.cleared} of the old 12 sandbox floors, which paid the income of original floor {25*t.legacy.cleared}; you continue from floor {t.cleared+1} at that same rate.</p>}
 <details className="rules-note"><summary>Tower rules and what is measured</summary><p>All 300 floors come from the original tower table: each floor’s enemy familiars with their own level, Attack, Health and Speed, its one-time Challenge reward, and its hourly income of level-up and class-up items, held for 24 hours. Floors 100, 200 and 300 are boss floors. Floors 60, 100, 130, 160, 200 and 300 reward a familiar; one you already have pays its fragments instead. Floors 100 and 200 open new exploring areas, and dispatch areas open at their original floors. Auto mode unlocks after floor 30, as in the original.</p><p>Local and flagged: battles use Everkai’s combat engine (Speed order, up to 15 rounds, Rage fills by 25 when attacking or hit, higher remaining Health wins, ties lose). Enemy familiars attack and use Rage strikes but not their own skills, and have a local 5% critical chance. Team formation bonuses and Endless Mode (which opens after floor 200 in the original) are not built. Auto climbs at most 10 floors a tap.</p></details></section>;
}
