import {Button} from '@/components/ui/button';
import {cardStyle,cardRarity,rarityIcon} from '@/lib/ui-sprites.mjs';
import {familiarById} from '@/lib/familiars.mjs';
import {EXPLORE,EXPLORE_AREAS,CATCH_ITEMS,RARITY_NAMES,exploreState,staminaAt,areaUnlocked,explorePet,catchChance,encounterPool} from '@/lib/familiar-explore.mjs';
import {towerFloorOf} from '@/lib/familiar-supplies.mjs';
const mins=(ms:number)=>{const m=Math.ceil(ms/60000);return m>=60?`${Math.floor(m/60)}h ${m%60}m`:`${m}m`};
export default function FamiliarExplorePanel({game,action,locked}:any){
 const now=Date.now(),e=exploreState(game),tank=staminaAt(e,now),area=EXPLORE_AREAS.find((a:any)=>a.id===e.area)!,c=e.encounter,floor=towerFloorOf(game);
 const pet=c?familiarById(c.pet)!:null,info=c?explorePet(c.pet):null,owned=c?!!game.familiars?.[c.pet]:false;
 const free=e.items.Item_PetExploreBuff_04>0;
 const total=Object.values(EXPLORE.gradeWeights).reduce((n:number,w:any)=>n+w,0) as number;
 return <section className="familiar-tower familiar-explore" aria-label="Familiar exploring"><h4 className="bond-ribbon">Exploring</h4>
 <div className="bond-progress"><span>Stamina</span><progress value={tank.stamina} max={EXPLORE.energy.max} aria-label="Exploration stamina"/><b>{tank.stamina}/{EXPLORE.energy.max}</b></div>
 <p className="item-status">{tank.next?`+1 stamina in ${mins(tank.next-now)} · one point every 90 minutes`:'Stamina is full.'}</p>
 <nav className="business-actions" aria-label="Exploring areas">{EXPLORE_AREAS.map((a:any)=><Button key={a.id} variant={a.id===e.area?'default':'outline'} disabled={locked||!!c||a.id===e.area||!areaUnlocked(game,a.id)} onClick={()=>action('exploreArea',a.id)}>{a.name}{areaUnlocked(game,a.id)?'':` · tower floor ${a.unlock}`}</Button>)}</nav>
 {c&&pet&&info?<article className="tower-floor"><h4>{c.sp?'Shining ':''}{RARITY_NAMES[info.grade]} · {pet.name}</h4>
  <div className="framed-card explore-monster" style={cardStyle(pet.rarity) as any} aria-hidden="true"><span>{rarityIcon(cardRarity(pet.rarity))&&<img src={rarityIcon(cardRarity(pet.rarity))!} alt=""/>}</span><strong>{pet.name}</strong></div>
  <p>{owned?'Already contracted: a new contract pays '+info.pieces+' fragments.':'Not yet contracted.'}{c.mustCatch?` This first meeting succeeds by attempt ${c.mustCatch}.`:''}</p>
  <div className="bond-progress"><span>Alertness</span><progress value={c.alert} max={info.alertMax} aria-label="Alertness"/><b>{c.alert}/{info.alertMax}</b></div>
  <p className="item-status">A failed contract raises Alertness by 30-40. At {info.alertMax} it flees{info.tears?` and leaves ${info.tears} Familiar Tears`:''}.</p>
  <div className="business-actions">{CATCH_ITEMS.map((k:any)=>{const count=k.grade===1?Infinity:e.items[k.item];return <Button key={k.grade} variant={k.grade===1?'default':'outline'} disabled={locked||count<1} onClick={()=>action('exploreCatch',null,k.grade)}>{k.name} · {catchChance(c.pet,k.grade)/100}% · {count===Infinity?'∞':count}</Button>})}</div>
  <div className="business-actions"><Button variant="outline" disabled={locked||c.alert<=0||c.soothed>=EXPLORE.soothe.useMax||e.items.Item_PetPacify1<1} onClick={()=>action('exploreSoothe')}>Soothe with Ordinary Mochi · -30 · {e.items.Item_PetPacify1} left · {EXPLORE.soothe.useMax-c.soothed} uses</Button><Button variant="outline" disabled={locked} onClick={()=>action('exploreLeave')}>Leave it</Button></div>
 </article>:<article className="tower-floor"><h4>{area.name}</h4><p>{area.text}</p>
  <p className="item-status">Explored {e.steps[area.id]} times here. Events: monster 40% · lost item 50% · Luck Flower 10%.</p>
  <Button disabled={locked||(!free&&tank.stamina<area.cost)} onClick={()=>action('exploreStep')}>{free?'Explore · free (Special Potion)':`Explore · ${area.cost} stamina`}</Button></article>}
 {e.last&&<p className="tower-reward" role="status">{e.last.text}</p>}
 <details className="rules-note"><summary>Monsters in {area.name}</summary><ul>{[4,3,2,1].map(g=>{const pool=encounterPool(game,area,g);return <li key={g}><b>{RARITY_NAMES[g]} · {Math.round((EXPLORE.gradeWeights as any)[g]/total*1000)/10}%</b>: {pool.map((id:string)=>`${familiarById(id)?.name}${game.familiars?.[id]?' ✓':''}`).join(', ')}</li>})}</ul>{area.ownedOnly.some((id:string)=>!game.familiars?.[id])&&<p>Appears only once contracted elsewhere: {area.ownedOnly.filter((id:string)=>!game.familiars?.[id]).map((id:string)=>familiarById(id)?.name).join(', ')} (a Familiar Tower reward).</p>}</details>
 <details className="rules-note"><summary>Your exploring items</summary><ul>{Object.entries(e.items).filter(([,n])=>(n as number)>0).map(([id,n])=><li key={id}>{(EXPLORE.itemNames as any)[id]} ×{n as number}{(EXPLORE.itemText as any)[id]?` · ${(EXPLORE.itemText as any)[id]}`:''}{['Item_PetRefresh1','Item_PetRefresh2'].includes(id)?' · kept for Metamorphosis, not built yet':''}{id==='Item_PetExploreRunCoin'?' · the Familiar Shop is not built yet':''}</li>)}{!Object.values(e.items).some(n=>(n as number)>0)&&<li>None yet. Basic Contracts are unlimited.</li>}</ul>{Object.keys(e.pieces).length>0&&<p>Fragments: {Object.entries(e.pieces).map(([id,n])=>`${familiarById(id)?.name} ${n}`).join(', ')}. Kept for stars; star costs still use class-up items.</p>}</details>
 <details className="rules-note"><summary>Exploring rules and what is measured</summary><p>From the original tables: three areas opened by Familiar Tower floors 0, 100 and 200; 1 stamina per explore, 20 held, one point every 90 minutes; events weighted 40% monster, 50% lost item, 10% Luck Flower; monster rarity weighted N 33.5%, R 47%, SR 15%, SSR 4.5%; each familiar’s shining chance; contract success by contract grade and rarity (Basic Contract N 70%, R 10%, SR 7.2%, SSR 3.1% and unlimited; Advanced 100/80/40/10%; Super always succeeds); Alertness +30-40 per failure until 100, when the monster flees and leaves Familiar Tears; Ordinary Mochi lowers Alertness by 30, up to 3 times per monster; the early scripted meetings in each area; lost item and Luck Flower rewards; a familiar you already have pays its fragments.</p><p>Local and flagged: every roll uses a random sequence stored in your save, so reloading cannot change an outcome. A scripted first meeting is read as succeeding by its listed attempt. The four buff items are used up by the next event they apply to, and Track Identification adds 500 to the SSR weight. Leaving a monster is an Everkai button. Not built: Incense, the Familiar Shop, Energy Drinks, auto-explore and the SSR wish.</p></details>
 <p className="item-status">Tower floor {floor} cleared.</p>
 </section>;
}
