import {familiarSupplies,suppliesWaiting,trainingCost,starCost} from '@/lib/familiar-supplies.mjs';
import FamiliarTowerPanel from './familiar-tower-panel';
import FamiliarNodePanel from './familiar-node-panel';
import PanelPages from './panel-pages';
import RosterLanding from './roster-landing';
import {useState} from 'react';
import {cardStyle,cardRarity,rarityIcon} from '@/lib/ui-sprites.mjs';
import {Button} from '@/components/ui/button';
import {FAMILIARS,familiarById,familiarStats,familiarStage,familiarCap} from '@/lib/familiars.mjs';
export default function FamiliarPanel({game,action,locked}:any){
 const [id,setId]=useState(FAMILIARS[0].id),pet=familiarById(id)!,progress=game.familiars?.[id],stats=familiarStats(id,progress||{level:1,stars:0}),supplies=familiarSupplies(game),waiting=suppliesWaiting(game,Date.now());
 // Companions land on the roster too, matching Family and Fellows. No album: OriginalAlbum covers
 // Hero and Wife only. Familiars carry no portrait, so RosterPicker falls back to the rarity card.
 const [browse,setBrowse]=useState(true);
 if(browse)return <RosterLanding kind="Companions" entries={FAMILIARS} owned={game.familiars||{}} selected={id}
  status={(x:string)=>game.familiars?.[x]?`Lv. ${game.familiars[x].level}`:'Not joined'}
  summary={<span>{FAMILIARS.filter(p=>game.familiars?.[p.id]).length} welcomed</span>}
  onSelect={(x:string)=>{setId(x);setBrowse(false)}}/>;
 return <section className="family-detail familiar-detail"><Button className="collection-open" variant="outline" onClick={()=>setBrowse(true)}>‹ Companions roster</Button><header className="familiar-hero"><div className="framed-card" style={cardStyle(pet.rarity) as any} aria-hidden="true"><span>{rarityIcon(cardRarity(pet.rarity))&&<img src={rarityIcon(cardRarity(pet.rarity))!} alt=""/>}</span><strong>{pet.name}</strong>{progress&&<small>Lv. {progress.level}</small>}</div><div><h3>{pet.name}</h3><p>{pet.rarity} · {pet.type}</p></div></header><div className="family-stats"><div><span>Attack</span><strong>{stats.ATK.toLocaleString()}</strong></div><div><span>Health</span><strong>{stats.HP.toLocaleString()}</strong></div><div><span>Speed</span><strong>{stats.SPD.toLocaleString()}</strong></div></div>
 {progress?<PanelPages labels={['Training','Fellow bond','Tower']}><><p>Level {progress.level} / {familiarCap(id)} · Stage {familiarStage(progress.level)} · {progress.stars} stars</p><p className="item-status">{supplies.levelUp.toLocaleString()} level-up items · {supplies.classUp.toLocaleString()} class-up items</p>{(()=>{const next=progress.level<familiarCap(id)?trainingCost(progress.level,progress.level+1):null,star=starCost(progress.stars);return <><div className="business-actions"><Button disabled={locked||!next||next.levelUp>supplies.levelUp||next.classUp>supplies.classUp} onClick={()=>action('trainFamiliar',id,1)}>Train +1{next?` · ${next.levelUp.toLocaleString()} level-up${next.classUp?` + ${next.classUp.toLocaleString()} class-up`:''}`:''}</Button><Button variant="outline" disabled={locked||!next||next.levelUp>supplies.levelUp||next.classUp>supplies.classUp} onClick={()=>action('trainFamiliar',id,10)}>Train up to 10</Button></div><Button disabled={locked||star===null||star>supplies.classUp} onClick={()=>action('starFamiliar',id)}>Add star{star!==null?` · ${star} class-up`:''}</Button></>})()}<div className="bond-progress"><span>Tower income</span><b>{waiting.hours?`${waiting.levelUp.toLocaleString()} + ${waiting.classUp.toLocaleString()} waiting`:familiarSupplies(game).since===null?'Clear floor 1':'Next full hour'}</b></div><Button variant="outline" disabled={locked||!(waiting.levelUp||waiting.classUp)} onClick={()=>action('collectFamiliarSupplies')}>Collect tower items</Button></><FamiliarNodePanel game={game} id={id} action={action} locked={locked}/><FamiliarTowerPanel game={game} action={action} locked={locked}/></PanelPages>:<Button disabled={locked} onClick={()=>action('adoptFamiliar',id)}>Welcome {pet.name} · Free</Button>}
 <Button variant="outline" disabled={locked||Object.keys(game.familiars||{}).length===FAMILIARS.length} onClick={()=>action('adoptFamiliars')}>Welcome all familiars · Free</Button><details className="rules-note"><summary>About familiar progression</summary><p>These base stats and level, stage and star calculations follow The Ascended’s public familiar calculator. Welcoming a familiar is free. Training costs the original’s level-up items per level and class-up items at each new stage, both earned from the Familiar Tower each hour and held for up to 24 hours. Your 12 tower floors pay the income of the original’s floors 25 to 300. Stars cost class-up items, a local choice, because the original’s star item is not identified. A bound familiar gives its Fellow nothing at stage 1, then a ninth of its bonus per stage up to the full bonus at stage 10. A separate 12-floor sandbox Tower is playable; original combat skills, enemy tables and acquisition costs remain unverified. Newer familiars may postdate the APK. Explicitly activated nodes benefit the bound Fellow and therefore roster-based business earnings; training alone does not activate nodes.</p></details></section>
}
