import {useState} from 'react';
import RosterLanding from './roster-landing';
import GiftPanel from './gift-panel';
import CharacterScreen from './character-screen';
import WardrobePanel from './wardrobe-panel';
import {wardrobeAppearance} from '@/lib/wardrobe.mjs';
import FamilyGalleryPanel from './family-gallery-panel';
import {availableDateEnergy,tonicReserve} from '@/lib/tonics.mjs';
import FamilyArtStage from './family-art-stage';
import {dateReward} from '@/lib/dating.mjs';
import {fishingDateBonus} from '@/lib/fishing.mjs';
import CharacterSkillGuide from './character-skill-guide';
import CharacterShowcase from './character-showcase';
import BlessingPanel from './blessing-panel';
import FathomPanel from './fathom-panel';
import CharacterScene from './character-scene';
import ConsumableShelf from './consumable-shelf';
import BondPanel from './bond-panel';
import PanelPages from './panel-pages';
import {Button} from '@/components/ui/button';
import {FAMILY} from '@/lib/catalog.mjs';
import {energyCap,blessingCost,familyBonus,ENERGY_RECOVERY_MS} from '@/lib/progression.mjs';
import {relationRequired} from '@/lib/school.mjs';
export default function FamilyPanel({game,action,selected,onSelect,locked,onReadStory}:any){const person=wardrobeAppearance(game,FAMILY.find(f=>f.id===selected)||FAMILY[0]),member=game.family[person.id];
 // Family lands on its roster too, matching Fellows and the original. The flag is local because this
 // panel already receives selected/onSelect, so page.tsx needs no new state.
 const [browse,setBrowse]=useState(true);
 if(browse)return <RosterLanding kind="Family" album="Wife" family entries={FAMILY} owned={game.family} selected={selected}
  status={(id:string)=>game.family[id]?`Intimacy ${game.family[id].intimacy}`:'Not joined'}
  summary={<span>{Object.values(game.family).reduce((n:number,f:any)=>n+f.intimacy,0).toLocaleString()} total Intimacy</span>}
  onSelect={(id:string)=>{onSelect(id);setBrowse(false)}}/>;
 return <CharacterScreen person={person} onPrevious={()=>onSelect(FAMILY[(FAMILY.findIndex(f=>f.id===person.id)+FAMILY.length-1)%FAMILY.length].id)} onNext={()=>onSelect(FAMILY[(FAMILY.findIndex(f=>f.id===person.id)+1)%FAMILY.length].id)} stats={member?[{label:'Intimacy',value:member.intimacy},{label:'Blessing Power',value:member.blessingPower}]:[]} subtitle={member?`Intimacy ${member.intimacy} · Blessing Power ${member.blessingPower}`:'A new companion'} collection={<Button className="collection-open" variant="outline" onClick={()=>setBrowse(true)}>‹ Family roster</Button>}>
 <PanelPages key={person.id} popup personName={person.name} labels={['Profile','Dates','Gifts','More gifts','Bonds','Blessings','Fathoms','Pictures','Wardrobe']}><article className="family-detail"><small>YOUR FAMILY</small><h2>{person.name}</h2><CharacterSkillGuide key={person.id+'-skill-guide'} id={person.id} game={game} action={action} locked={locked}/> <details className="rules-note"><summary>About these rules</summary><p className="balance-note">Gift effects and the separate family stats follow the readable game data. Auto-date uses available whole Energy and preserves the fractional remainder; its original rank/VIP unlock is waived. Starting stats, welcome method, date rewards, one-minute Energy recovery, shop prices and the +1% skill are local balance. Pupil formulas and relationship thresholds are local balance; Documented family–Fellow pairings are available under Bonds; their bonus strength remains local balance.</p></details><CharacterScene key={person.id+'-encounter'} id={person.id} locked={locked} onRead={onReadStory}/><p>{person.title} · {person.description||'No biography was recovered for this character.'}</p>{member?<><div className="family-stats"><div><span>Intimacy</span><strong>{member.intimacy}</strong></div><div><span>Blessing Power</span><strong>{member.blessingPower}</strong></div><div><span>Blessing Points</span><strong>{member.points}</strong></div></div><p className="management-hint">Blessing Power increases points earned on dates. Intimacy increases pupil graduation earnings. Improve relationships to raise the Intellect of future pupils.</p><div className="blessing-row"><h3>Relationship · Tier {member.relationship}</h3><p>Future pupil Intellect: {member.relationship*10}. Intimacy is not consumed.</p><Button disabled={locked||member.relationship>=5||member.intimacy<relationRequired(member.relationship)} onClick={()=>action('relationship',person.id)}>{member.relationship>=5?'Current tier cap reached':`Improve relationship · requires ${relationRequired(member.relationship)} Intimacy`}</Button></div><div className="blessing-row"><h3>Family skill · Lv. {member.skill}</h3><p>+{member.skill}% village earnings · {Math.round(familyBonus(game)*100)}% from all family skills</p><Button disabled={locked||member.skill>=20||member.points<blessingCost(member)} onClick={()=>action('bless',person.id)}>{member.skill>=20?'Fully upgraded':`Improve skill · ${blessingCost(member)} points`}</Button></div></>:<p>Welcome family members to begin gifts and dates.</p>}<p className="small-note">{Object.keys(game.family).length===FAMILY.length?'Everyone is home.':`${person.name} can be invited at the Recruit counter in Drakenberg.`}</p><p className="small-note">Family join at the Recruit counter in Drakenberg, paid for with habit-earned currency.</p></article>
 <section><h2>Family dates</h2><div className="family-date-layout"><div className="family-date-setting"><FamilyArtStage key={person.id+'-date'} person={person} context="date"/><p>{person.name}</p></div><div className="family-date-actions"><strong>Natural Energy {Math.floor(game.energy)} / {energyCap(game)}</strong><small>Tonic reserve: {tonicReserve(game)} · spent first</small><small>{game.energy>=energyCap(game)?'Fully recovered':`Next Energy in ${Math.ceil((1-game.energy%1)*ENERGY_RECOVERY_MS/1000)}s`}</small><Button disabled={locked||availableDateEnergy(game)<1||!Object.keys(game.family).length} onClick={()=>action('date',null,Math.random())}>Random date · 1 Energy</Button><Button variant="outline" disabled={locked||availableDateEnergy(game)<1||!Object.keys(game.family).length} onClick={()=>action('autoDate')}>Auto-date · Use {availableDateEnergy(game)} Energy</Button></div></div><p className="small-note">Selected portrait: {person.name}. Random dates can choose any joined Family member.</p>{member&&<p>If dated, {person.name} gains {dateReward(game,person.id).credited.toLocaleString()} points ({member.blessingPower.toLocaleString()} base{dateReward(game,person.id).credited<dateReward(game,person.id).total?' · storage capped':''}).</p>}<details className="rules-note"><summary>Date bonuses and Energy</summary><p>Fishing combination bonus: +{fishingDateBonus(game)}% Blessing Points. Each date uses 1 Energy, even at the point storage cap. Spend points on blessings to make room.</p></details>
</section><GiftPanel game={game} person={person} action={action} locked={locked}/><ConsumableShelf game={game} action={action} locked={locked} familyId={person.id}/><BondPanel game={game} id={person.id} action={action} locked={locked}/><BlessingPanel game={game} id={person.id} action={action} locked={locked}/><FathomPanel game={game} id={person.id} action={action} locked={locked}/><FamilyGalleryPanel key={person.id} game={game} person={person} action={action} locked={locked}/><WardrobePanel key={person.id} game={game} person={person} action={action} locked={locked}/></PanelPages>
 </CharacterScreen>}