import FarmTradePanel from './farm-trade-panel';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import PanelPages from './panel-pages';
import {FARM_PLANTS,farmPlant,farmGrowthKnowledge,farmHarvestPlan,FARM_YIELD,farmYieldLevel,FARM_MAX_PLOTS,farmPlotCost,farmPlantLevel,farmUpgradeCost,farmPlantRise} from '@/lib/farm.mjs';
export default function FarmPanel({game,action,locked}:any){
 const [plot,setPlot]=useState(0),[plant,setPlant]=useState(FARM_PLANTS[0].id),f=game.farm;
 if(!f)return <section><h2>Magic Farm</h2><p>Sow magical plants, water them, gather harvests and use Knowledge to reclaim more land.</p><Button disabled={locked} onClick={()=>action('openFarm')}>Open Magic Farm · Free</Button></section>;
 // Harvest level is the plant's own bought level now, not a picker: SimGame3PlantUpgrade charges
 // upgradeCost for every step of the ladder, and the level-3 rows carry none because 3 is terminal.
 const harvestLevel=farmPlantLevel(f,plant),upgradeCost=farmUpgradeCost(f,plant),rise=farmPlantRise(f,plant)!,selectedPlan=farmHarvestPlan(plant,harvestLevel)!;
 const plotCost=farmPlotCost(f.plots.length);
 const selected=Math.min(plot,f.plots.length-1),growing=f.plots[selected],p=farmHarvestPlan(growing?.plant||plant,growing?(growing.harvestLevel??1):harvestLevel)!,ready=growing&&growing.readyAt<=game.lastAt;
 return <section><h2>Magic Farm</h2><p>{f.knowledge.toLocaleString()} Knowledge · {f.plots.length}/{FARM_MAX_PLOTS} plots</p><PanelPages labels={['Garden','Orders','Alraune','Harvests','Land','Rules']}><><label htmlFor="farm-plot">Plot</label><NativeSelect id="farm-plot" value={selected} onChange={e=>setPlot(Number(e.target.value))}>{f.plots.map((row:any,n:number)=><NativeSelectOption key={n} value={n}>Plot {n+1} · {row?row.readyAt<=game.lastAt?'Ready':farmPlant(row.plant)?.name:'Empty'}</NativeSelectOption>)}</NativeSelect>
 {growing?<><h3>{p.name} · Harvest level {growing.harvestLevel??1}</h3><p>{ready?'Ready to harvest':`${Math.ceil((growing.readyAt-game.lastAt)/1000)} seconds remaining`} · {p.amount} plants</p><div className="business-actions"><Button disabled={locked||ready||growing.watered} onClick={()=>action('waterFarm',selected)}>Water · +10 Knowledge</Button><Button disabled={locked||!ready} onClick={()=>action('harvestFarm',selected)}>Harvest · +{farmGrowthKnowledge(p)} Knowledge</Button></div></>:<><label htmlFor="farm-seed">Seeds</label><NativeSelect id="farm-seed" value={plant} onChange={e=>setPlant(e.target.value)}>{FARM_PLANTS.map(p=><NativeSelectOption key={p.id} value={p.id}>{p.name}</NativeSelectOption>)}</NativeSelect><h4>Harvest level {harvestLevel}{upgradeCost===null?' · highest':''}</h4><Button disabled={locked||upgradeCost===null||f.knowledge<upgradeCost} onClick={()=>action('upgradePlant',plant)}>{upgradeCost===null?'Fully upgraded':`Upgrade to level ${harvestLevel+1} · ${upgradeCost.toLocaleString()} Knowledge`}</Button><details><summary>Compare harvest schedules</summary>{[1,2,3].map(n=>{const plan=farmHarvestPlan(plant,n)!;const step=farmUpgradeCost({plantLevels:{[plant]:n}},plant);return <p key={n}>Level {n}: {plan.amount} plants in {plan.seconds/60} minutes · {(plan.amount*60/plan.seconds).toFixed(2)} per minute{step===null?' · terminal':` · ${step.toLocaleString()} Knowledge to the next level`}</p>})}<p>The original charges SimGame3PlantUpgrade&rsquo;s upgradeCost for every step; level 3 is terminal and carries no cost. Each plant keeps its level permanently.</p></details><p>{p.seconds/60} minutes · Harvest {p.amount} · Growth Knowledge {farmGrowthKnowledge(p)}</p><p className="small-note item-status">Table effect at this level: all {rise.type} Building Earnings +{rise.percent}% — recorded from the original, not yet applied to income.</p><Button disabled={locked} onClick={()=>action('sowFarm',selected,{plant,level:harvestLevel})}>Sow free seeds · +10 Knowledge</Button></>}</><FarmTradePanel game={game} action={action} locked={locked} kind="orders"/><FarmTradePanel game={game} action={action} locked={locked} kind="exchange"/><><NativeSelect aria-label="Harvest collection" value={plant} onChange={e=>setPlant(e.target.value)}>{FARM_PLANTS.map(p=><NativeSelectOption key={p.id} value={p.id}>{p.name} · {f.harvests[p.id]||0}</NativeSelectOption>)}</NativeSelect><h3>{farmPlant(plant)?.name} · Harvest level {harvestLevel}</h3><p>{f.harvests[plant]||0} harvested · {selectedPlan.amount} per harvest in {selectedPlan.seconds/60} minutes</p>
 {/* The ladder is repeated here because the Garden only offers it while the selected plot is EMPTY,
     and a plant's level is a permanent purchase rather than a per-sowing choice. */}
 <Button disabled={locked||upgradeCost===null||f.knowledge<upgradeCost} onClick={()=>action('upgradePlant',plant)}>{upgradeCost===null?'Harvest level 3 · highest':`Upgrade to harvest level ${harvestLevel+1} · ${upgradeCost.toLocaleString()} Knowledge`}</Button>
 <p className="small-note item-status">All {rise.type} Building Earnings +{rise.percent}% at this level — the original&rsquo;s own risePercent, not yet applied to income.</p>
 <p>Deliver stored crops through Local orders to obtain Morning Dew.</p></><><p>{f.plots.length} of {FARM_MAX_PLOTS} plots reclaimed. {game.crystals.toLocaleString()} crystals available.</p><Button disabled={locked||plotCost===null||game.crystals<plotCost} onClick={()=>action('expandFarm')}>{plotCost===null?`All ${FARM_MAX_PLOTS} plots open`:`Reclaim plot ${f.plots.length+1} · ${plotCost.toLocaleString()} crystals`}</Button><details className="rules-note"><summary>About these rules</summary><p>SimGame3Farmland has 40 plots: the first three are free (isBaseUnlock), the rest are priced in item 4 — the original&rsquo;s Diamond, which Everkai maps to crystals — starting at 500, rising by 500 a plot to 10,000, then flat 10,000 from plot 23 on. 275,000 crystals opens all forty. Reclaiming still gives back 10 Knowledge, which is local policy.</p></details>
 {/* The Magic Tree had no control: farmYieldUpgrade was dispatched nowhere in the app, so the
     201-level ladder (+5% village earnings each, to +1000%) could never be climbed. */}
 <h3>Magic Tree · Level {farmYieldLevel(f)}</h3>
 <p>+{FARM_YIELD[farmYieldLevel(f)].percent}% village earnings from every building{FARM_YIELD[farmYieldLevel(f)].consume===undefined?' · fully grown':` · next level +${FARM_YIELD[farmYieldLevel(f)+1].percent}%`}</p>
 <Button disabled={locked||FARM_YIELD[farmYieldLevel(f)].consume===undefined||f.knowledge<FARM_YIELD[farmYieldLevel(f)].consume!} onClick={()=>action('farmYieldUpgrade')}>
  {FARM_YIELD[farmYieldLevel(f)].consume===undefined?'Fully grown':`Grow the Magic Tree · ${FARM_YIELD[farmYieldLevel(f)].consume!.toLocaleString()} Knowledge`}</Button>
 <p className="small-note">The original&rsquo;s farm NPC level, which adds buildingYieldPercent to every building. Deterministic — no rolls.</p></><details className="rules-note"><summary>About these rules</summary><p>Three harvest levels use times and yields verified 117/117 against the original SimGame3PlantUpgrade table. Each step of the ladder now costs that table&rsquo;s own upgradeCost — 30 to 110 for level 1 to 2, and 2,000 to 5,000 for level 2 to 3 — charged in Knowledge, because upgradeCost carries no currency id and Everkai already reads the identically shaped SimGame3Yield.consume as Knowledge. A plant keeps its level permanently and every crop of it grows on that schedule. APK rules give 10 Knowledge for sowing, watering and reclaiming, plus 2 per growth minute. This sandbox credits whole growth minutes at harvest, allows one watering per crop and free seeds. Plants mature while away. Local orders exchange one harvest for 5 Dew; Alraune exchanges 5 Dew for one matching essence with a local +1 Aptitude effect. These order quantities, rewards and effects are local policy, not recovered original formulas. Soil and Money Tree remain unimplemented. Each plant level also carries a per-business-type earnings bonus (risePercent, +25% to +200%, verified 117/117); it is shown above but not yet added to income, because the table does not say how the seven or eight plants of a type combine.</p></details></PanelPages></section>;
}
