import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {FARM_ESSENCES,farmOrder,farmTrade,essencePlan} from '@/lib/farm-trade.mjs';
import {farmPlant} from '@/lib/farm.mjs';
import {fellowById} from '@/lib/catalog.mjs';
export default function FarmTradePanel({game,action,locked,kind}:any){
 const [slot,setSlot]=useState(0),[essence,setEssence]=useState(FARM_ESSENCES[0].id),[fellow,setFellow]=useState('');const f=game.farm,t=farmTrade(f),order=farmOrder(f,slot)!,e=FARM_ESSENCES.find(x=>x.id===essence)!,workers=Object.keys(game.fellows).filter(id=>fellowById(id)?.type===e.type),selected=workers.includes(fellow)?fellow:workers[0];
 if(kind==='orders')return <><h3>Local crop orders</h3><p>{t.dew} Magic Morning Dew · {t.completed.reduce((a:number,b:number)=>a+b,0)} delivered</p><NativeSelect aria-label="Crop order" value={slot} onChange={event=>setSlot(Number(event.target.value))}>{[0,1,2].map(n=><NativeSelectOption key={n} value={n}>Order {n+1} · {farmPlant(farmOrder(f,n)!.plant)?.name}</NativeSelectOption>)}</NativeSelect><h3>{farmPlant(order.plant)?.name}</h3><p>Deliver {order.quantity} · In storage {f.harvests[order.plant]||0}</p><Button disabled={locked||(f.harvests[order.plant]||0)<order.quantity||t.dew>1e9-5} onClick={()=>action('deliverFarmOrder',slot,order.key)}>Deliver crops · +5 Dew</Button><p className="small-note">Local orders use one harvest per delivery. Exchange Dew with Alraune for Fellow training.</p></>;
 return <><h3>Alraune’s exchange</h3><p>{t.dew} Magic Morning Dew</p><NativeSelect aria-label="Alraune essence" value={essence} onChange={event=>setEssence(event.target.value)}>{FARM_ESSENCES.map(e=><NativeSelectOption key={e.id} value={e.id}>{e.name} · {e.type}</NativeSelectOption>)}</NativeSelect><p>{t.essences[essence]||0} owned · Local effect: Aptitude +1</p><Button disabled={locked||!essencePlan(game,essence,'buy').count} onClick={()=>action('buyFarmEssence',essence)}>Exchange · 5 Dew</Button><div className="business-actions">{([5,'max'] as const).map(n=>{const p=essencePlan(game,essence,'buy',n);return <Button key={n} variant="outline" disabled={locked||!p.count} onClick={()=>action('buyFarmEssence',essence,n)}>Exchange {n} · {p.count} essences · {p.cost} Dew</Button>})}</div><NativeSelect aria-label="Essence Fellow" value={selected||''} onChange={event=>setFellow(event.target.value)}>{!workers.length&&<NativeSelectOption value="">Recruit a matching Fellow first</NativeSelectOption>}{workers.map(id=><NativeSelectOption key={id} value={id}>{fellowById(id)?.name} · Aptitude {game.fellows[id].aptitude}</NativeSelectOption>)}</NativeSelect><Button disabled={locked||!selected||!(t.essences[essence]>0)||game.fellows[selected]?.aptitude>=1000} onClick={()=>action('useFarmEssence',selected,essence)}>Use essence · Aptitude +1</Button><div className="business-actions">{([5,'max'] as const).map(n=>{const p=essencePlan(game,essence,'use',n,selected);return <Button key={n} variant="outline" disabled={locked||!p.count} onClick={()=>action('useFarmEssence',selected,{essence,amount:n})}>Use {n} · {p.cost} essences · +{p.gain} Aptitude</Button>})}</div><p className="small-note">Essence types follow the original descriptions; price and +1 effect are sandbox balance.</p></>;
}
