import FarmTradePanel from './farm-trade-panel';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import PanelPages from './panel-pages';
import {FARM_PLANTS,farmPlant,farmGrowthKnowledge,farmHarvestPlan,FARM_YIELD,farmYieldLevel,FARM_MAX_PLOTS,farmPlotCost,farmPlantLevel,farmUpgradeCost,farmPlantRise,farmPlantRecord} from '@/lib/farm.mjs';
export default function FarmPanel({game,action,locked}:any){
 const [plot,setPlot]=useState(0),[plant,setPlant]=useState(FARM_PLANTS[0].id),f=game.farm;
 if(!f)return <section><h2>Magic Farm</h2><p>Sow magical plants, water them, gather harvests and use Knowledge to reclaim more land.</p><Button disabled={locked} onClick={()=>action('openFarm')}>Open Magic Farm · Free</Button></section>;
 // Harvest level is the plant's own earned level now, not a picker: the original qualifies each step
 // on that plant's lifetime harvest record, and the level-3 rows carry none because 3 is terminal.
 const harvestLevel=farmPlantLevel(f,plant),needed=farmUpgradeCost(f,plant),record=farmPlantRecord(f,plant),rise=farmPlantRise(f,plant)!,selectedPlan=farmHarvestPlan(plant,harvestLevel)!;
 const canUpgrade=needed!==null&&record>=needed;
 const plotCost=farmPlotCost(f.plots.length);
 const selected=Math.min(plot,f.plots.length-1),growing=f.plots[selected],p=farmHarvestPlan(growing?.plant||plant,growing?(growing.harvestLevel??1):harvestLevel)!,ready=growing&&growing.readyAt<=game.lastAt;
 return <section><h2>Magic Farm</h2><p>{f.knowledge.toLocaleString()} Knowledge · {f.plots.length}/{FARM_MAX_PLOTS} plots</p><PanelPages labels={['Garden','Orders','Alraune','Harvests','Land','Rules']}><><label htmlFor="farm-plot">Plot</label><NativeSelect id="farm-plot" value={selected} onChange={e=>setPlot(Number(e.target.value))}>{f.plots.map((row:any,n:number)=><NativeSelectOption key={n} value={n}>Plot {n+1} · {row?row.readyAt<=game.lastAt?'Ready':farmPlant(row.plant)?.name:'Empty'}</NativeSelectOption>)}</NativeSelect>
 {growing?<><h3>{p.name} · Harvest level {growing.harvestLevel??1}</h3><p>{ready?'Ready to harvest':`${Math.ceil((growing.readyAt-game.lastAt)/1000)} seconds remaining`} · {p.amount} plants</p><div className="business-actions"><Button disabled={locked||ready||growing.watered} onClick={()=>action('waterFarm',selected)}>Water · +10 Knowledge</Button><Button disabled={locked||!ready} onClick={()=>action('harvestFarm',selected)}>Harvest · +{farmGrowthKnowledge(p)} Knowledge</Button></div></>:<><label htmlFor="farm-seed">Seeds</label><NativeSelect id="farm-seed" value={plant} onChange={e=>setPlant(e.target.value)}>{FARM_PLANTS.map(p=><NativeSelectOption key={p.id} value={p.id}>{p.name}</NativeSelectOption>)}</NativeSelect><h4>Harvest level {harvestLevel}{needed===null?' · highest':` · ${record.toLocaleString()}/${needed.toLocaleString()} harvested`}</h4><Button disabled={locked||!canUpgrade} onClick={()=>action('upgradePlant',plant)}>{needed===null?'Highest harvest level':canUpgrade?`Raise to harvest level ${harvestLevel+1}`:`Harvest ${(needed-record).toLocaleString()} more to reach level ${harvestLevel+1}`}</Button><details><summary>Compare harvest schedules</summary>{[1,2,3].map(n=>{const plan=farmHarvestPlan(plant,n)!;const step=farmUpgradeCost({plantLevels:{[plant]:n}},plant);return <p key={n}>Level {n}: {plan.amount} plants in {plan.seconds/60} minutes · {(plan.amount*60/plan.seconds).toFixed(2)} per minute{step===null?' · terminal':` · ${step.toLocaleString()} total harvested to reach the next level`}</p>})}<p>The original qualifies each step on that plant&rsquo;s lifetime harvest record, not on a currency — nothing is spent. Level 3 is terminal. Each plant keeps its level permanently.</p></details><p>{p.seconds/60} minutes · Harvest {p.amount} · Growth Knowledge {farmGrowthKnowledge(p)}</p><p className="small-note item-status">Table effect at this level: all {rise.type} Building Earnings +{rise.percent}% — recorded from the original, not yet applied to income.</p><Button disabled={locked} onClick={()=>action('sowFarm',selected,{plant,level:harvestLevel})}>Sow free seeds · +10 Knowledge</Button></>}</><FarmTradePanel game={game} action={action} locked={locked} kind="orders"/><FarmTradePanel game={game} action={action} locked={locked} kind="exchange"/><><NativeSelect aria-label="Harvest collection" value={plant} onChange={e=>setPlant(e.target.value)}>{FARM_PLANTS.map(p=><NativeSelectOption key={p.id} value={p.id}>{p.name} · {f.harvests[p.id]||0}</NativeSelectOption>)}</NativeSelect><h3>{farmPlant(plant)?.name} · Harvest level {harvestLevel}</h3><p>{f.harvests[plant]||0} in store · {record.toLocaleString()} harvested in all · {selectedPlan.amount} per harvest in {selectedPlan.seconds/60} minutes</p>
 {/* The ladder is repeated here because the Garden only offers it while the selected plot is EMPTY,
     and a plant's level is a permanent purchase rather than a per-sowing choice. */}
 <Button disabled={locked||!canUpgrade} onClick={()=>action('upgradePlant',plant)}>{needed===null?'Harvest level 3 · highest':canUpgrade?`Raise to harvest level ${harvestLevel+1}`:`Harvest ${(needed-record).toLocaleString()} more to reach level ${harvestLevel+1}`}</Button>
 <p className="small-note item-status">All {rise.type} Building Earnings +{rise.percent}% at this level — the original&rsquo;s own risePercent, not yet applied to income.</p>
 <p>Deliver stored crops through Local orders to obtain Morning Dew.</p></><><p>{f.plots.length} of {FARM_MAX_PLOTS} plots reclaimed. {f.knowledge.toLocaleString()} Knowledge available.</p><Button disabled={locked||plotCost===null||f.knowledge<plotCost} onClick={()=>action('expandFarm')}>{plotCost===null?`All ${FARM_MAX_PLOTS} plots open`:`Reclaim plot ${f.plots.length+1} · ${plotCost.toLocaleString()} Knowledge`}</Button><details className="rules-note"><summary>About these rules</summary><p>SimGame3Field has twelve plots. Plot 1 comes with the farm; the other eleven cost 100, 300, 600, 3,000, 3,000, 3,000, 3,000, 4,000, 5,000, 5,000 and 10,000 Knowledge — 37,000 for all twelve. Reclaiming gives back 10 Knowledge, which is the original&rsquo;s own rule, not local policy.</p></details>
 {/* The Magic Tree had no control: farmYieldUpgrade was dispatched nowhere in the app, so the
     201-level ladder (+5% village earnings each, to +1000%) could never be climbed. */}
 <h3>Magic Tree · Level {farmYieldLevel(f)}</h3>
 <p>+{FARM_YIELD[farmYieldLevel(f)].percent}% village earnings from every building{FARM_YIELD[farmYieldLevel(f)].consume===undefined?' · fully grown':` · next level +${FARM_YIELD[farmYieldLevel(f)+1].percent}%`}</p>
 <Button disabled={locked||FARM_YIELD[farmYieldLevel(f)].consume===undefined||f.knowledge<FARM_YIELD[farmYieldLevel(f)].consume!} onClick={()=>action('farmYieldUpgrade')}>
  {FARM_YIELD[farmYieldLevel(f)].consume===undefined?'Fully grown':`Grow the Magic Tree · ${FARM_YIELD[farmYieldLevel(f)].consume!.toLocaleString()} Knowledge`}</Button>
 <p className="small-note">The original&rsquo;s farm NPC level, which adds buildingYieldPercent to every building. Deterministic — no rolls.</p></><details className="rules-note"><summary>About these rules</summary><p>Three harvest levels use times and yields verified 117/117 against the original SimGame3PlantUpgrade table. Each step is earned, not bought: the original qualifies it on how much of that plant you have harvested in all — 30 to 110 for level 1 to 2, and 2,000 to 5,000 for level 2 to 3 — and spends nothing. A plant keeps its level permanently and every crop of it grows on that schedule. APK rules give 10 Knowledge for sowing, watering and reclaiming, plus 2 per growth minute. This sandbox credits whole growth minutes at harvest, allows one watering per crop and free seeds. Plants mature while away. Local orders exchange one harvest for 5 Dew; Alraune exchanges 5 Dew for one matching essence with a local +1 Aptitude effect. These order quantities, rewards and effects are local policy, not recovered original formulas. Soil and Money Tree remain unimplemented, as do the Mole Family automations SimGame3Field unlocks alongside plots. Each plant level also carries a per-business-type earnings bonus (risePercent, +25% to +200%, verified 117/117): the original sums it across every obtained plant of that type, but Everkai does not add it to income yet.</p></details></PanelPages></section>;
}
