import {tonicReserve,tonicCount} from '@/lib/tonics.mjs';
import ElixirUse from './elixir-use';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {WISH_POOL,WISH_RECRUITS,fountainState,transferable,fairyAvailable,fairyClaims} from '@/lib/fountain.mjs';
export default function FountainPanel({game,action,locked,onBag,onRoster}:any){
 const [tab,setTab]=useState('wish'),[item,setItem]=useState('Lottery_10'),[person,setPerson]=useState('hero_102'),[page,setPage]=useState(0);const f=fountainState(game),r=WISH_POOL.find(r=>r.id===item)!,p=WISH_RECRUITS.find(p=>p.id===person)!,last=f.history.at(-1);const run=(a:string,target:any=null,count:any=null)=>action(a,target,{seq:f.seq,count});
 return <section className="treasure-panel"><h2>Fountain of Wishes</h2><nav className="panel-pages" aria-label="Fountain pages">{[['wish','Wish'],['rewards','Rewards'],['recruit','Recruit']].map(([id,name])=><Button key={id} variant="outline" aria-pressed={tab===id} onClick={()=>setTab(id)}>{name}</Button>)}</nav>
 {tab==='wish'&&<><p>{f.bottles} Fairy Bottles · {f.total} Fairies released</p><div className="business-actions"><Button disabled={locked||f.bottles<1} onClick={()=>{setPage(0);run('wishDraw',null,1)}}>Wish 1 · 1 bottle</Button><Button disabled={locked||f.bottles<9} onClick={()=>{setPage(0);run('wishDraw',null,10)}}>Wish 10 · 9 bottles</Button><Button variant="outline" disabled={locked||f.bottles+100>1e6} onClick={()=>run('wishSupply')}>Prepare 100 bottles · Free sandbox</Button></div>{last&&<article className="school-card"><h3>Saved wish results</h3>{last.rewards.slice(page*4,page*4+4).map((x:any,i:number)=><p key={i}>{x.quantity} × {WISH_POOL.find(r=>r.id===x.id)?.name}</p>)}{last.rewards.length>4&&<Button variant="outline" onClick={()=>setPage((page+1)%Math.ceil(last.rewards.length/4))}>More results · {page+1}/{Math.ceil(last.rewards.length/4)}</Button>}<Button variant="outline" onClick={()=>setTab('rewards')}>Use earned rewards</Button></article>}<article className="school-card"><h3>Fairy milestone rewards</h3><p>{fairyAvailable(game)} ready · {fairyClaims(game).length} claimed · {500-f.total%500} wishes to next</p><p>1 Acquaint Stone per 500 wishes</p><div className="business-actions"><Button disabled={locked||!fairyAvailable(game)||(f.ledger.Lottery_4||0)>=1e6} onClick={()=>run('wishFairyClaim',null,1)}>Claim 1 Fairy reward</Button><Button variant="outline" disabled={locked||!fairyAvailable(game)||(f.ledger.Lottery_4||0)+fairyAvailable(game)>1e6} onClick={()=>run('wishFairyClaim',null,'all')}>Claim all Fairy rewards</Button></div></article></>}
 {tab==='rewards'&&<><label>Earned item<select className="potion-select" aria-label="Fountain reward" value={item} onChange={e=>setItem(e.target.value)}>{WISH_POOL.map(r=><option key={r.id} value={r.id}>{r.name} · {f.ledger[r.id]||0}</option>)}</select></label><p>{f.ledger[item]||0} {r.name} saved at the fountain.</p>{item==='Lottery_9'?<article className="school-card"><h3>Tonic Energy reserve</h3><p>{tonicReserve(game)} / 30 reserved · natural Energy {game.energy.toFixed(2)}</p><div className="business-actions">{[1,5,'max'].map(q=>{const n=tonicCount(game,q);return <Button key={q} disabled={locked||!n} onClick={()=>run('useFountainTonic',item,q)}>Use {q==='max'?`max (${n})`:q} · +{n*3} reserve</Button>})}<Button variant="outline" onClick={()=>onRoster('family',Object.keys(game.family)[0]||'wife_2')}>Visit Family dates</Button></div><p className="small-note">Each tonic gives 3 Energy. Our local reserve stores it separately and is spent before natural Energy on manual and auto dates. Natural recovery continues; no fractional Energy is discarded. Original overflow rules are unverified.</p></article>:['Lottery_6','Lottery_13'].includes(item)?<ElixirUse key={item} game={game} ledger={item} action={action} locked={locked} onRoster={onRoster}/>:transferable(r)?<div className="business-actions"><Button disabled={locked||!f.ledger[item]||game.inventory[r.itemId!]+f.ledger[item]>1e6} onClick={()=>run('wishTransfer',item)}>Move earned items to Bag</Button><Button variant="outline" onClick={onBag}>Open Bag</Button></div>:item==='Lottery_8'?<><p>20 fragments → 1 Acquaint Stone</p><Button disabled={locked||(f.ledger[item]||0)<20||(f.ledger.Lottery_4||0)>=1e6} onClick={()=>run('wishSynthesize')}>Combine 20 fragments</Button></>:item==='Lottery_4'?<Button onClick={()=>setTab('recruit')}>Choose an acquaintance</Button>:<p className="small-note">Kept in your save. This item's original use is not yet implemented.</p>}</>}
 {tab==='recruit'&&<><p>{f.ledger.Lottery_4||0} Acquaint Stones · selected recruitment</p><label>Acquaintance<select className="potion-select" aria-label="Acquaintance" value={person} onChange={e=>setPerson(e.target.value)}>{['fellows','family'].map(kind=><optgroup key={kind} label={kind==='fellows'?'Bonds Between Elites · Fellows':'Fated Acquaintance · Family'}>{WISH_RECRUITS.filter(p=>p.kind===kind).map(p=><option key={p.id} value={p.id}>{p.name} · {p.cost} {p.cost===1?'stone':'stones'}{game[p.kind][p.id]?' · Joined':''}</option>)}</optgroup>)}</select></label><article className="school-card"><h3>{p.name}</h3><p className="small-note">{p.category}</p><p>{game[p.kind][person]?'Already joined — existing progress kept':`Recruit with ${p.cost} Acquaint Stones`}</p><div className="business-actions"><Button disabled={locked||!!game[p.kind][person]||(f.ledger.Lottery_4||0)<p.cost} onClick={()=>run('wishRecruit',person)}>Recruit · {p.cost} {p.cost===1?'stone':'stones'}</Button><Button variant="outline" onClick={()=>onRoster(p.kind,person)}>Visit {p.kind==='fellows'?'Fellows':'Family'}</Button></div></article><p className="small-note">Eight Fellows and eight Family have named community recruitment costs matched to their original identities. These costs are not version-matched APK formulas. The full roster also remains available through free sandbox recruitment.</p></>}
 <details className="rules-note"><summary>Wish odds and source rules</summary>{WISH_POOL.map(r=><p key={r.id}>{r.name} ×{r.quantity} · {r.weight/10}%</p>)}<p>Costs, twelve displayed probabilities and Fairy counts come from readable APK rules. The offline random stream, free bottles and storage limits are local. No pity is added. The one-stone Fairy milestone reward, fragment synthesis and selected recruit costs come from community references. Previously accumulated milestones remain available until explicitly claimed. Draws and all rewards save together before display; reloading keeps the same results.</p></details></section>
}
