import EncounterAdvice from './encounter-advice';
import {Button} from '@/components/ui/button';
import {FRONTIER,frontierState,frontierKey,frontierPower} from '@/lib/frontier.mjs';
import {fellowById} from '@/lib/catalog.mjs';
export default function FrontierPanel({game,action,locked}:any){
 const f=frontierState(game),e=FRONTIER[f.cleared],a=f.active;
 if(game.adventure.cleared<30)return <article><h2>The Frontier</h2><p>Clear the first30 stages to unlock three more local chapters: scouting, relay encounters and a citadel siege. Bring three trained Fellows.</p></article>;
 return <article><small>LOCAL CAMPAIGN CONTINUATION</small><h2>The Frontier · {f.cleared}/12 cleared</h2><p>Chapter6 Trailwatch {Math.min(4,f.cleared)}/4 · Chapter7 Relay Pass {Math.max(0,Math.min(4,f.cleared-4))}/4 · Chapter8 Citadel {Math.max(0,f.cleared-8)}/4</p>{e?<><h3>Chapter {e.chapter} · {e.name} {((e.id-1)%4)+1}</h3><p>{e.waves.length} waves · {e.distinct?'Each wave needs a different leader.':'Party coordination followed by a solo scout.'}</p><p>Victory: {e.rewards.gold.toLocaleString()} gold, {e.rewards.xp.toLocaleString()} EXP, {e.rewards.pearls} Skill Pearls, {e.rewards.scrolls} Skill Scrolls{e.rewards.tokens?`, plus chapter milestone: ${e.rewards.tokens} Limit-Break Tokens and ${e.rewards.crystals} crystals`:''}.</p>{a?<><h3>Wave {a.wave+1}/{e.waves.length}</h3><p>{e.waves[a.wave].mode==='party'?'Combined party Power':'Leader’s individual Power'} · Need {e.waves[a.wave].power.toLocaleString()} · {e.waves[a.wave].type} leader gives +25%.</p>{a.party.map((id:string)=>{const power=frontierPower(game,a,id),spent=e.distinct&&a.used.includes(id);return <div className="training-option" key={id}><span>{fellowById(id)?.name} · {power.toLocaleString()} effective Power{spent?' · Already led':''}</span><Button disabled={locked||spent||power<e.waves[a.wave].power} onClick={()=>action('frontierWave',id,frontierKey(a))}>Lead with {fellowById(id)?.name}</Button></div>})}<EncounterAdvice game={game} action={action} locked={locked} frontier/><p>Train between waves if needed. This encounter keeps its starting party. Failed power checks spend nothing.</p><Button variant="outline" disabled={locked} onClick={()=>action('retreatFrontier')}>Retreat · Entry fee lost</Button></>:<><p>Entry {e.entry.toLocaleString()} gold. Choose three Fellows on the Party page before starting.</p><Button disabled={locked||game.gold<e.entry||game.adventure.party.length!==3} onClick={()=>action('startFrontier',e.id)}>Start Frontier encounter {e.id}</Button></>}</>:<><h3>Frontier complete</h3><p>All three chapter milestones earned. Your original cleared-stage patrols remain available for repeatable EXP.</p></>}<p className="small-note">Spend EXP on levels, pearls on Aptitude/talents, scrolls on skills and milestone tokens on limit breaks. Each encounter rewards once, only after its final wave.</p><details><summary>Local encounter rules</summary><p>These chapters, wave patterns, type bonus and all numeric balance are reconstructed. They are not recovered original encounters. Progress saves after each wave. Rewards and final clear save together; full resource storage pauses the final wave. Retreating restarts the encounter and requires another entry fee. The first30 stages and patrols keep their previous rules.</p></details></article>;
}
