import {originalProgression} from '@/lib/original-progression.mjs';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {enterpriseState,enterpriseBreakdown,operationSlots,employeeCap} from '@/lib/businesses.mjs';
import {staffingStatus,staffingPlan} from '@/lib/staffing.mjs';
import {fellowById} from '@/lib/catalog.mjs';
import {wardrobeAppearance} from '@/lib/wardrobe.mjs';
import PaidStaffing from './paid-staffing';
import InnPanel from './inn-panel';
import {SystemMenus} from './panel-pages';
export default function InnBusinessScene({game,action,locked,management}:any){
 const [panel,setPanel]=useState<string|null>(null),b=enterpriseState(game).Building_101,rates=enterpriseBreakdown(game,'Building_101'),paid=b&&originalProgression(game)?staffingStatus('Building_101',b):null;
 return <section className="inn-business-scene" aria-label="Inn business"><div className="inn-exterior"><h2>Inn</h2><img src="./assets/ui-scenes/Scene_MainCity_Building_2_1_New.png" alt="Inn exterior"/></div><div className="inn-operation"><div className="inn-summary"><div><span>Employee earnings</span><strong>{(rates?.employees||0).toLocaleString()} /s</strong></div><div><span>Employees</span><strong>{(b?.employees||0).toLocaleString()}</strong></div></div>{!b?<Button disabled={locked} onClick={()=>action('openEnterprise','Building_101')}>Open Inn · Free sandbox</Button>:<><div className="inn-hire-row">{[1,10].map(n=>{const plan=paid?staffingPlan(game,'Building_101',n):null;return <Button key={n} disabled={locked||(paid?(!plan?.count||(plan?.cost||0)>game.gold):(b.employees>=employeeCap))} onClick={()=>action(paid?'paidStaffHire':'hireEmployees','Building_101',n)}>Hire {paid?plan?.count:Math.max(0,Math.min(n,employeeCap-b.employees))} · {paid?(plan?.cost||0).toLocaleString()+' Gold':'Free'}</Button>})}</div><div className="inn-quality-row"><span>{paid?'Quality '+paid.quality:'Building growth'}</span><Button className="advancement-button" onClick={()=>setPanel('Growth')}>Improve</Button></div><div className="inn-operators"><span>Operating Fellows · {b.fellows.length}/{operationSlots(b.employees)}</span><div>{b.fellows.map((id:string)=>{const p=wardrobeAppearance(game,fellowById(id));return <button key={id} aria-label={'Manage '+p.name} onClick={()=>setPanel('Operation')}><img src={'./assets/'+p.portrait} alt={p.name}/></button>})}<Button variant="outline" onClick={()=>setPanel('Operation')}>Assign</Button></div></div></>}
 <nav className="inn-bottom-actions" aria-label="Inn activities">{['Growth','Service','Operation'].map(name=><Button key={name} variant="outline" onClick={()=>setPanel(name)} disabled={!b&&name==='Growth'}>{name}</Button>)}</nav></div><Dialog open={!!panel} onOpenChange={open=>{if(!open)setPanel(null)}}><DialogContent className="stage-detail-sheet"><DialogTitle>Inn · {panel}</DialogTitle><DialogDescription>Manage your Inn</DialogDescription><SystemMenus name="">{panel==='Growth'&&b?<PaidStaffing game={game} id="Building_101" action={action} locked={locked}/>:panel==='Service'?<InnPanel game={game} action={action} locked={locked}/>:management}</SystemMenus></DialogContent></Dialog></section>;
}
