import InnGuestsPanel from './inn-guests-panel';
import {innRating,innStaminaCap,nextInnRating,innServingGains,innServingCoverage} from '@/lib/inn-progression.mjs';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import PanelPages from './panel-pages';
import {INN_STATIONS,INN_DISHES,innRecipeReady} from '@/lib/inn.mjs';
export default function InnPanel({game,action,locked}:any){
 const [station,setStation]=useState('1'),[recipe,setRecipe]=useState('57');const i=game.inn;
 const st=INN_STATIONS.find(s=>s.id===station)!,dish=INN_DISHES.find(d=>d.id===recipe)!;
 if(!i)return <section><h2>Inn service</h2><p>Build your kitchen, develop recipes and serve a queue of guests—even while offline.</p><Button disabled={locked||!game.enterprises?.Building_101} onClick={()=>action('openInnService')}>Open Inn service</Button>{!game.enterprises?.Building_101&&<p>Open the Inn in Original businesses first.</p>}</section>;
 const level=i.stations[station]||0;
 return <section><h2>Inn service</h2><div className="family-stats"><div><span>Guests served</span><strong>{i.served}</strong></div><div><span>Stamina</span><strong>{i.stamina}/{innStaminaCap(i)}</strong></div><div><span>Blueprints</span><strong>{i.blueprints}</strong></div></div>
 <p>Rating {innRating(i)} · Popularity {(i.popularity||0).toLocaleString()}{nextInnRating(i)?` / ${nextInnRating(i)?.toLocaleString()}`:' · Highest documented rating'}</p><PanelPages labels={['Reception','Kitchen','Recipes','Guests','Rules']}><>
 {i.queue?<><h3>Serving {INN_DISHES.find(d=>d.id===i.queue.dish)?.name}</h3><p>{i.queue.remaining} guests waiting · Next meal in {Math.max(0,Math.ceil((i.queue.nextAt-game.lastAt)/1000))}s</p><p>You can close the app. The queue will finish while you’re away.</p></>:<><label htmlFor="inn-menu">Guest order</label><NativeSelect id="inn-menu" value={i.menu.includes(recipe)?recipe:i.menu[0]||''} onChange={e=>setRecipe(e.target.value)}>{!i.menu.length&&<NativeSelectOption value="">Develop a recipe first</NativeSelectOption>}{i.menu.map((id:string)=><NativeSelectOption key={id} value={id}>{INN_DISHES.find(d=>d.id===id)?.name}</NativeSelectOption>)}</NativeSelect><div className="business-actions">{[1,5,10].map(n=><Button key={n} disabled={locked||!i.menu.length||i.stamina<n} onClick={()=>action('receiveInnGuests',i.menu.includes(recipe)?recipe:i.menu[0],n)}>Receive {n} · {n} stamina</Button>)}</div></>}
 <Button variant="outline" disabled={locked||i.stamina>=innStaminaCap(i)} onClick={()=>action('refillInnStamina')}>Refill stamina · Free sandbox</Button><p>Deposit: {i.deposit.toLocaleString()} gold</p><Button disabled={locked||!i.deposit||game.gold+i.deposit>1e9} onClick={()=>action('collectInnDeposit')}>Collect Inn earnings</Button><p className="small-note">10 seconds · 50 gold · 1 blueprint per guest.</p>
 </><><label htmlFor="inn-station">Kitchen station</label><NativeSelect id="inn-station" value={station} onChange={e=>setStation(e.target.value)}>{INN_STATIONS.map(s=><NativeSelectOption key={s.id} value={s.id}>{s.name} · {i.stations[s.id]?`Lv.${i.stations[s.id]}`:`${s.guests} guests to unlock`}</NativeSelectOption>)}</NativeSelect><h3>{st.name}</h3><p>Requires {st.guests} guests served · {level?`Level ${level}/30`:'Not built'}</p>{level?<Button disabled={locked||level>=30||i.blueprints<level} onClick={()=>action('upgradeInnStation',station)}>Upgrade · {level} blueprints</Button>:<Button disabled={locked||i.served<st.guests||game.gold<Number(station)*100} onClick={()=>action('buildInnStation',station)}>Build · {Number(station)*100} gold</Button>}</><>
 <label htmlFor="inn-recipe">Recipe book · {i.menu.length}/80 developed</label><NativeSelect id="inn-recipe" value={recipe} onChange={e=>setRecipe(e.target.value)}>{INN_DISHES.map(d=><NativeSelectOption key={d.id} value={d.id}>{d.name}{i.menu.includes(d.id)?' · Developed':''}</NativeSelectOption>)}</NativeSelect><h3>{dish.name}</h3><p>{dish.station?`${INN_STATIONS.find(s=>s.id===dish.station)?.name} level ${dish.level}`:`${dish.guests} guests served`}</p><p>Finesse: {i.finesse[recipe]||0} · Per serving: +{innServingGains(i,recipe).finesse} finesse{innServingCoverage(i,recipe).finesse?'':' (sandbox)'} · {innServingCoverage(i,recipe).popularity?`+${innServingGains(i,recipe).popularity} popularity`:'Popularity not documented'}</p><Button disabled={locked||i.menu.includes(recipe)||!innRecipeReady(i,dish)} onClick={()=>action('developInnRecipe',recipe)}>Develop recipe · Free sandbox</Button></><InnGuestsPanel game={game} action={action} locked={locked}/><p>Original rules support serial guest service, stamina, offline operation, gold-built stations, blueprint upgrades, recipe development, finesse and manually collected earnings. This sandbox uses local prices, 10-second meals, free stamina and selected guest orders. Recipe management tasks are waived. Station finesse and popularity gains now use the original full 30-level tables for all ten stations. Gains are fixed when receiving guests. Historical popularity is not guessed. Seven special-guest treasures are available through Guests; other gifts, Gratitude upgrades and dish bonus formulas still need complete data. Your existing village and Inn business earnings continue separately.</p></PanelPages></section>;
}
