import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {MILESTONES,playerRank,rankXP,energyCap} from '@/lib/progression.mjs';
import {GIFTS} from '@/lib/catalog.mjs';
import {giftIcon} from '@/lib/ui-sprites.mjs';
import AdventurePanel from './adventure-panel';
import {SystemMenus} from './panel-pages';
const groups:Record<string,string>={earn500:'Village',threeFellows:'Village',threeBusinesses:'Village',twoFamily:'Family',fiveGifts:'Family',threeDates:'Family',firstBlessing:'Family',clear5:'Progress',clear15:'Progress',aptitude15:'Village',graduate1:'Lifestyle'};
const destinations:Record<string,string>={earn500:'village',threeFellows:'fellows',threeBusinesses:'businesses',twoFamily:'family',fiveGifts:'family',threeDates:'family',firstBlessing:'family',aptitude15:'fellows',graduate1:'school'};
const icons:Record<string,string>={Village:'building',Family:'bonds',Progress:'mastery',Treasure:'relics',Lifestyle:'overview'};
export default function JourneyPanel({game,action,locked,onNavigate}:any){const [category,setCategory]=useState('Village'),[campaign,setCampaign]=useState(false),xp=rankXP(game);return <section className="achievement-screen"><div className="achievement-rank">Rank {playerRank(game)} · {xp} Rank EXP · Energy limit {energyCap(game)}</div><nav className="achievement-categories" aria-label="Achievement categories">{Object.keys(icons).map(name=><Button key={name} variant="outline" aria-pressed={category===name} onClick={()=>setCategory(name)}><img src={'./assets/ui-original/Icon_Achive_'+name+'.png'} alt=""/><span>{name}</span></Button>)}</nav><div className="achievement-rows">{MILESTONES.filter(m=>groups[m.id]===category).map(m=>{const claimed=game.claims.includes(m.id),progress=Math.min(m.goal,m.metric(game)),ready=progress>=m.goal;return <article className="achievement-row" key={m.id}><header><h3>{m.detail}</h3><strong>{Math.floor(progress).toLocaleString()}/{m.goal.toLocaleString()}</strong></header><div className="achievement-reward"><div><span>{m.reward.gold.toLocaleString()} Gold · {m.xp} EXP</span><div>{GIFTS.filter(g=>m.reward[g.id]).map(g=><span className="achievement-gift" key={g.id}><img src={giftIcon(g.id)!} alt={g.name}/><b>{m.reward[g.id]}</b></span>)}</div></div>{claimed?<Button disabled>Collected</Button>:ready?<Button disabled={locked} onClick={()=>action('claim',m.id)}>Claim</Button>:<Button className="advancement-button" disabled={!onNavigate&&!m.id.startsWith('clear')} onClick={()=>{if(m.id.startsWith('clear'))setCampaign(true);else onNavigate?.(destinations[m.id])}}>Go</Button>}</div></article>})}{!MILESTONES.some(m=>groups[m.id]===category)&&<p>No milestones in this category yet.</p>}</div><details className="achievement-rules"><summary>Milestone rules</summary><p>These eleven milestones, rewards and rank thresholds are the village’s local progression. Original achievement and daily-task chains are still being integrated. Each reward can be claimed once.</p></details><Dialog open={campaign} onOpenChange={setCampaign}><DialogContent className="stage-detail-sheet"><DialogTitle>Campaign milestones</DialogTitle><DialogDescription>Continue the local campaign</DialogDescription><SystemMenus name=""><AdventurePanel initialPage={1} game={game} action={action} locked={locked} onNavigate={onNavigate}/></SystemMenus></DialogContent></Dialog></section>}
