import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import PanelPages from './panel-pages';
import {fellowById} from '@/lib/catalog.mjs';
import {mineState,mineToday,minePlan,mineShopPlan,MINE_ROWS} from '@/lib/mine-clearance.mjs';
export default function MineClearancePanel({game,action,locked,onBag,onFellow}:any){
 const [selected,setSelected]=useState('hero_15'),m=mineState(game),today=mineToday(game),plan=minePlan(game,selected),shop=mineShopPlan(game),enemy=MINE_ROWS[today.cleared],remaining=enemy?enemy.cumulativePower-today.progress:0;
 const run=(a:string,count:any=1)=>action(a,selected,{seq:m.seq,day:today.day,count});
 return <section><p className="small-note">Private Mine Clearance · eight source encounters · local combat rules</p><PanelPages labels={['Clearance','Mine exchange','Mine records']}><>
 <h3>{enemy?`${today.cleared+1}/8 · ${enemy.name}`:'Today’s mine is clear'}</h3>
 <p>{enemy?`${remaining.toLocaleString()} Power remaining`:'All eight encounters paid once today. Return after the next UTC midnight.'}</p>
 <progress aria-label="Mine cleared encounters" max={8} value={today.cleared}/>
 <>{enemy?<><p>{today.used.length} Fellows deployed today · {Object.keys(game.fellows).length-today.used.length} available</p>
 <label htmlFor="mine-fellow">Deploy a Fellow</label><NativeSelect id="mine-fellow" value={selected} onChange={e=>setSelected(e.target.value)}>{Object.keys(game.fellows).map(id=><NativeSelectOption key={id} value={id}>{fellowById(id)?.name||id}{today.used.includes(id)?' · Resting':' · Ready'}</NativeSelectOption>)}</NativeSelect>
 <article className="school-card"><h4>{plan.power.toLocaleString()} Power</h4><p>{plan.allowed?plan.kills.length?`Clears ${plan.kills.length} encounters: ${plan.gold.toLocaleString()} gold, ${plan.fellowEXP.toLocaleString()} Fellow EXP and ${plan.coins} Mine Coins.`:`Deals ${(plan.after-plan.before).toLocaleString()} damage. No encounter reward yet; damage stays for your next Fellow.`:'This Fellow has already deployed, or the mine is clear.'}</p><Button disabled={locked||!plan.allowed} onClick={()=>run('mineDeploy')}>Deploy {fellowById(selected)?.name||'Fellow'} · once today</Button></article>
 <p className="small-note">One deployment per owned Fellow per UTC day. Damage carries through encounters. A weak attack still uses today’s deployment; another Fellow can continue. No Adventure, Date or Trading energy is spent.</p>
 <div className="business-actions"><Button variant="outline" onClick={()=>onFellow(selected)}>Train selected Fellow</Button><Button variant="outline" onClick={()=>onFellow('hero_54')}>Rani · recruitment & Stella</Button></div><p className="small-note">Need stronger Fellows? Rani’s existing free recruitment and Stella training provide a route into the mine. You choose whether to use those sandbox supplies.</p></>:<article className="school-card"><h4>Rewards saved</h4><p>Your encounters are complete for today. Open Mine exchange to spend earned Mine Coins on Magic Ore, or Mine records to review the result.</p><p>{m.coins.toLocaleString()} Mine Coins available</p></article>}</>
 </><><h3>{m.coins.toLocaleString()} Mine Coins</h3><p>Magic Ore · 300 Mine Coins each · {5-today.bought}/5 available today</p><div className="business-actions"><Button disabled={locked||shop.quantity<1} onClick={()=>run('mineExchange',1)}>Exchange 1 Ore · 300 coins</Button><Button disabled={locked||!shop.quantity} onClick={()=>run('mineExchange','max')}>Exchange max · {shop.quantity} Ore · {shop.paid} coins</Button><Button variant="outline" onClick={onBag}>Open Bag · Equipment</Button></div><p>Ore goes directly to Equipment for artifact upgrades. Previously recorded equipment investments and refunds are preserved.</p></><><h3>{m.history.length} deployments saved</h3>{m.history.at(-1)&&<article className="school-card"><h4>Latest · {fellowById(m.history.at(-1).owner)?.name}</h4><p>{m.history.at(-1).power.toLocaleString()} Power · {m.history.at(-1).kills.length} encounters defeated</p><p>{m.history.at(-1).gold.toLocaleString()} gold · {m.history.at(-1).fellowEXP.toLocaleString()} EXP · {m.history.at(-1).coins} Mine Coins</p></article>}<p>{m.exchanges.length} exchange receipts. All older results stay in your save.</p></></PanelPages>
 <details className="rules-note"><summary>Mine rules & sources</summary><p>Encounter Power and individual rewards, one Fellow deployment per day, and the Ore price come from readable rules and community reference revision6634. Direct Power damage, overflow and UTC reset are private rules. Each new day resets the route and participation; earned wallets and receipts remain. Clearing a monster grants its reward once that day, with no extra first-clear or replay reward. No random chests, guild helpers or online excavation are included.</p></details></section>;
}
