import PickStrip from './pick-strip';
import {wardrobeAppearance} from '@/lib/wardrobe.mjs';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import PanelPages from './panel-pages';
import {fellowById} from '@/lib/catalog.mjs';
import {mineState,mineToday,minePlan,mineShopPlan,MINE_ROWS,MINE_DEPTH,mineRowName,MINE_UNLOCK_RANK,mineUnlocked} from '@/lib/mine-clearance.mjs';
export default function MineClearancePanel({game,action,locked,onBag,onFellow}:any){
 const [selected,setSelected]=useState(()=>Object.keys(game.fellows)[0]),m=mineState(game),today=mineToday(game),plan=minePlan(game,selected),shop=mineShopPlan(game),enemy=MINE_ROWS[today.cleared],remaining=enemy?enemy.cumulativePower-today.progress:0;
 const run=(a:string,count:any=1)=>action(a,selected,{seq:m.seq,day:today.day,count});
 if(!mineUnlocked(game))return <section className="school-card frontier-locked"><h2>Mine Clearance</h2><p>The mines open at player rank {MINE_UNLOCK_RANK}. Their first guardian, Rock Baby, has {MINE_ROWS[0].power.toLocaleString()} health — train your Fellows through the campaign first.</p><div className="bond-progress"><span>Rank</span><progress value={game.opening?.rank||1} max={MINE_UNLOCK_RANK} aria-label="Player rank toward the mines"/><b>{game.opening?.rank||1}/{MINE_UNLOCK_RANK}</b></div></section>;
 return <section><details className="rules-note"><summary>About these rules</summary><p>Private Mine Clearance · {MINE_DEPTH} source encounters · local combat rules</p></details><PanelPages labels={['Clearance','Mine exchange','Mine records']}><>
 <h3>{enemy?`${today.cleared+1}/${MINE_DEPTH} · ${mineRowName(enemy)}`:'Today’s mine is clear'}</h3>
 <p>{enemy?`${remaining.toLocaleString()} Power remaining`:`All ${MINE_DEPTH} encounters paid once today. Return after the next UTC midnight.`}</p>
 <progress aria-label="Mine cleared encounters" max={MINE_DEPTH} value={today.cleared}/>
 <>{enemy?<><p>{today.used.length} Fellows deployed today · {Object.keys(game.fellows).length-today.used.length} available</p>
 <h4 className="pick-heading">Deploy a Fellow</h4><PickStrip label="Deploy a Fellow" value={selected} onChange={setSelected} items={Object.keys(game.fellows).sort((a,b)=>Number(today.used.includes(a))-Number(today.used.includes(b))).map(id=>{const p=wardrobeAppearance(game,fellowById(id));return {id,name:p?.name||id,img:p?.portrait||null,sub:today.used.includes(id)?'Resting':'Lv.'+game.fellows[id].level,muted:today.used.includes(id)}})}/>
 <article className="school-card"><h4>{plan.power.toLocaleString()} Power</h4><p>{plan.allowed?plan.kills.length?`Clears ${plan.kills.length} encounters: ${plan.gold.toLocaleString()} gold, ${plan.fellowEXP.toLocaleString()} Fellow EXP and ${plan.coins} Mine Coins.`:`Deals ${(plan.after-plan.before).toLocaleString()} damage. No encounter reward yet; damage stays for your next Fellow.`:'This Fellow has already deployed, or the mine is clear.'}</p><Button disabled={locked||!plan.allowed} onClick={()=>run('mineDeploy')}>Deploy {fellowById(selected)?.name||'Fellow'} · once today</Button></article>
 <p className="small-note">One deployment per owned Fellow per UTC day. Damage carries through encounters. A weak attack still uses today’s deployment; another Fellow can continue. No Adventure, Date or Trading energy is spent.</p>
 <div className="business-actions"><Button variant="outline" onClick={()=>onFellow(selected)}>Train selected Fellow</Button><Button variant="outline" onClick={()=>onFellow('hero_54')}>Rani · recruitment & Stella</Button></div><p className="small-note item-status">Need stronger Fellows? Rani’s existing free recruitment and Stella training provide a route into the mine. You choose whether to use those free supplies.</p></>:<article className="school-card"><h4>Rewards saved</h4><p>Your encounters are complete for today. Open Mine exchange to spend earned Mine Coins on Magic Ore, or Mine records to review the result.</p><p>{m.coins.toLocaleString()} Mine Coins available</p></article>}</>
 </><><h3>{m.coins.toLocaleString()} Mine Coins</h3><p>Magic Ore · 300 Mine Coins each · {5-today.bought}/5 available today</p><div className="business-actions"><Button disabled={locked||shop.quantity<1} onClick={()=>run('mineExchange',1)}>Exchange 1 Ore · 300 coins</Button><Button disabled={locked||!shop.quantity} onClick={()=>run('mineExchange','max')}>Exchange max · {shop.quantity} Ore · {shop.paid} coins</Button><Button variant="outline" onClick={onBag}>Open Bag · Equipment</Button></div><p>Ore goes directly to Equipment for artifact upgrades. Previously recorded equipment investments and refunds are preserved.</p></><><h3>{m.history.length} deployments saved</h3>{m.history.at(-1)&&<article className="school-card"><h4>Latest · {fellowById(m.history.at(-1).owner)?.name}</h4><p>{m.history.at(-1).power.toLocaleString()} Power · {m.history.at(-1).kills.length} encounters defeated</p><p>{m.history.at(-1).gold.toLocaleString()} gold · {m.history.at(-1).fellowEXP.toLocaleString()} EXP · {m.history.at(-1).coins} Mine Coins</p></article>}<p>{m.exchanges.length} exchange receipts. All older results stay in your save.</p></></PanelPages>
 <details className="rules-note"><summary>Mine rules & sources</summary><p>All {MINE_DEPTH} encounter Power values and their individual rewards are the original’s own highwayBoss table. The first eight also carry the English names a community page recorded; that page stopped at eight, so deeper guardians are listed by depth rather than given invented names. The Ore price comes from readable rules. Direct Power damage, overflow and UTC reset are private rules. Each new day resets the route and participation; earned wallets and receipts remain. Clearing a monster grants its reward once that day, with no extra first-clear or replay reward. No random chests, guild helpers or online excavation are included.</p></details></section>;
}
