import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {KEEPSAKES,museumState,museumBonus,acceptedKeepsakes} from '@/lib/museum.mjs';
export default function MuseumPanel({game,action,locked,onRelics}:any){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(0);
 const accepted=acceptedKeepsakes(game),owned=museumState(game),bonus=museumBonus(game),count=Object.keys(owned).length;
 const items=KEEPSAKES.filter(k=>k.name.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='bonuses'&&k.effect||filter==='owned'&&Object.hasOwn(owned,k.id)));
 const pages=Math.max(1,Math.ceil(items.length/2)),current=Math.min(page,pages-1);
 return <section><h2>Private Hall</h2>{onRelics&&<Button variant="outline" onClick={onRelics}>Visit excavated relics</Button>}<p>{count} / {KEEPSAKES.length} keepsakes collected · {accepted.length} accepted · {Object.values(owned).filter(Boolean).length} displayed</p>
 <p>Museum bonuses: +{bonus.aptitude} Fellow Aptitude for Power · +{bonus.basicPowerPercent}% basic Power · +{bonus.powerPercent}% Power</p>
 <p className="small-note">Hall 1 keepsakes pay once accepted and keep paying in storage; excavated relics are Hall 5 and 6 exhibits and pay only while displayed.</p>
 <div className="business-actions"><Button disabled={locked||count===KEEPSAKES.length} onClick={()=>action('claimMuseum')}>Daily keepsake · after a habit</Button><Button variant="outline" disabled={locked||accepted.length===count} onClick={()=>action('acceptMuseum')}>Accept collected keepsakes</Button><Button variant="outline" disabled={locked||!accepted.length} onClick={()=>action('displayMuseum')}>Display all</Button><Button variant="outline" disabled={locked||!count} onClick={()=>action('storeMuseum')}>Store all</Button></div>
 <Input aria-label="Find museum keepsakes" placeholder="Find a keepsake…" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/>
 <nav className="panel-pages" aria-label="Museum filters">{[['all','All'],['bonuses','With bonuses'],['owned','Collected']].map(([id,label])=><Button key={id} variant="outline" aria-pressed={filter===id} onClick={()=>{setFilter(id);setPage(0)}}>{label}</Button>)}</nav>
 {items.slice(current*2,current*2+2).map(k=><article className="school-card" key={k.id}><h3>{k.name}</h3><p>{k.effect?`+${k.effect.amount}${k.effect.stat==='aptitude'?' Aptitude to all Fellows':k.effect.stat==='basicPowerPercent'?'% basic Fellow Power':'% Fellow Power'}`:'Collection keepsake · no bonus'}</p><details><summary>Read the keepsake description</summary><p>{k.description}</p></details><Button disabled={locked} onClick={()=>action(!Object.hasOwn(owned,k.id)?'claimKeepsake':!accepted.includes(k.id)?'acceptKeepsake':'toggleKeepsake',k.id)}>{!Object.hasOwn(owned,k.id)?'Collect · daily, after a habit':!accepted.includes(k.id)?'Accept keepsake':owned[k.id]?'Store keepsake':'Display keepsake'}</Button></article>)}
 {!items.length&&<p>No keepsakes match this selection.</p>}
 <div className="business-actions"><Button variant="outline" disabled={!current} onClick={()=>setPage(current-1)}>Previous</Button><span>{current+1} / {pages}</span><Button variant="outline" disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Next</Button></div>
 <details className="rules-note"><summary>About Museum bonuses</summary><p>All 32 Hall 1 keepsakes now carry the effect the original gives them: each one resolves through its own Exhibit row to a SkillBase skill, which is either +2 Fellow Aptitude or +2% basic Fellow Power. Accepted bonuses remain when a keepsake is stored; display is cosmetic. In the original a keepsake arrives from a limited-time crossover milestone item, so Everkai rate-limits it instead: one keepsake a day, after a completed daily habit. Aptitude and basic Power bonuses apply before family bonuses; general Power applies afterward, and no Hall 1 keepsake uses it. Museum bonuses affect Power only. Exhibit levelling, awakening and duplicate rewards are not modelled; each keepsake records the original's per-level growth so nothing is lost.</p></details></section>;
}
