import CharacterScene from './character-scene';
import availability from '@/lib/roster-availability.mjs';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {FELLOWS,FAMILY} from '@/lib/catalog.mjs';
import {searchCharacters} from '@/lib/original-catalog.mjs';
import original from '@/lib/original-content.mjs';
const plain=(s:string)=>s.replace(/\[\/?(?:color|size|b|i)(?:=[^\]]*)?\]/g,'');
export default function OriginalAlbum({kind,onChoose}: {kind:'Hero'|'Wife',onChoose:(id:string)=>void}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[page,setPage]=useState(0),[selected,setSelected]=useState<any>(null),[mode,setMode]=useState('characters');
 const entries=searchCharacters(kind,query),playable=kind==='Hero'?FELLOWS:FAMILY,label=kind==='Hero'?'Fellow':'Family';
 const rules=original.rules.filter(r=>r.id.startsWith('Rule:text:'+kind+'_')).sort((a,b)=>Number(a.id.split('_').at(-1))-Number(b.id.split('_').at(-1)));
 const pages=Math.max(1,Math.ceil((mode==='characters'?entries.length:rules.length)/6)),current=Math.min(page,pages-1);
 return <><Button variant="outline" className="album-open" onClick={()=>setOpen(true)}><img src="./assets/ui/journey.webp" alt=""/>{label} album · {searchCharacters(kind).length}</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="game-modal album-modal" showCloseButton={false}><div className="modal-heading"><img src={'./assets/ui/'+(kind==='Hero'?'fellows':'family')+'.webp'} alt=""/><div><DialogTitle>{label} album</DialogTitle><DialogDescription>From the original game records</DialogDescription></div><DialogClose className="village-close" aria-label="Close album"><img src="./assets/ui/close.webp" alt=""/></DialogClose></div><div className="modal-body album-body">
 {selected?<article className="album-detail"><Button variant="outline" onClick={()=>setSelected(null)}>← Back to album</Button>{(()=>{const active=playable.find(f=>f.id===selected.id);return <>{active&&<img className="album-portrait" src={'./assets/'+active.art} alt={selected.fields.name}/>}<h2>{selected.fields.name}</h2><CharacterScene key={selected.id} id={selected.id}/><p>{plain(selected.fields.title||'')}</p><dl>{[['Race',selected.fields.race],['Occupation',selected.fields.occupation]].filter(([,v])=>v).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{plain(v)}</dd></div>)}</dl><p>{plain(selected.fields.introduce||selected.fields.info||'No biography in the recovered record.')}</p>{active?<Button onClick={()=>{onChoose(active.id);setOpen(false);setSelected(null)}}>Open {active.name}</Button>:<p className="album-status">{availability.find(r=>r.id===selected.id)?.status==='variant-only'?'Only variant artwork is verified; the base appearance is still pending.':'A verified base-character render is still missing.'} Original stats and unlock requirements also remain unverified.</p>}<details className="rules-note"><summary>Record details</summary><p>Names and biography are imported from the original English text. A record may describe unused or variant content. Rarity, affinities and numeric progression have not been recovered.</p><p>Original ID: {selected.source_id}</p></details></>})()}</article>:<><nav className="panel-pages" aria-label="Album pages">{['characters','rules'].map(m=><Button key={m} aria-pressed={mode===m} onClick={()=>{setMode(m);setPage(0)}}>{m==='characters'?'Characters':'Original rules'}</Button>)}</nav>{mode==='characters'?<><label htmlFor={'album-search-'+kind}>Find by name, title, race or occupation</label><Input id={'album-search-'+kind} type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}} placeholder="Search characters…"/><p className="album-count" role="status">{entries.length} records · {playable.length} currently playable</p><div className="album-grid">{entries.slice(current*6,current*6+6).map(c=><Button variant="outline" key={c.id} onClick={()=>setSelected(c)}><strong>{c.fields.name}</strong><span>{plain(c.fields.title||c.fields.race||'Character record')}</span><small>{playable.some(f=>f.id===c.id)?'Playable':'Album entry'}</small></Button>)}</div>{!entries.length&&<p>No matching characters. Try another name or clear the search.</p>}</>:<><p className="album-status">Original descriptions. Some features are still pending or use local balance in this sandbox.</p><div className="album-rules">{rules.slice(current*6,current*6+6).map(r=><p key={r.id}>{plain(r.en)}</p>)}</div></>}<nav className="album-pagination" aria-label="Album pagination"><Button variant="outline" disabled={current===0} onClick={()=>setPage(current-1)}>Previous</Button><span>{current+1} / {pages}</span><Button variant="outline" disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Next</Button></nav></>}
 </div></DialogContent></Dialog></>
}
