import {useState,Children,createContext,useContext,Fragment,type ReactNode} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogClose,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const SystemMenuContext=createContext('');
export function SystemMenus({name,children}:{name:string,children:ReactNode}){return <SystemMenuContext.Provider value={name}>{children}</SystemMenuContext.Provider>}
const icons:Record<string,string>={Profile:'overview',Overview:'overview',Level:'level',Dates:'bonds',Gifts:'gifts','More gifts':'gifts',Bonds:'bonds',Blessings:'rank',Pictures:'overview',Wardrobe:'relics',Skills:'mastery',Equipment:'relics',Stella:'rank',Welcome:'bonds','Original businesses':'building','Inn service':'building',Workshop:'building','Magic Farm':'building','Starter businesses':'building',Pupils:'bonds',Graduate:'rank',Opening:'overview',Sandbox:'gifts',Milestones:'rank',Familiars:'bonds',Museum:'relics',Keepsakes:'relics',Materials:'relics',Supplies:'gifts',Counter:'building','Brew & stock':'gifts','Recipe visitors':'bonds',Negotiate:'mastery',Exchange:'gifts',Records:'overview',Wish:'rank',Rewards:'gifts',Recruit:'bonds',Host:'building',Expedition:'building',Appraisal:'mastery','Relic collection':'relics'};
export default function PanelPages({labels,children,initialPage=0,popup=false,personName='Character',selectedPage,onPageChange}:{labels:string[],children:ReactNode,initialPage?:number,popup?:boolean,personName?:string,selectedPage?:number,onPageChange?:(page:number)=>void}){
 const facility=useContext(SystemMenuContext),systemPopup=!!facility&&!popup,title=systemPopup?facility:personName;
 const [page,setLocalPage]=useState(initialPage),[open,setOpen]=useState(systemPopup);const pages=Children.toArray(children),active=Math.min(selectedPage??page,Math.max(0,pages.length-1));
 const setPage=(next:number)=>{setLocalPage(next);onPageChange?.(next)};
 if(popup||systemPopup)return <div className={systemPopup?'system-menu':'character-menu'}><nav className={systemPopup?'system-action-dock':'character-action-dock'} aria-label={title+' actions'}>{labels.map((label,i)=><Button key={label} variant="outline" aria-haspopup="dialog" onClick={()=>{setPage(i);setOpen(true)}}><img src={'./assets/menu/'+(icons[label]||'overview')+'.png'} alt=""/><span>{label}</span></Button>)}</nav><Dialog open={open} onOpenChange={setOpen}><DialogContent className={'character-sheet'+(systemPopup?' system-sheet':'')} showCloseButton={false}><header className="character-sheet-heading"><div><DialogDescription>{title}</DialogDescription><DialogTitle>{labels[active]}</DialogTitle></div><DialogClose className="character-sheet-close" aria-label={'Back to '+title}>×</DialogClose></header><div className="character-sheet-body" key={active} tabIndex={0} aria-label={labels[active]+' details'}><SystemMenuContext.Provider value="">{pages[active]}</SystemMenuContext.Provider></div><footer className="character-sheet-footer"><Button variant="outline" disabled={active===0} onClick={()=>setPage(active-1)}>Previous</Button><span>{active+1} / {labels.length}</span><Button variant="outline" disabled={active===labels.length-1} onClick={()=>setPage(active+1)}>Next</Button></footer></DialogContent></Dialog></div>;
 return <div className="panel-book"><nav className="panel-pages" aria-label="Panel pages">{labels.map((label,i)=><Button key={label} variant="outline" aria-pressed={active===i} onClick={()=>setPage(i)}>{label}</Button>)}</nav><section key={active} aria-label={labels[active]} className="panel-page">{pages[active]}</section></div>
}

export function ActivityPages({options,value,onChange,children}:{options:string[][],value:string,onChange:(value:string)=>void,children:ReactNode}){
 const selected=Math.max(0,options.findIndex(([id])=>id===value));
 return <PanelPages labels={options.map(([,label])=>label)} selectedPage={selected} onPageChange={i=>onChange(options[i][0])}>{options.map(([id],i)=><Fragment key={id}>{i===selected?children:null}</Fragment>)}</PanelPages>;
}
