import {useState,Children,type ReactNode} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogClose,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const icons:Record<string,string>={Profile:'overview',Overview:'overview',Level:'level',Dates:'bonds',Gifts:'gifts','More gifts':'gifts',Bonds:'bonds',Blessings:'rank',Pictures:'overview',Wardrobe:'relics',Skills:'mastery',Equipment:'relics',Stella:'rank',Welcome:'bonds'};
export default function PanelPages({labels,children,initialPage=0,popup=false,personName='Character'}:{labels:string[],children:ReactNode,initialPage?:number,popup?:boolean,personName?:string}){
 const [page,setPage]=useState(initialPage),[open,setOpen]=useState(false);const pages=Children.toArray(children),active=Math.min(page,Math.max(0,pages.length-1));
 if(popup)return <div className="character-menu"><nav className="character-action-dock" aria-label={personName+' actions'}>{labels.map((label,i)=><Button key={label} variant="outline" aria-haspopup="dialog" onClick={()=>{setPage(i);setOpen(true)}}><img src={'./assets/menu/'+(icons[label]||'overview')+'.png'} alt=""/><span>{label}</span></Button>)}</nav><Dialog open={open} onOpenChange={setOpen}><DialogContent className="character-sheet" showCloseButton={false}><header className="character-sheet-heading"><div><DialogDescription>{personName}</DialogDescription><DialogTitle>{labels[active]}</DialogTitle></div><DialogClose className="character-sheet-close" aria-label={'Back to '+personName}>×</DialogClose></header><div className="character-sheet-body" key={active} tabIndex={0} aria-label={labels[active]+' details'}>{pages[active]}</div><footer className="character-sheet-footer"><Button variant="outline" disabled={active===0} onClick={()=>setPage(active-1)}>Previous</Button><span>{active+1} / {labels.length}</span><Button variant="outline" disabled={active===labels.length-1} onClick={()=>setPage(active+1)}>Next</Button></footer></DialogContent></Dialog></div>;
 return <div className="panel-book"><nav className="panel-pages" aria-label="Panel pages">{labels.map((label,i)=><Button key={label} variant="outline" aria-pressed={active===i} onClick={()=>setPage(i)}>{label}</Button>)}</nav><section key={active} aria-label={labels[active]} className="panel-page">{pages[active]}</section></div>
}
