import RaphaelProgress from './raphael-progress';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import PanelPages from './panel-pages';
import {RAPHAEL_FANS,RAPHAEL_ITEMS,stageState,stageDefinition,stageScore,stageTargets} from '@/lib/raphael.mjs';
export default function RaphaelPanel({game,action,locked,onBag}:any){
 const [selected,setSelected]=useState(12),[choice,setChoice]=useState('fan:1'),[moving,setMoving]=useState<number|null>(null);
 const r=stageState(game),score=stageScore(r.cells),p=r.cells[selected],d=p?stageDefinition(p.kind,p.id):null,targets=d?stageTargets(selected,d.effectTypeId):[];
 const [kind,id]=choice.split(':'),chosen=stageDefinition(kind,id);
 return <section className="raphael-panel"><div className="family-stats"><div><span>Encouragement</span><strong>{score.total.toLocaleString()}</strong></div><div><span>Best performance</span><strong>{r.best.toLocaleString()}</strong></div></div>
 <p>{moving===null?'Tap a square to arrange your support group.':'Tap a destination to move or swap.'}</p>
 <div className="raphael-grid" role="group" aria-label="Raphael support formation, five rows and five columns">{r.cells.map((cell:any,i:number)=>{const item=cell?stageDefinition(cell.kind,cell.id):null;return <Button key={i} variant="outline" className={`raphael-square ${i===selected?'selected':''} ${targets.includes(i)?'supported':''}`} aria-pressed={i===selected} aria-label={`Row ${Math.floor(i/5)+1}, column ${i%5+1}: ${item?item.name+', level '+cell.level:'empty'}`} disabled={locked} onClick={()=>{if(moving!==null){action('stageMove',moving,i);setMoving(null)}setSelected(i)}}><span>{item?item.name.split(' ').map((x:string)=>x[0]).join('').slice(0,3):'+'}</span><small>{cell?'Lv. '+cell.level:i+1}</small></Button>})}</div>
 <p><strong>{d?.name||`Square ${selected+1}`}</strong>{d?` · Supports ${d.effectSummary.toLowerCase()}`:' · Empty'}{p?.kind==='fan'?` · ${score.scores[selected].toLocaleString()} encouragement`:''}</p>
 <PanelPages labels={['Arrange','Improve','Perform','Event']}>
 <div><label htmlFor="stage-cast">Fan or support item</label><NativeSelect id="stage-cast" value={choice} disabled={locked} onChange={e=>setChoice(e.target.value)}>{RAPHAEL_FANS.map(f=><NativeSelectOption key={'fan:'+f.id} value={'fan:'+f.id}>{f.name}</NativeSelectOption>)}{RAPHAEL_ITEMS.map(f=><NativeSelectOption key={'item:'+f.id} value={'item:'+f.id}>Item · {f.name}</NativeSelectOption>)}</NativeSelect><p>{chosen?.effectSummary} · {kind==='fan'?'Fans can appear more than once.':'Only one copy of each support item; four items total.'}</p><div className="business-actions"><Button disabled={locked} onClick={()=>action('stagePlace',selected,{kind,id,level:1})}>{p?'Replace':'Place'} · Free</Button><Button variant="outline" disabled={locked||!p} onClick={()=>setMoving(moving===null?selected:null)}>{moving===null?'Move / swap':'Cancel move'}</Button><Button variant="outline" disabled={locked||!p} onClick={()=>action('stageRemove',selected)}>Remove</Button></div></div>
 <div><p>Choose an occupied square. Fan and support levels are free to adjust in this sandbox.</p><div className="business-actions"><Button variant="outline" disabled={locked||!p||p.level<=(d?.levelMin||1)} onClick={()=>action('stageLevel',selected,-1)}>Level −1</Button><Button disabled={locked||!p||p.level>=(d?.levelMax||1)} onClick={()=>action('stageLevel',selected,1)}>Level +1 · Free</Button></div></div>
 <div><p>Arrange your fans and support items to improve encouragement. Perform to record your best score.</p><Button disabled={locked||!r.cells.some((x:any)=>x?.kind==='fan')} onClick={()=>action('stagePerform')}>Perform</Button><p>{r.performances} performances · Your formation and best score save on this device.</p></div>
 <RaphaelProgress game={game} action={action} locked={locked} onBag={onBag}/></PanelPages><details className="rules-note"><summary>About this event</summary><p>Fan values, directional support and scoring follow The Ascended’s public Raphael’s Stage calculator. All 27 fans and eight items are freely available here. Event support runs now connect paid Stamina to a pinned milestone track and saved reward locker. Free practice records scores only. Original acquisition, Heat progression, prop costs, event shops and drop rewards remain unimplemented.</p></details></section>
}
