import {rarityIcon,countryIcon,petCardIcon} from '@/lib/ui-sprites.mjs';
import {useState,useEffect} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {filterRoster} from '@/lib/roster-filter.mjs';
export default function RosterPicker({entries,selected,onSelect,status,owned={},family=false,pageSize=null}:any){
 const size=pageSize??(family?2:3),[query,setQuery]=useState(''),[mode,setMode]=useState('all'),[country,setCountry]=useState('all'),[page,setPage]=useState(Math.max(0,Math.floor(entries.findIndex((f:any)=>f.id===selected)/size)));
 useEffect(()=>{const i=entries.findIndex((f:any)=>f.id===selected);if(i>=0){setQuery('');setMode('all');setPage(Math.floor(i/size))}},[selected,entries,size]);
 const matches=filterRoster(entries,query,mode,owned).filter((f:any)=>country==='all'||f.type===country),pages=Math.max(1,Math.ceil(matches.length/size)),current=Math.min(page,pages-1),kind=family?'Family':'Fellow';
 return <section className="roster-picker" aria-label={kind+' roster'}><div className="roster-search"><Input type="search" aria-label={'Search playable '+kind.toLowerCase()} placeholder={'Find a '+kind.toLowerCase()+'…'} value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/><NativeSelect aria-label="Show characters" value={mode} onChange={e=>{setMode(e.target.value);setPage(0)}}><NativeSelectOption value="all">Everyone</NativeSelectOption><NativeSelectOption value="owned">Joined</NativeSelectOption><NativeSelectOption value="new">Not joined</NativeSelectOption></NativeSelect></div>{!family&&<nav className="roster-type-filters" aria-label="Fellow types">{['all','Inspiring','Diligent','Brave','Informed','Unfettered'].map(type=><Button key={type} variant="ghost" aria-label={type==='all'?'All Fellow types':type} aria-pressed={country===type} onClick={()=>{setCountry(type);setPage(0)}}>{countryIcon(type)?<img src={countryIcon(type)!} alt=""/>:'All'}</Button>)}</nav>}<p className="roster-count" role="status">{matches.length} shown · {Object.keys(owned).length}/{entries.length} joined</p><div className={family?'family-roster':'roster'}>{matches.slice(current*size,(current+1)*size).map((f:any)=><Button key={f.id} variant="outline" className={'roster-tile '+(selected===f.id?'chosen':'')+(!owned[f.id]?' not-joined':'')} aria-pressed={selected===f.id} onClick={()=>onSelect(f.id)}>{f.portrait||f.art?<img src={'./assets/'+(f.portrait||f.art)} alt=""/>:<img className="roster-card-only" src={petCardIcon(f.rarity)||''} alt=""/>}<span className="roster-source-badges">{rarityIcon(f.rarity)&&<img src={rarityIcon(f.rarity)!} alt={f.rarity}/>} {countryIcon(f.type)&&<img src={countryIcon(f.type)!} alt={f.type}/>}</span><strong>{f.name}</strong><span>{[f.rarity,f.type].filter(Boolean).join(' · ')}</span><span>{status(f.id)}</span></Button>)}</div>{!matches.length&&<p className="roster-count">No matches. Try another search or show everyone.</p>}{pages>1&&<nav className="roster-pagination" aria-label="Roster pages"><Button variant="outline" disabled={current===0} onClick={()=>setPage(current-1)}>Previous</Button><span>{current+1} / {pages}</span><Button variant="outline" disabled={current===pages-1} onClick={()=>setPage(current+1)}>Next</Button></nav>}</section>
}
