import PickStrip from './pick-strip';
import {wardrobeAppearance} from '@/lib/wardrobe.mjs';
import {countryIcon} from '@/lib/ui-sprites.mjs';
import {pupilMilestone} from '@/lib/school-maturation.mjs';
import {innGiftSchoolBonus} from '@/lib/inn-guests.mjs';
import {educationReward,educationRoundPlan} from '@/lib/education.mjs';
import PanelPages from './panel-pages';
import {useState} from 'react';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {FAMILY} from '@/lib/catalog.mjs';import {playerRank} from '@/lib/progression.mjs';
import {EDUCATION_CAP,EDUCATION_RECOVERY_MS,PUPIL_TYPES,pupilReward} from '@/lib/school.mjs';
import {GRADES,SCHOOL_TYPES,requiredLessons,schoolCapacity,graduationBond,graduationBonus} from '@/lib/education.mjs';
export default function SchoolPanel({game,action,locked}:any){
 const [caretaker,setCaretaker]=useState(''),[type,setType]=useState('diligent'),[grade,setGrade]=useState('D'),[name,setName]=useState(''),[pupilId,setPupilId]=useState(0),[bondId,setBondId]=useState('');
 const available=FAMILY.filter(f=>game.family[f.id]),selected=available.some(f=>f.id===caretaker)?caretaker:available[0]?.id||'',p=game.school.pupils.find((p:any)=>p.id===pupilId)||game.school.pupils[0];
 const round=educationRoundPlan(game,playerRank(game)),milestone=p?pupilMilestone(p,requiredLessons(p)):null;
 const bondFamily=available.filter(f=>graduationBond(f.id)),bondFamilyId=bondFamily.some(f=>f.id===bondId)?bondId:bondFamily[0]?.id||'',bond=graduationBond(bondFamilyId);
 return <section className="school-panel"><div className="family-energy"><div><strong>Education {Math.floor(game.school.points)} / {EDUCATION_CAP}</strong><p>{game.school.points>=EDUCATION_CAP?'Fully recovered':`Next point in ${Math.ceil((1-game.school.points%1)*EDUCATION_RECOVERY_MS/1000)}s`}</p></div></div><p>{game.school.graduates} graduates · +{game.school.income.toFixed(2)} gold/s · {game.fellowXP.toLocaleString()} Fellow EXP</p>
 <PanelPages labels={['Enroll','Classroom','Graduates','Bonuses']}>
 <article className="school-card"><h2>Enroll a pupil</h2><p>{game.school.pupils.length}/{schoolCapacity(game)} seats occupied</p><label htmlFor="school-name">Pupil name</label><Input id="school-name" value={name} maxLength={30} placeholder="Name your pupil" onChange={e=>setName(e.target.value)}/><h4 className="pick-heading">Caretaker</h4>{available.length?<PickStrip label="Caretaker" value={selected} onChange={setCaretaker} items={available.map(f=>({id:f.id,name:f.name,img:wardrobeAppearance(game,f).portrait}))}/>:<p className="item-status">Welcome family first</p>}<h4 className="pick-heading">Pupil type</h4><PickStrip label="Pupil type" shape="chip" value={type} onChange={setType} items={SCHOOL_TYPES.map((t:string)=>({id:t,name:t[0].toUpperCase()+t.slice(1),img:countryIcon(t[0].toUpperCase()+t.slice(1))?.replace(/^\.\/assets\//,'')||null}))}/><h4 className="pick-heading">Intellect grade</h4><PickStrip label="Intellect grade" shape="chip" value={grade} onChange={setGrade} items={Object.entries(GRADES).map(([g,n])=>({id:g,name:g,sub:`${n} pts`}))}/><Button disabled={locked||!selected||!name.trim()||game.school.pupils.length>=schoolCapacity(game)} onClick={()=>action('enrollPupil',selected,{type,grade,name})}>Enroll · Free</Button>{schoolCapacity(game)<5&&<Button variant="outline" disabled={locked} onClick={()=>action('expandSchool')}>Open two more seats · Free</Button>}<p className="small-note">Choose any type and grade. Existing pupils keep their previous requirements.</p></article>
 <article className="school-card"><h2>Classroom</h2><Button disabled={locked||!round.affordable} onClick={()=>action('educateAllRound')}>Teach all · {round.count} points</Button><p>{round.count} pupils need a lesson · {round.credited} EXP this round{round.bonus?` (includes ${round.bonus} from Hunter’s Hat)`:""}</p>{!p?<p>No pupils enrolled yet.</p>:<><PickStrip label="Choose pupil" value={String(p.id)} onChange={id=>setPupilId(Number(id))} items={game.school.pupils.map((x:any)=>({id:String(x.id),name:x.name||`Pupil ${x.id}`,img:FAMILY.find(f=>f.id===x.caretaker)?.portrait||null,sub:`${x.progress}/${requiredLessons(x)}`}))}/><h3>{p.name||`Pupil ${p.id}`}</h3><p>{PUPIL_TYPES.find(t=>t.id===p.type)?.name} · {p.grade?'Grade '+p.grade:'Legacy curriculum'} · Caretaker: {FAMILY.find(f=>f.id===p.caretaker)?.name}</p><div className="school-milestone" aria-live="polite"><strong>{milestone?.stage}</strong>{!!milestone?.remaining&&<p>{milestone.remaining} lessons until {milestone.label.toLowerCase()}</p>}</div><progress value={p.progress} max={requiredLessons(p)} aria-label="Education progress"/><p>{p.progress}/{requiredLessons(p)} lessons · Graduation: +{pupilReward(game,p).toFixed(2)} gold/s</p><p>Noble Lamp: +{innGiftSchoolBonus(game,'graduationFlat')} future graduation earnings</p><p>Active family graduation bonus: +{graduationBonus(game,p)}%</p>{p.progress<requiredLessons(p)?<><div className="business-actions"><Button disabled={locked||game.school.points<1} onClick={()=>action('educate',p.id,'class')}>Class · 1 point</Button><Button variant="outline" disabled={locked||game.school.points<1} onClick={()=>action('educateBatch',p.id)}>Use available points</Button></div><Button variant="outline" disabled={locked||game.school.points<1} onClick={()=>action('educateToMilestone',p.id)}>Teach to next milestone · {Math.min(Math.floor(game.school.points),milestone?.remaining||0)} points</Button><Button variant="outline" disabled={locked} onClick={()=>action('finishSchool',p.id)}>Finish lessons · Free</Button></>:<Button disabled={locked} onClick={()=>action('graduate',p.id)}>Graduate · earnings + 1 Gold Ring</Button>}<p>Class reward: {educationReward(game,p,playerRank(game)).perAward} Fellow EXP · Fishing +{educationReward(game,p,playerRank(game)).percent}%</p><p className="small-note item-status">{educationReward(game,p,playerRank(game)).credited} EXP can be credited now. Batch lessons use the same reward per lesson, up to your EXP limit.</p></>}<Button variant="outline" disabled={locked||game.school.points>EDUCATION_CAP-1||game.inventory.Item_GetCE_10<1} onClick={()=>action('useConsumable','Item_GetCE_10',{count:1})}>Use Focus Candy · +1 point · ×{game.inventory.Item_GetCE_10}</Button></article>
 <article className="school-card"><h2>Recent graduates</h2><Button disabled={locked||!game.school.pupils.some((p:any)=>p.progress>=requiredLessons(p))} onClick={()=>action('graduateAll')}>Graduate all ready pupils</Button>{!game.school.alumni.length?<p>Complete a pupil’s education to graduate them.</p>:game.school.alumni.map((p:any)=><div className="worker" key={p.id}><span>{p.name||`Pupil ${p.id}`}{p.grade?' · '+p.grade:''}</span><strong>+{p.income.toFixed(2)} gold/s</strong></div>)}<p>Latest 20 graduates shown. All graduation income stays saved.</p></article>
 <article className="school-card"><h2>Family graduation bonds</h2>{!bond?<p>Welcome a family member with a graduation bond, such as Charlotte.</p>:<><PickStrip label="Family member" value={bondFamilyId} onChange={setBondId} items={bondFamily.map((f:any)=>({id:f.id,name:f.name,img:wardrobeAppearance(game,f).portrait,sub:game.family[f.id].graduationBond?'Active':undefined}))}/><p>Graduating {bond.type} pupils gain +{bond.percent}% earnings.</p><Button disabled={locked||game.family[bondFamilyId].graduationBond} onClick={()=>action('activateGraduationBond',bondFamilyId)}>{game.family[bondFamilyId].graduationBond?'Bond active':'Activate bond · Free'}</Button><Button variant="outline" disabled={locked||bondFamily.every(f=>game.family[f.id].graduationBond)} onClick={()=>action('activateGraduationBonds')}>Activate all available bonds · Free</Button><p>Applies to matching pupils graduating from now on. Existing graduate income remains unchanged.</p></>}</article>
 </PanelPages><details className="rules-note"><summary>About school progression</summary><p>The five pupil types, D through B+ education requirements, five-seat capacity and five-minute recovery follow published references. Type and grade selection, seat unlocks and bond activation are free sandbox choices. Grades do not yet reproduce original Intellect or earnings formulas; those formulas and Fellow EXP rewards remain local. Matching activated family bonuses add together. Noble Lamp adds a flat amount after that formula, only for future graduates. Teach all spends one point for one lesson per unfinished pupil; enough points for the whole group are required. Hunter’s Hat adds its EXP once per nonempty round, after individual Fishing bonuses. Single-pupil actions do not receive that extra award. Normal Fishing education bonuses add together and apply to future Fellow EXP awards only; each lesson award rounds down. Only documented base graduation bonuses are enabled; bond upgrades, grade A requirements, pupil acquisition, unions and workaholic probabilities remain pending.</p></details></section>
}
