import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {CAMPAIGN,OPENING_STAGES,openingPower,openingQuote,openingRequirement,openingTask,openingAutoGate,AUTO_SPEED_S} from '@/lib/opening.mjs';
import {openingChapterName,openingObjective} from '@/lib/opening-presentation.mjs';
import scenes from '@/lib/stage-scene-data.json';
import OpeningPanel from './opening-panel';
import AdventurePanel from './adventure-panel';
import {SystemMenus} from './panel-pages';
// Chapters 7-150 name a background id; show the opening chapter scene that uses the mapped art (the import
// script maps Forest/City_02/Level/Maze/Mountain/Mine backgrounds onto the four shipped scenes).
const campaignScene=(chapter:number)=>{const shown=(CAMPAIGN as any).backgrounds[String(chapter)]?.shown;return Object.values((scenes as any).chapters).find((c:any)=>c.background===shown)};
export default function StageScreen({game,action,locked,onNavigate,suspended=false}:any){
 const [auto,setAuto]=useState(false),[details,setDetails]=useState<string|null>(null),o=game.opening,stage:any=OPENING_STAGES[o?.cleared||0],chapter=stage?Number(stage._id.split("-")[0]):CAMPAIGN.lastChapter,section=stage?Number(stage._id.split('-')[1]):6;
 const scene=(scenes as any).chapters[chapter]||campaignScene(chapter),power=openingPower(game),quote=stage?openingQuote(stage,power):0,requirement=openingRequirement(game),task=openingTask(game);
 const pending=!!o?.events.length,autoGate=openingAutoGate(game);
 // The Wayfarer walks the path: he stands where the progress bar has reached, and strides for the
 // length of the move whenever a stage clears (reduced motion keeps only the position change).
 const progress=Math.min(100,((o?.cleared||0)%21)/20*100),[walking,setWalking]=useState(false),walkKey=chapter;
 useEffect(()=>{if(!o?.cleared)return;setWalking(true);const t=setTimeout(()=>setWalking(false),900);return()=>clearTimeout(t)},[o?.cleared]);
 const go=()=>{if(!o)return action('openingStart');if(!stage)return false;return action('openingBattle',stage._id)};
 // StageBattleAutoSpeed is 1.7 seconds a stage; the 1000ms here before was a local guess.
 useEffect(()=>{if(!auto)return;if(!o||!stage||locked||pending||details||suspended||autoGate){setAuto(false);return}const hidden=()=>{if(document.hidden)setAuto(false)};document.addEventListener('visibilitychange',hidden);const timer=setTimeout(()=>{if(document.hidden||!action('openingBattle',stage._id))setAuto(false)},AUTO_SPEED_S*1000);return()=>{clearTimeout(timer);document.removeEventListener('visibilitychange',hidden)}},[auto,o?.cleared,locked,pending,details,suspended,stage?._id,autoGate]);
 const open=(name:string)=>{setAuto(false);setDetails(name)};
 return <section className="stage-screen" aria-label="Exploration stage"><div className="stage-scene">{scene?.src&&<img key={scene.src} className="stage-background" src={'./assets/'+(scene.display||scene.src)} decoding="async" alt="" ref={i=>{if(i?.complete&&i.naturalWidth)i.classList.add('loaded')}} onLoad={e=>e.currentTarget.classList.add('loaded')} onError={e=>{const i=e.currentTarget;if(scene.display&&!i.src.endsWith(scene.src))i.src='./assets/'+scene.src}}/>}<h2>{openingChapterName(chapter)}</h2><div className="stage-path" aria-label={'Chapter '+chapter+', section '+section+' of 6'}><div className="stage-path-bar"><div style={{width:progress+'%'}}/></div><img key={walkKey} className={'stage-walker'+(walking?' walking':'')} style={{'--walk':progress/100} as any} src="./assets/wayfarer/wayfarer-cutout.png" alt="" aria-hidden="true"/>{[1,2,3,4,5,6].map(n=><span key={n} className={'stage-marker'+(n===section?' current':'')}><img src={'./assets/ui-scenes/'+(n===6?'Icon_Stage_Boss':n<section?'Icon_Stage_Arrived':'Icon_Stage_NotArrived')+'.png'} alt=""/><b>{n}</b></span>)}</div></div>
 <div className="stage-operation"><div className="stage-current"><small>{stage?.boss?'BOSS ENCOUNTER':'EXPLORATION'}</small><h3>{o?stage?'Stage '+stage._id:'Every chapter cleared':'A village of your own'}</h3>{o&&stage&&<p>Fellow Power {power.toLocaleString()}</p>}</div><div className="stage-records" aria-label="Recent stage records"><header>Stage Records</header>{o?.cleared?OPENING_STAGES.slice(Math.max(0,o.cleared-3),o.cleared).map(s=><p key={s._id}>✓ Cleared {s._id}</p>):<p>No records yet.</p>}{pending&&<Button variant="outline" onClick={()=>open('Explore')}>Resolve roadside encounter · {o.events.length}</Button>}</div><div className="stage-go"><Button disabled={locked||!!o&&!stage} onClick={go}>{o&&stage?<><b>Go</b><small>{(quote||0).toLocaleString()} Gold</small></>:o?'Go':'Begin opening journey'}</Button><Button variant="outline" aria-pressed={auto} disabled={locked||!o||!stage||pending||!!autoGate} onClick={()=>setAuto(v=>!v)}>{auto?'Stop Auto':'Auto'}</Button><Button variant="outline" disabled={locked||!o||!stage||pending||!!autoGate} onClick={()=>{setAuto(false);action('openingAuto')}}>Full-Auto</Button>{autoGate&&o&&<p className="small-note item-status">{autoGate}</p>}</div>
 <nav className="stage-activity-buttons" aria-label="Stage activities">{([['Quest','overview'],['Rank','rank'],['Workshop','building'],['Rewards','gifts'],['Other journeys','mastery']] as const).map(([name,icon])=><Button key={name} variant="outline" aria-label={name} onClick={()=>open(name)}><img src={'./assets/menu/'+icon+'.png'} alt=""/><span>{name==='Other journeys'?'Journeys':name}</span></Button>)}</nav>{o&&task&&<button className="stage-quest-link" onClick={()=>open('Quest')}>{openingObjective(task)?.text||requirement.label} · {requirement.current.toLocaleString()}/{requirement.goal.toLocaleString()}</button>}
 </div><Dialog open={!!details} onOpenChange={value=>{if(!value)setDetails(null)}}><DialogContent className="stage-detail-sheet"><DialogTitle>{details}</DialogTitle><DialogDescription>Journey activities</DialogDescription><SystemMenus name="">{details==='Other journeys'?<AdventurePanel game={game} action={action} locked={locked} onNavigate={onNavigate}/>:<OpeningPanel key={details} initialPage={details||'Quest'} initialExplorePage={details==='Explore'&&pending?1:0} game={game} action={action} locked={locked} onNavigate={onNavigate}/>}</SystemMenus></DialogContent></Dialog></section>;
}
