import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {OPENING_STAGES,openingPower,openingQuote,openingRequirement,openingTask} from '@/lib/opening.mjs';
import {openingChapterName,openingObjective} from '@/lib/opening-presentation.mjs';
import scenes from '@/lib/stage-scene-data.json';
import OpeningPanel from './opening-panel';
import AdventurePanel from './adventure-panel';
import {SystemMenus} from './panel-pages';
export default function StageScreen({game,action,locked,onNavigate,suspended=false}:any){
 const [auto,setAuto]=useState(false),[details,setDetails]=useState<string|null>(null),o=game.opening,stage:any=OPENING_STAGES[o?.cleared||0],chapter=stage?Number(stage._id.split('-')[0]):6,section=stage?Number(stage._id.split('-')[1]):6;
 const scene=(scenes as any).chapters[chapter],power=openingPower(game),quote=stage?openingQuote(stage,power):0,requirement=openingRequirement(game),task=openingTask(game);
 const pending=!!o?.events.length;
 const go=()=>{if(!o)return action('openingStart');if(!stage)return false;return action('openingBattle',stage._id)};
 useEffect(()=>{if(!auto)return;if(!o||!stage||locked||pending||details||suspended){setAuto(false);return}const hidden=()=>{if(document.hidden)setAuto(false)};document.addEventListener('visibilitychange',hidden);const timer=setTimeout(()=>{if(document.hidden||!action('openingBattle',stage._id))setAuto(false)},1000);return()=>{clearTimeout(timer);document.removeEventListener('visibilitychange',hidden)}},[auto,o?.cleared,locked,pending,details,suspended,stage?._id]);
 const open=(name:string)=>{setAuto(false);setDetails(name)};
 return <section className="stage-screen" aria-label="Exploration stage"><div className="stage-scene">{scene?.src&&<img className="stage-background" src={'./assets/'+scene.src} alt=""/>}<h2>{openingChapterName(chapter)}</h2><div className="stage-path" aria-label={'Chapter '+chapter+', section '+section+' of 6'}><div className="stage-path-bar"><div style={{width:Math.min(100,((o?.cleared||0)%21)/20*100)+'%'}}/></div>{[1,2,3,4,5,6].map(n=><span key={n} className={'stage-marker'+(n===section?' current':'')}><img src={'./assets/ui-scenes/'+(n===6?'Icon_Stage_Boss':n<section?'Icon_Stage_Arrived':'Icon_Stage_NotArrived')+'.png'} alt=""/><b>{n}</b></span>)}</div></div>
 <div className="stage-operation"><div className="stage-current"><small>{stage?.boss?'BOSS ENCOUNTER':'EXPLORATION'}</small><h3>{o?stage?'Stage '+stage._id:'Six chapters cleared':'A village of your own'}</h3>{o&&stage&&<p>Power {power.toLocaleString()} · Cost {(quote||0).toLocaleString()} Gold</p>}</div><div className="stage-records" aria-label="Recent stage records">{o?.cleared?OPENING_STAGES.slice(Math.max(0,o.cleared-3),o.cleared).map(s=><p key={s._id}>✓ Cleared {s._id}</p>):<p>Start your journey and earn your first companions.</p>}{pending&&<Button variant="outline" onClick={()=>open('Explore')}>Resolve roadside encounter · {o.events.length}</Button>}</div><div className="stage-go"><Button disabled={locked||!!o&&!stage} onClick={go}>{o?'Go':'Begin opening journey'}</Button><Button variant="outline" aria-pressed={auto} disabled={locked||!o||!stage||pending} onClick={()=>setAuto(v=>!v)}>{auto?'Stop Auto':'Auto'}</Button></div>
 <nav className="stage-activity-buttons" aria-label="Stage activities">{['Quest','Rank','Workshop','Rewards'].map(name=><Button key={name} variant="outline" onClick={()=>open(name)}>{name}</Button>)}<Button variant="outline" onClick={()=>open('Other journeys')}>Other journeys</Button></nav>{o&&task&&<button className="stage-quest-link" onClick={()=>open('Quest')}>{openingObjective(task)?.text||requirement.label} · {requirement.current.toLocaleString()}/{requirement.goal.toLocaleString()}</button>}
 </div><Dialog open={!!details} onOpenChange={value=>{if(!value)setDetails(null)}}><DialogContent className="stage-detail-sheet"><DialogTitle>{details}</DialogTitle><DialogDescription>Journey activities</DialogDescription><SystemMenus name="">{details==='Other journeys'?<AdventurePanel game={game} action={action} locked={locked} onNavigate={onNavigate}/>:<OpeningPanel key={details} initialPage={details||'Quest'} initialExplorePage={details==='Explore'&&pending?1:0} game={game} action={action} locked={locked} onNavigate={onNavigate}/>}</SystemMenus></DialogContent></Dialog></section>;
}
