import {ActivityPages} from './panel-pages';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {TREASURE_AREAS,TREASURE_RELICS,treasureState,treasureLevel,tileGem,restorationLevel,relicEffects,treasureIncome,gemGradeWeights,RESTORATION_MAX,TREASURE_STAMINA_LIMIT} from '@/lib/treasure.mjs';
// What a relic pays and to whom, from its own Exhibit row (lib/treasure.mjs relicEffects, 2026-09-18).
const SCOPE:any={all:()=>'every Fellow',country:(id:string)=>['','Inspiring','Diligent','Brave','Informed','Unfettered'][+id]+' Fellows',rare:(id:string)=>`rarity-${id} Fellows`};
function relicLine(r:any,own:any){const e=r.effectSource;if(!e||e.target!=='hero'||!['talent','atk'].includes(e.prop))return 'this exhibit’s original effect has no Everkai equivalent yet';
 const v=e.initial+restorationLevel(own)*e.perLevel,what=e.prop==='talent'?`+${v.toLocaleString()} Aptitude`:e.propType==='extradd'?`+${v.toLocaleString()} Power`:`+${v/100}% Power`;
 return `${what} to ${SCOPE[e.condition.conditionType]?.(e.condition.id)||'Fellows'}${own.displayed?'':' when displayed'}`;}
export default function TreasurePanel({game,action,locked,initialPage='dig',onMuseum,onVillage}:any){
 const [tab,setTab]=useState(initialPage),[region,setRegion]=useState('Relic001'),[page,setPage]=useState(0);
 const t=treasureState(game),level=treasureLevel(t),area=TREASURE_AREAS.find(a=>a.id===(t.trip?.area||region))!,owned=TREASURE_RELICS.filter(r=>t.relics[r.id]),pages=Math.max(1,owned.length),current=Math.min(page,pages-1);
 const run=(a:string,id:any=null)=>action(a,id,t.seq);
 return <section className="treasure-panel"><h2>Treasure Hunt</h2><ActivityPages options={[['dig','Expedition'],['appraise','Appraisal'],['relics','Relic collection']]} value={tab} onChange={setTab}><div className="treasure-panel">
 {tab==='dig'&&<><p>Steeltooth Lv. {level} · {t.xp} EXP · Stamina {t.stamina}/{TREASURE_STAMINA_LIMIT}</p>{!t.trip?<><div className="business-actions">{TREASURE_AREAS.map(a=><Button key={a.id} variant="outline" aria-pressed={region===a.id} disabled={level<a.level} onClick={()=>setRegion(a.id)}>{a.name}{level<a.level?` · Lv. ${a.level}`:''}</Button>)}</div>{!t.stamina&&<p>Steeltooth is empty. Refill here before the next expedition.</p>}<p>Scout {area.name}. Find gemstones, then return to unload your finds.</p><div className="business-actions"><Button disabled={locked||!t.stamina} onClick={()=>run('treasureStart',area.id)}>Begin expedition</Button></div></>:<><p>{area.name} · {t.trip.tiles.length*10} EXP aboard · {t.trip.tiles.filter(tileGem).length} gemstones aboard</p><div className="treasure-board" aria-label="Excavation grid">{Array.from({length:12},(_,i)=>{const dug=t.trip.tiles.includes(i);return <button key={i} disabled={locked||dug||!t.stamina} aria-label={`Tile ${i+1}${dug?' excavated':tileGem(i)?' gemstone':' stone'}`} className={dug?'excavated':tileGem(i)?'gem-tile':''} onClick={()=>run('treasureDig',i)}>{dug?'✓':tileGem(i)?'◆':'▰'}</button>})}</div><div className="business-actions"><Button disabled={locked} onClick={()=>run('treasureReturn')}>Return to camp</Button><span>◆ Radar: gemstone</span></div></>}</>}
 {tab==='appraise'&&<><p>Unload at camp, then open gemstones from each region.</p><p className="item-status">Steeltooth Lv. {level} gemstone grades · {['common','fine','rare'].map((g,i)=>`${g} ${Math.round(gemGradeWeights(level)[i]/100)}%`).join(' · ')}</p>{TREASURE_AREAS.map(a=><div className="business-actions" key={a.id}><span>{a.name} · {t.gems[a.id]||0}</span><Button disabled={locked||!!t.trip||!t.gems[a.id]} onClick={()=>run('treasureAppraise',a.id)}>Appraise · {a.name}</Button></div>)}{t.trip&&<p>Return to camp before appraising.</p>}</>}
 {tab==='relics'&&<><div className="business-actions">{onMuseum&&<Button variant="outline" onClick={onMuseum}>Visit Private Hall</Button>}{onVillage&&treasureIncome(game)>0&&<Button variant="outline" onClick={onVillage}>Collect earnings in village</Button>}</div><p>{owned.length} / {TREASURE_RELICS.length} relics found · {Object.values(t.relics).filter((r:any)=>r.donated).length} donated{treasureIncome(game)>0?` · legacy visitor income +${treasureIncome(game)} gold/s`:''}</p>{!owned.length&&<p>Your first appraised relic will appear here.</p>}{owned.slice(current,current+1).map(r=><article className="school-card" key={r.id}><h3>{r.name}</h3><p>{t.relics[r.id].materials} duplicate materials · {t.relics[r.id].displayed?'On display':t.relics[r.id].donated?'In storage':'Awaiting donation'}</p><Button disabled={locked} onClick={()=>run(t.relics[r.id].donated?'treasureDisplay':'treasureDonate',r.id)}>{!t.relics[r.id].donated?'Donate relic':t.relics[r.id].displayed?'Store relic':'Display relic'}</Button>{t.relics[r.id].donated&&<div className="relic-restoration"><p>Restoration {restorationLevel(t.relics[r.id])}/{RESTORATION_MAX} · {relicLine(r,t.relics[r.id])}</p><Button variant="outline" disabled={locked||restorationLevel(t.relics[r.id])>=RESTORATION_MAX||t.relics[r.id].materials<restorationLevel(t.relics[r.id])+1} onClick={()=>run('treasureRestore',r.id)}>{restorationLevel(t.relics[r.id])>=RESTORATION_MAX?'Fully restored':`Restore · ${restorationLevel(t.relics[r.id])+1} materials${r.effect?` → +${r.effect.perLevel} Aptitude`:''}`}</Button><p className="small-note">Spend this relic’s materials, or keep them. An exhibit pays only while it is on display.</p></div>}</article>)}<div className="business-actions"><Button disabled={!current} onClick={()=>setPage(current-1)}>Previous</Button><span>{current+1} / {pages}</span><Button disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Next</Button></div></>}
 <details className="rules-note"><summary>About this expedition</summary><p>Regions and relic names come from a community reference; the appraisal pools, the three gemstone grades per region and the per-level grade weights come from the original’s own RelicMap, GemGacha and RelicLevel tables. A higher Steeltooth level digs rarer gemstones, and only the rarest grade carries the pieces that assemble Ladon’s Skeleton and the Ancient Golden Mural. Digging layout, EXP, level gates and free refill are sandbox rules; stamina refills daily at midnight UTC. Restoration no longer pays gold: the original’s museum pays exhibit EXP hourly, never gold, and a restored exhibit raises its own skill instead. Eight relics raise Fellow Aptitude; the other twenty-eight carry effects Everkai has no channel for yet and say so. Everkai keeps a 20-step restoration ladder priced in duplicate materials in place of the original’s 120 steps priced in exhibit EXP. This collection is separate from Private Hall keepsakes.</p></details></div></ActivityPages></section>;
}
