import {ActivityPages} from './panel-pages';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {TREASURE_AREAS,TREASURE_RELICS,treasureState,treasureLevel,tileGem,restorationLevel,restorationIncome,treasureIncome} from '@/lib/treasure.mjs';
export default function TreasurePanel({game,action,locked,initialPage='dig',onMuseum,onVillage}:any){
 const [tab,setTab]=useState(initialPage),[region,setRegion]=useState('Relic001'),[page,setPage]=useState(0);
 const t=treasureState(game),level=treasureLevel(t),area=TREASURE_AREAS.find(a=>a.id===(t.trip?.area||region))!,owned=TREASURE_RELICS.filter(r=>t.relics[r.id]),pages=Math.max(1,owned.length),current=Math.min(page,pages-1);
 const run=(a:string,id:any=null)=>action(a,id,t.seq);
 return <section className="treasure-panel"><h2>Treasure Hunt</h2><ActivityPages options={[['dig','Expedition'],['appraise','Appraisal'],['relics','Relic collection']]} value={tab} onChange={setTab}><div className="treasure-panel">
 {tab==='dig'&&<><p>Steeltooth Lv. {level} · {t.xp} EXP · Stamina {t.stamina}/12</p>{!t.trip?<><div className="business-actions">{TREASURE_AREAS.map(a=><Button key={a.id} variant="outline" aria-pressed={region===a.id} disabled={level<a.level} onClick={()=>setRegion(a.id)}>{a.name}{level<a.level?` · Lv. ${a.level}`:''}</Button>)}</div>{!t.stamina&&<p>Steeltooth is empty. Refill here before the next expedition.</p>}<p>Scout {area.name}. Find gemstones, then return to unload your finds.</p><div className="business-actions"><Button disabled={locked||!t.stamina} onClick={()=>run('treasureStart',area.id)}>Begin expedition</Button><Button variant="outline" disabled={locked||t.stamina===12} onClick={()=>run('treasureRefill')}>Refill · Free</Button></div></>:<><p>{area.name} · {t.trip.tiles.length*10} EXP aboard · {t.trip.tiles.filter(tileGem).length} gemstones aboard</p><div className="treasure-board" aria-label="Excavation grid">{Array.from({length:12},(_,i)=>{const dug=t.trip.tiles.includes(i);return <button key={i} disabled={locked||dug||!t.stamina} aria-label={`Tile ${i+1}${dug?' excavated':tileGem(i)?' gemstone':' stone'}`} className={dug?'excavated':tileGem(i)?'gem-tile':''} onClick={()=>run('treasureDig',i)}>{dug?'✓':tileGem(i)?'◆':'▰'}</button>})}</div><div className="business-actions"><Button disabled={locked} onClick={()=>run('treasureReturn')}>Return to camp</Button><span>◆ Radar: gemstone</span></div></>}</>}
 {tab==='appraise'&&<><p>Unload at camp, then open gemstones from each region.</p>{TREASURE_AREAS.map(a=><div className="business-actions" key={a.id}><span>{a.name} · {t.gems[a.id]||0}</span><Button disabled={locked||!!t.trip||!t.gems[a.id]} onClick={()=>run('treasureAppraise',a.id)}>Appraise · {a.name}</Button></div>)}{t.trip&&<p>Return to camp before appraising.</p>}</>}
 {tab==='relics'&&<><div className="business-actions">{onMuseum&&<Button variant="outline" onClick={onMuseum}>Visit Private Hall</Button>}{onVillage&&treasureIncome(game)>0&&<Button variant="outline" onClick={onVillage}>Collect earnings in village</Button>}</div><p>Museum visitors +{treasureIncome(game)} gold/s · {owned.length} relics found · {Object.values(t.relics).filter((r:any)=>r.donated).length} donated</p>{!owned.length&&<p>Your first appraised relic will appear here.</p>}{owned.slice(current,current+1).map(r=><article className="school-card" key={r.id}><h3>{r.name}</h3><p>{t.relics[r.id].materials} duplicate materials · {t.relics[r.id].displayed?'On display':t.relics[r.id].donated?'In storage':'Awaiting donation'}</p><Button disabled={locked} onClick={()=>run(t.relics[r.id].donated?'treasureDisplay':'treasureDonate',r.id)}>{!t.relics[r.id].donated?'Donate relic':t.relics[r.id].displayed?'Store relic':'Display relic'}</Button>{t.relics[r.id].donated&&<div className="relic-restoration"><p>Sandbox restoration {restorationLevel(t.relics[r.id])}/20 · Visitors +{restorationIncome(t.relics[r.id])} gold/s</p><Button variant="outline" disabled={locked||restorationLevel(t.relics[r.id])>=20||t.relics[r.id].materials<restorationLevel(t.relics[r.id])+1} onClick={()=>run('treasureRestore',r.id)}>{restorationLevel(t.relics[r.id])>=20?'Fully restored':`Restore · ${restorationLevel(t.relics[r.id])+1} materials → +1 gold/s`}</Button><p className="small-note">Optional local rule. Spend this relic’s materials, or keep them. Earnings continue in storage.</p></div>}</article>)}<div className="business-actions"><Button disabled={!current} onClick={()=>setPage(current-1)}>Previous</Button><span>{current+1} / {pages}</span><Button disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Next</Button></div></>}
 <details className="rules-note"><summary>About this expedition</summary><p>Regions, relic names and normal appraisal weights come from a community reference. Digging layout, costs, EXP, level gates and free refill are sandbox rules. Stamina refills daily at midnight UTC. Original relic upgrade costs and Power effects remain unverified. Optional sandbox restoration spends 1, then 2, up to 20 duplicate materials per level; each level adds 1 gold/s through village collection. This is our visitor-income rule, not an original relic skill. This collection is separate from Private Hall keepsakes.</p></details></div></ActivityPages></section>;
}
