import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import PanelPages from './panel-pages';
import {WORKSHOP_PRODUCTS,workshopProduct,workshopHot,workshopUnlocked,workshopMastery,workshopAvailableXP} from '@/lib/workshop.mjs';
import {fellowById} from '@/lib/catalog.mjs';
export default function WorkshopPanel({game,action,locked}:any){
 const [id,setId]=useState('1001'),[worker,setWorker]=useState(''),w=game.workshop,p=workshopProduct(id)!;
 if(!w)return <section><h2>Workshop production</h2><p>Assign a Fellow, manufacture goods, collect Workshop coins and exchange them for training supplies.</p><Button disabled={locked||!game.enterprises?.Building_301} onClick={()=>action('openWorkshop')}>Open Workshop production</Button>{!game.enterprises?.Building_301&&<p>Open the original Workshop business first.</p>}</section>;
 const workers=Object.keys(game.fellows).filter(f=>fellowById(f)?.type===p.type),selected=workers.includes(worker)?worker:workers[0],j=w.job;
 return <section><h2>Workshop production</h2><p>Supplies {w.supplies} · Wallet {w.wallet.toLocaleString()} coins</p><PanelPages labels={['Manufacture','Products','Mastery','Store','Rules']}><>
 {j?<><h3>{workshopProduct(j.product)?.name}</h3><p>{fellowById(j.fellow)?.name} · {j.unitsDone}/{j.count} complete</p><p>{j.count*workshopProduct(j.product)!.seconds-j.secondsDone}s remaining · +{workshopProduct(j.product)?.coinsPerSecond} base coins/s · +{(j.masteryTier||0)*10}% saved mastery</p><Button disabled={locked} onClick={()=>action('finishWorkshop')}>Finish now · Free sandbox</Button></>:<><label htmlFor="workshop-product">Product</label><NativeSelect id="workshop-product" value={id} onChange={e=>setId(e.target.value)}>{WORKSHOP_PRODUCTS.map(p=><NativeSelectOption key={p.id} value={p.id}>{p.name}{workshopHot(p.id,game.lastAt)?' · Hot':''}{workshopUnlocked(w,p.id)?'':' · Locked'}</NativeSelectOption>)}</NativeSelect><p>{p.type} · {p.seconds}s · {p.coinsPerSecond} coins/s · {p.salesXP*(workshopHot(id,game.lastAt)?1.2:1)} Sales EXP{workshopHot(id,game.lastAt)?' (+20% hot bonus)':''}</p><NativeSelect aria-label="Manufacturing Fellow" value={selected||''} onChange={e=>setWorker(e.target.value)}>{!workers.length&&<NativeSelectOption value="">Recruit a matching Fellow first</NativeSelectOption>}{workers.map(f=><NativeSelectOption key={f} value={f}>{fellowById(f)?.name} · {w.salesXP[f]||0} Sales EXP</NativeSelectOption>)}</NativeSelect><div className="business-actions">{[1,5,10].map(n=><Button key={n} disabled={locked||!selected||!workshopUnlocked(w,id)||w.supplies<n} onClick={()=>action('startWorkshop',id,{fellow:selected,count:n})}>Make {n} · {n} supplies</Button>)}</div></>}
 <Button variant="outline" disabled={locked||w.supplies>=1e9} onClick={()=>action('restockWorkshop')}>Restock 20 supplies · Free sandbox</Button><p>Deposit: {w.deposit.toLocaleString()} coins</p><Button disabled={locked||!w.deposit||w.wallet+w.deposit>1e9} onClick={()=>action('collectWorkshop')}>Collect Workshop coins</Button></><><NativeSelect aria-label="Product progress" value={id} onChange={e=>setId(e.target.value)}>{WORKSHOP_PRODUCTS.map(p=><NativeSelectOption key={p.id} value={p.id}>{p.name}</NativeSelectOption>)}</NativeSelect><h3>{p.name}</h3><p>{w.crafted[id]||0} crafted · {workshopUnlocked(w,id)?'Available':'Craft the previous product to unlock'}</p><p>Each product completed rewards {p.salesXP} Sales EXP before the hot bonus. Sales EXP belongs to its manufacturing Fellow. Its original upgrade use is not documented; optional local mastery spends a separate ledger.</p><p>Product level and Power effects await verified tables.</p></><><h3>Local Workshop mastery</h3><p>Spend Sales EXP to increase this Fellow’s future Workshop coin yields. Earned EXP stays recorded. Costs and effects are local sandbox rules.</p><NativeSelect aria-label="Mastery Fellow" value={worker||Object.keys(game.fellows)[0]} onChange={e=>setWorker(e.target.value)}>{Object.keys(game.fellows).map(f=><NativeSelectOption key={f} value={f}>{fellowById(f)?.name}</NativeSelectOption>)}</NativeSelect>{(()=>{const f=worker||Object.keys(game.fellows)[0],tier=workshopMastery(w,f),cost=100*(tier+1);return <><p>Tier {tier}/10 · +{tier*10}% Workshop coins</p><p>Earned {w.salesXP[f]||0} · Spent {w.mastery?.[f]?.spent||0} · Available {workshopAvailableXP(w,f)} Sales EXP</p><Button disabled={locked||tier>=10||workshopAvailableXP(w,f)<cost} onClick={()=>action('upgradeWorkshopMastery',f)}>{tier>=10?'Mastery complete':`Upgrade · ${cost} Sales EXP → +${(tier+1)*10}% coins`}</Button><p>Applies only to new jobs. Current jobs keep their saved payout.</p></>})()}</><><h3>Workshop store</h3><p>{w.wallet.toLocaleString()} coins available</p><Button disabled={locked||w.wallet<2000||game.inventory.Item_Talent_Hero_1>=1e9} onClick={()=>action('buyWorkshopPearl')}>Skill Pearl · 2,000 coins</Button><p>Use Skill Pearls in Fellow training. This store price is sandbox balance.</p></><p>Durations, coin rates, Sales EXP and the +20% hot bonus are readable APK values. Materials use a local supply counter. Product type mapping, one-craft unlocks, UTC daily hot rotation and store price are sandbox choices. Actual recipe materials, evaluation odds and product-level Power effects remain unknown. Jobs cannot be canceled; free finishing is optional. Manufacturing roles are separate from business assignments. Coins accumulate while away and must be collected.</p></PanelPages></section>;
}
