import {artifactState} from './artifacts.mjs';
export const BANQUET_ORE='Item_Strengthen_Equipment_1';
import data from './banquet-data.json' with {type:'json'};import {FELLOWS} from './catalog.mjs';
export const BANQUET_PARTIES=data.parties,BANQUET_SHOP=data.shop,BANQUET_MATERIALS=data.materials;
const partyById=new Map(BANQUET_PARTIES.map(x=>[x.id,x])),shopById=new Map(BANQUET_SHOP.map(x=>[x.id,x])),materialIds=new Set(BANQUET_MATERIALS.map(x=>x.id));
const int=(x,max=1e9)=>Number.isSafeInteger(x)&&x>=0&&x<=max,record=x=>x&&typeof x==='object'&&!Array.isArray(x),day=s=>Math.floor(s.lastAt/86400000);
export function banquetState(s){const b=s.banquets||{policyVersion:1,seq:0,coins:0,popularity:0,pantry:{},run:null,history:[],shop:{day:day(s),bought:{}}};return b.shop.day<day(s)?{...b,shop:{day:day(s),bought:{}}}:b}
export const seatedGuests=(s,r=s.banquets?.run)=>r?Math.min(r.guests.length,Math.max(0,Math.floor((s.lastAt-r.startedAt)/r.intervalMs))):0;
function validRun(r,s){return record(r)&&r.policyVersion===1&&int(r.id)&&partyById.has(r.kind)&&Number.isSafeInteger(r.startedAt)&&r.startedAt>=0&&r.startedAt<=s.lastAt&&int(r.intervalMs,86400000)&&r.intervalMs>0&&int(r.coinsPerGuest,1e6)&&int(r.popularityPerGuest,1e6)&&r.coinsPerGuest>0&&r.popularityPerGuest>0&&Array.isArray(r.guests)&&r.guests.length>0&&r.guests.length<=16&&r.guests.every(x=>typeof x==='string'&&x.length>0&&x.length<=80)&&r.guestMode==='simulated'&&record(r.paid)&&Object.keys(r.paid).length>0&&Object.entries(r.paid).every(([id,n])=>materialIds.has(id)&&int(n,1e6)&&n>0)}
export function validBanquets(s){if(s?.banquets===undefined)return true;const b=s.banquets;if(!record(b)||b.policyVersion!==1||!int(b.seq)||!int(b.coins)||!int(b.popularity)||!record(b.pantry)||!Object.entries(b.pantry).every(([id,n])=>materialIds.has(id)&&int(n,1e6))||!Array.isArray(b.history)||b.history.length>10000||new Set(b.history.map(r=>r?.id)).size!==b.history.length)return false;
 if(!b.history.every(r=>validRun(r,s)&&r.id<=b.seq&&Number.isSafeInteger(r.claimedAt)&&r.claimedAt>=r.startedAt+r.guests.length*r.intervalMs&&r.claimedAt<=s.lastAt&&r.coins===r.coinsPerGuest*r.guests.length&&r.popularity===r.popularityPerGuest*r.guests.length))return false;
 if(b.run!==null&&(!validRun(b.run,s)||b.run.id>b.seq||b.history.some(r=>r.id===b.run.id)))return false;return record(b.shop)&&int(b.shop.day)&&b.shop.day<=day(s)&&record(b.shop.bought)&&Object.entries(b.shop.bought).every(([id,n])=>shopById.has(id)&&int(n,shopById.get(id).dailyLimit))&&validPurchases(b,s);}
export function banquetPurchasePlan(s,id,requested){const b=banquetState(s),item=shopById.get(id);if(!item||![1,5,'max'].includes(requested)||(b.purchases?.length||0)>=10000)return {quantity:0,cost:0};const capacity=id===BANQUET_ORE?1e9-artifactState(s).ore:1e6-(s.inventory[id]??1e6),max=Math.max(0,Math.min(item.dailyLimit-(b.shop.bought[id]||0),Math.floor(b.coins/item.price),capacity)),quantity=requested==='max'?max:requested<=max?requested:0;return {quantity,cost:quantity*item.price};}
function validPurchases(b,s){if(b.purchases===undefined)return true;if(!Array.isArray(b.purchases)||b.purchases.length>10000)return false;const ids=new Set(),historyIds=new Set(b.history.map(h=>h.id)),today={};for(const r of b.purchases){if(!record(r)||r.policyVersion!==1||!int(r.id)||!r.id||r.id>b.seq||ids.has(r.id)||historyIds.has(r.id)||b.run?.id===r.id||!shopById.has(r.itemId)||!int(r.quantity,100)||!r.quantity||!int(r.unitPrice,1e9)||!r.unitPrice||r.paid!==r.quantity*r.unitPrice||!int(r.paid)||r.destination!==(r.itemId===BANQUET_ORE?'forge':'bag')||!Number.isSafeInteger(r.at)||r.at<0||r.at>s.lastAt||r.day!==Math.floor(r.at/86400000))return false;ids.add(r.id);if(r.day===b.shop.day)today[r.itemId]=(today[r.itemId]||0)+r.quantity;}return Object.entries(today).every(([id,n])=>n<=(b.shop.bought[id]||0));}
export function banquetAction(s,action,target,value){if(!['banquetPrepare','banquetHost','banquetClaim','banquetBuy'].includes(action))return null;const old=banquetState(s),fail=error=>({state:s,error});if(value?.seq!==old.seq||old.seq>=1e9)return fail('This banquet changed. Use the current controls.');const b={...old,seq:old.seq+1,pantry:{...old.pantry},shop:{...old.shop,bought:{...old.shop.bought}}};
 if(action==='banquetPrepare'||action==='banquetHost'){const p=partyById.get(target);if(!p)return fail('Choose a banquet.');if(action==='banquetPrepare'){if(p.materials.some(id=>(b.pantry[id]||0)>=1e6))return fail('Pantry is full.');for(const id of p.materials)b.pantry[id]=(b.pantry[id]||0)+1;return {state:{...s,banquets:b},message:'Free sandbox supplies prepared. Hosting is a separate action.'};}
 if(b.run)return fail('Finish and collect your current banquet first.');if(b.history.length>=10000)return fail('Banquet record capacity reached.');if(p.materials.some(id=>!(b.pantry[id]>0)))return fail('Prepare the listed materials first.');for(const id of p.materials)b.pantry[id]--;const fellows=FELLOWS.filter(f=>s.fellows[f.id]);b.run={policyVersion:1,id:b.seq,kind:p.id,startedAt:s.lastAt,intervalMs:5000,coinsPerGuest:100,popularityPerGuest:100,guestMode:'simulated',guests:Array.from({length:p.seats},(_,i)=>fellows[i]?.name||`Village visitor ${i+1}`),paid:Object.fromEntries(p.materials.map(id=>[id,1]))};return {state:{...s,banquets:b},message:'Private banquet started. All guests are simulated offline.'};}
 if(action==='banquetClaim'){const r=b.run;if(!r||r.id!==target||seatedGuests(s,r)<r.guests.length)return fail('Wait until every simulated guest is seated.');const coins=r.coinsPerGuest*r.guests.length,popularity=r.popularityPerGuest*r.guests.length;if(b.coins+coins>1e9||b.popularity+popularity>1e9)return fail('Reward balance is full. Spend coins before collecting.');b.coins+=coins;b.popularity+=popularity;b.history=[...b.history,{...r,claimedAt:s.lastAt,coins,popularity}];b.run=null;return {state:{...s,banquets:b},message:`Banquet complete · ${coins} Banquet Coins and ${popularity} Popularity.`};}
 const item=shopById.get(target),plan=banquetPurchasePlan(s,target,value.quantity),q=plan.quantity;if(!item||!q)return fail('Choose a full affordable batch with daily allowance and destination space.');
 b.coins-=plan.cost;b.shop.bought[target]=(b.shop.bought[target]||0)+q;b.purchases=[...(b.purchases||[]),{policyVersion:1,id:b.seq,itemId:target,quantity:q,unitPrice:item.price,paid:plan.cost,destination:target===BANQUET_ORE?'forge':'bag',day:day(s),at:s.lastAt}];
 if(target===BANQUET_ORE){const a=artifactState(s);return {state:{...s,banquets:b,artifacts:{...a,ore:a.ore+q}},message:`Exchanged ${plan.cost} Banquet Coins for ${q} Magic Ore · ready in Equipment.`};}
 return {state:{...s,banquets:b,inventory:{...s.inventory,[target]:s.inventory[target]+q}},message:`Exchanged for ${q} ${item.name}. Available in your Bag.`};}
