import data from './fountain-data.json' with {type:'json'};
import {FELLOWS,FAMILY} from './catalog.mjs';
import {newFellow,EXTRA_ITEMS} from './adventure.mjs';
import {originalCharacter} from './original-catalog.mjs';
export const WISH_POOL=data.pool,WISH_RECRUITS=data.recruits;
const byId=new Map(WISH_POOL.map(r=>[r.id,r])),int=(n,max=1e9)=>Number.isSafeInteger(n)&&n>=0&&n<=max,record=x=>x&&typeof x==='object'&&!Array.isArray(x);
export const fountainState=s=>s.fountain||{policyVersion:1,seq:0,seed:123456789,bottles:0,total:0,ledger:{},history:[],recruited:[]};
export const fairyClaims=s=>fountainState(s).fairyClaims||[];
export const fairyAvailable=s=>Math.floor(fountainState(s).total/500)-fairyClaims(s).length;
export const transferable=r=>!!r.itemId&&EXTRA_ITEMS.some(x=>x.id===r.itemId);
export const wishReward=roll=>{if(!Number.isFinite(roll)||roll<0||roll>=1)throw Error('Invalid wish roll');let end=0;for(const r of WISH_POOL){end+=r.weight;if(roll<end/1000)return r}return WISH_POOL.at(-1)};
export function validFountain(s){if(s?.fountain===undefined)return true;const f=s.fountain;if(!record(f)||f.policyVersion!==1||!int(f.seq)||!int(f.seed,4294967295)||!int(f.bottles,1e6)||!int(f.total,100000)||!record(f.ledger)||!Object.entries(f.ledger).every(([id,n])=>byId.has(id)&&int(n,1e6))||!Array.isArray(f.history)||f.history.length>10000||!Array.isArray(f.recruited)||f.recruited.length>WISH_RECRUITS.length)return false;
 let total=0;const ids=new Set();for(const h of f.history){if(!record(h)||h.policyVersion!==1||!int(h.id)||h.id>f.seq||ids.has(h.id)||![1,10].includes(h.count)||!int(h.paid,1e6)||h.paid<1||!int(h.seedBefore,4294967295)||!int(h.seedAfter,4294967295)||!Number.isSafeInteger(h.at)||h.at<0||h.at>s.lastAt||!Array.isArray(h.rewards)||h.rewards.length!==h.count||!h.rewards.every(r=>record(r)&&byId.has(r.id)&&int(r.quantity,1e6)&&r.quantity>0))return false;ids.add(h.id);total+=h.count;}
 if(total!==f.total)return false;const claims=f.fairyClaims===undefined?[]:f.fairyClaims;if(!Array.isArray(claims)||claims.length>Math.floor(f.total/500)||!claims.every((r,i)=>record(r)&&r.ordinal===i+1&&r.policyVersion===1&&r.reward==='Lottery_4'&&int(r.quantity,1e6)&&r.quantity>0&&int(r.id)&&r.id<=f.seq&&typeof r.source==='string'&&r.source.length>0&&r.source.length<500))return false;const owners=new Set();return f.recruited.every(r=>{const p=WISH_RECRUITS.find(p=>p.id===r?.character);if(!record(r)||!p||owners.has(p.id)||!s[p.kind]?.[p.id]||!int(r.paid,1e6)||r.paid<1||!int(r.id)||r.id>f.seq||ids.has(r.id))return false;owners.add(p.id);ids.add(r.id);return true});}
export function fountainAction(s,action,target,value){if(!['wishFairyClaim','wishSupply','wishDraw','wishTransfer','wishSynthesize','wishRecruit'].includes(action))return null;const old=fountainState(s),fail=error=>({state:s,error});if(value?.seq!==old.seq||old.seq>=1e9)return fail('The fountain changed. Use the current controls.');const f={...old,seq:old.seq+1,ledger:{...old.ledger}};const done=message=>({state:{...s,fountain:f},message});
 if(action==='wishFairyClaim'){const available=fairyAvailable(s),count=value.count==='all'?available:value.count;if(!available||!(count===1||value.count==='all'))return fail('No Fairy milestone reward is ready.');const amount=count*data.fairyReward.quantity;if((f.ledger.Lottery_4||0)+amount>1e6)return fail('Stone storage is full. Fairy rewards remain unclaimed.');const previous=fairyClaims(s);f.fairyClaims=[...previous,...Array.from({length:count},(_,i)=>({policyVersion:1,id:f.seq,ordinal:previous.length+i+1,reward:'Lottery_4',quantity:data.fairyReward.quantity,source:data.fairyReward.source}))];f.ledger.Lottery_4=(f.ledger.Lottery_4||0)+amount;return done(`Claimed ${count} Fairy rewards · ${amount} Acquaint Stones saved.`);}
 if(action==='wishSupply'){if(f.bottles+100>1e6)return fail('Fairy Bottle storage is full.');f.bottles+=100;return done('Sandbox: 100 Fairy Bottles prepared.');}
 if(action==='wishDraw'){const count=value.count;if(![1,10].includes(count))return fail('Choose one or ten wishes.');const paid=count===10?9:1;if(f.bottles<paid)return fail('Prepare Fairy Bottles first.');if(f.history.length>=10000)return fail('Wish record capacity reached. No bottles spent.');const rewards=[],seedBefore=f.seed;for(let i=0;i<count;i++){f.seed=(Math.imul(f.seed,1664525)+1013904223)>>>0;const r=wishReward(f.seed/4294967296);f.ledger[r.id]=(f.ledger[r.id]||0)+r.quantity;if(f.ledger[r.id]>1e6)return fail('A reward ledger is full. No bottles spent.');rewards.push({id:r.id,quantity:r.quantity});}f.bottles-=paid;f.total+=count;f.history=[...f.history,{policyVersion:1,id:f.seq,count,paid,at:s.lastAt,seedBefore,seedAfter:f.seed,rewards}];return done(`${count} wishes saved · ${paid} Fairy Bottles spent.`);}
 if(action==='wishTransfer'){const r=byId.get(target),n=f.ledger[target]||0;if(!r||!transferable(r)||!n)return fail('Choose an earned item with a supported Bag use.');if(s.inventory[r.itemId]+n>1e6)return fail('Bag space is insufficient. Rewards remain at the fountain.');f.ledger[target]=0;return {state:{...s,fountain:f,inventory:{...s.inventory,[r.itemId]:s.inventory[r.itemId]+n}},message:`Moved ${n} ${r.name} to Bag.`};}
 if(action==='wishSynthesize'){if((f.ledger.Lottery_8||0)<20)return fail('Collect 20 Acquaint Stone Fragments first.');if((f.ledger.Lottery_4||0)>=1e6)return fail('Stone storage is full.');f.ledger.Lottery_8-=20;f.ledger.Lottery_4=(f.ledger.Lottery_4||0)+1;return done('20 fragments combined into 1 Acquaint Stone.');}
 const p=WISH_RECRUITS.find(p=>p.id===target),c=p&&(p.kind==='fellows'?FELLOWS:FAMILY).find(x=>x.id===target);if(!p||!c||originalCharacter(p.id).fields.name!==p.name)return fail('Choose a supported acquaintance.');if(Object.hasOwn(s[p.kind],target))return fail('Already joined. No stones spent; existing progress kept.');if((f.ledger.Lottery_4||0)<p.cost)return fail(`Collect ${p.cost} Acquaint Stones first.`);f.ledger.Lottery_4-=p.cost;f.recruited=[...f.recruited,{id:f.seq,character:p.id,paid:p.cost}];return {state:{...s,fountain:f,[p.kind]:{...s[p.kind],[target]:p.kind==='fellows'?newFellow():{intimacy:0,blessingPower:10,points:0,skill:0,relationship:1}}},message:`${c.name} joined for ${p.cost} Acquaint Stones.`};
}
