/** Independent local habit tracker. Reference capabilities are documented in research; no reference implementation is copied. */
export const HABIT_DOMAINS=['reflection','relationship','parenting','health','career','household','rest','learning','general'];
export const HABIT_DOMAIN_NAMES=['Reflection','Relationships','Parenting','Health','Work','Household','Rest & boundaries','Learning','Uncategorized'];
export const HABIT_FREQS=['daily','weekly','monthly','quarterly','once'];
export const HABIT_BLOCKS=['','morning','midday','evening','night','weekStart','weekMid','weekend','weekEnd','monthStart','monthMid','monthEnd'];
export const HABIT_GATES=['','preCore','preFull','post'];
export const RESPONSIBILITIES=['Food planning','Clothes care','Household supplies','Property upkeep','Transport','Devices & accounts','Health administration','Seasonal preparation','Pet care','Trips','Finances','School administration','Children’s wellbeing','Parenting decisions','Partnership','Special occasions','Personal reflection','Physical wellbeing','Team leadership','Work organization','Career direction','Screen boundaries','Creative practice','Friend & family connections','Learning practice'];
const points={easy:1,med:2,hard:3};
const obj=x=>!!x&&typeof x==='object'&&!Array.isArray(x);
const int=(x,a=0,b=1e9)=>Number.isSafeInteger(x)&&x>=a&&x<=b;
const str=(x,n)=>typeof x==='string'&&x.length<=n;
const pad=n=>String(n).padStart(2,'0');
export function habitDay(now){const d=new Date(now);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function civil(day){return new Date(day+'T12:00:00')}
export function habitPeriod(freq,now){const d=new Date(now);if(freq==='once')return 'once';if(freq==='weekly'){d.setDate(d.getDate()-(d.getDay()+6)%7);return 'w:'+habitDay(d)}if(freq==='monthly')return 'm:'+habitDay(d).slice(0,7);if(freq==='quarterly')return 'q:'+d.getFullYear()+'-'+(Math.floor(d.getMonth()/3)+1);return 'd:'+habitDay(d)}
export function habitDue(item,now){return item.freq!=='daily'||item.days.includes(new Date(now).getDay())}
function previousPeriod(item,now){const d=new Date(now);if(item.freq==='daily'){do{d.setDate(d.getDate()-1)}while(!item.days.includes(d.getDay()))}else if(item.freq==='weekly')d.setDate(d.getDate()-7);else {d.setDate(1);d.setMonth(d.getMonth()-(item.freq==='quarterly'?3:1))}return habitPeriod(item.freq,d)}
export function freshHabits(now=Date.now()){return {version:1,nextId:1,lastNow:now,items:[],history:[],goldDays:{},grace:0,ownership:{},rotation:{day:'',start:0},taskBackup:null,plans:{},trustWeeks:[],badges:[],totals:Object.fromEntries(HABIT_DOMAINS.map(k=>[k,{actions:0,points:0}])),settings:{doneMode:'bottom',hideOffDays:true,compact:false,reducedMotion:false,sound:false,haptics:false,goldPerPoint:10,dailyGoldCap:1000},undo:null}}
export function safeHabitLink(value){const s=String(value||'').trim();if(!s)return '';const u=/^[a-z][a-z0-9+.-]*:/i.test(s)?s:'https://'+s;return /^(javascript|data|vbscript|file|blob):/i.test(u)?'':u}
function validItem(x){return obj(x)&&/^h[1-9][0-9]*$/.test(x.id)&&str(x.title,60)&&x.title.trim().length>0&&str(x.notes,500)&&str(x.memo,4000)&&str(x.link,300)&&(!x.link||safeHabitLink(x.link)===x.link)&&HABIT_FREQS.includes(x.freq)&&Object.hasOwn(points,x.diff)&&HABIT_DOMAINS.includes(x.domain)&&Array.isArray(x.days)&&x.days.length>0&&x.days.length<=7&&new Set(x.days).size===x.days.length&&x.days.every(n=>int(n,0,6))&&HABIT_BLOCKS.includes(x.block)&&HABIT_GATES.includes(x.gate)&&typeof x.review==='boolean'&&int(x.order)&&typeof x.oncePaid==='boolean'&&typeof x.done==='boolean'&&str(x.pk,20)&&str(x.lootedPk,20)&&int(x.streak)&&int(x.milestone)&&int(x.createdAt,0,8640000000000000)}
export function validHabits(s){const h=s?.habits;if(h===undefined)return true;try{return obj(h)&&h.version===1&&int(h.nextId,1)&&int(h.lastNow,0,8640000000000000)&&Array.isArray(h.items)&&h.items.length<=1000&&h.items.every(validItem)&&new Set(h.items.map(x=>x.id)).size===h.items.length&&h.items.every(x=>Number(x.id.slice(1))<h.nextId)&&Array.isArray(h.history)&&h.history.length<=20000&&h.history.every(x=>obj(x)&&str(x.id,60)&&str(x.title,60)&&str(x.period,20)&&str(x.day,10)&&int(x.at,0,8640000000000000)&&int(x.gold,0,1000000)&&int(x.points,0,3)&&HABIT_DOMAINS.includes(x.domain)&&['complete','check','grace'].includes(x.kind))&&obj(h.goldDays)&&Object.entries(h.goldDays).every(([k,v])=>/^\d{4}-\d{2}-\d{2}$/.test(k)&&int(v,0,1000000))&&int(h.grace,0,10000)&&obj(h.ownership)&&Object.entries(h.ownership).every(([k,v])=>int(+k,0,RESPONSIBILITIES.length-1)&&obj(v)&&['good','attention','urgent'].includes(v.status)&&str(v.day,10)&&int(v.at,0,8640000000000000))&&obj(h.rotation)&&str(h.rotation.day,10)&&int(h.rotation.start,0,RESPONSIBILITIES.length-1)&&(h.taskBackup===null||(obj(h.taskBackup)&&Array.isArray(h.taskBackup.items)&&h.taskBackup.items.length<=1000&&h.taskBackup.items.every(validItem)&&int(h.taskBackup.at,0,8640000000000000)))&&obj(h.plans)&&Object.entries(h.plans).every(([k,v])=>int(+k,0,24)&&obj(v)&&str(v.week,20)&&str(v.text,500)&&str(v.taskId,30))&&Array.isArray(h.trustWeeks)&&h.trustWeeks.every(x=>str(x,20))&&new Set(h.trustWeeks).size===h.trustWeeks.length&&Array.isArray(h.badges)&&h.badges.every(x=>str(x,100))&&new Set(h.badges).size===h.badges.length&&obj(h.totals)&&HABIT_DOMAINS.every(k=>obj(h.totals[k])&&int(h.totals[k].actions)&&int(h.totals[k].points))&&obj(h.settings)&&['compact','reducedMotion','sound','haptics'].every(k=>typeof h.settings[k]==='boolean')&&['keep','bottom','hide'].includes(h.settings.doneMode)&&typeof h.settings.hideOffDays==='boolean'&&int(h.settings.goldPerPoint,0,10000)&&int(h.settings.dailyGoldCap,0,1000000)&&(h.undo===null||(obj(h.undo)&&int(h.undo.at,0,8640000000000000)&&int(h.undo.gold,0,1000000)&&h.undo.before?.undo===null&&validHabits({habits:h.undo.before})))}catch{return false}}
export function settleHabits(state,now){if(!state.habits)return state;const h=structuredClone(state.habits),time=Math.max(now,h.lastNow),day=habitDay(time);h.lastNow=time;let missed=[];for(const x of h.items){if(x.freq==='once'||(x.freq==='daily'&&!habitDue(x,time)))continue;const pk=habitPeriod(x.freq,time);if(x.pk!==pk){if(x.streak&&!(x.done&&x.pk===previousPeriod(x,time)))missed.push(x);x.done=false;x.pk=pk}}
 if(missed.length){if(h.grace>0){h.grace--;h.history.push({id:'grace:'+time,title:'Streak protection used',period:day,day,at:time,gold:0,points:0,domain:'rest',kind:'grace'})}else for(const x of missed){x.streak=0;x.milestone=0}h.undo=null}
 if(h.rotation.day!==day){h.rotation.start=h.rotation.day?(h.rotation.start+3)%RESPONSIBILITIES.length:0;h.rotation.day=day}
 if(h.undo&&(time-h.undo.at>30000||habitDay(h.undo.at)!==day))h.undo=null;
 h.history=h.history.slice(-20000);return {...state,habits:h}}
const aliases={faith:'reflection',marriage:'relationship',fatherhood:'parenting',fitness:'health',work:'career',home:'household',discipline:'rest',hobbies:'learning'};
function normalize(spec,id,now,old){if(!obj(spec))throw Error('Invalid task');const title=String(spec.title??old?.title??'').trim();const freq=spec.freq??old?.freq??'daily';const rawDays=spec.days??spec.activeDays??old?.days??[0,1,2,3,4,5,6];const domain=spec.domain===null?'general':spec.domain??old?.domain??'general';const changed=old&&freq!==old.freq;const x={id,title,notes:spec.notes??old?.notes??'',memo:spec.memo??old?.memo??'',link:safeHabitLink(spec.link??old?.link??''),freq,diff:spec.diff??old?.diff??'med',domain:aliases[domain]||domain,days:rawDays,block:spec.block??old?.block??'',gate:spec.gate??old?.gate??'',review:freq==='quarterly'?true:spec.review??old?.review??false,order:spec.order??spec.gateOrd??old?.order??Number(id.slice(1)),done:changed?false:old?.done??false,pk:changed?habitPeriod(freq,now):old?.pk??habitPeriod(freq,now),lootedPk:old?.lootedPk??'',streak:old?.streak??0,milestone:old?.milestone??0,oncePaid:old?.oncePaid??false,createdAt:old?.createdAt??now};if(!validItem(x))throw Error('Check task fields and schedule.');return x}
export function habitAction(state,action,target,value,now){if(!action.startsWith('habit'))return null;const base=settleHabits({...state,habits:state.habits||freshHabits(now)},now),h=structuredClone(base.habits),time=h.lastNow,day=habitDay(time),fail=error=>({state:base,error});let gold=0,message='Tracker saved';const before=structuredClone(h);before.undo=null;h.undo=null;
 try{
 if(action==='habitSave'){const old=h.items.find(x=>x.id===target);if(target&&!old)return fail('Task not found');const id=old?.id||'h'+h.nextId++;const x=normalize(value,id,time,old);if(old)h.items=h.items.map(y=>y.id===id?x:y);else h.items.push(x)}
 else if(action==='habitDelete'){if(!h.items.some(x=>x.id===target))return fail('Task not found');h.items=h.items.filter(x=>x.id!==target)}
 else if(action==='habitClear'){h.taskBackup={items:structuredClone(h.items),at:time};h.items=[];message='Tasks cleared; history and village preserved'}
 else if(action==='habitRestoreTasks'){if(!h.taskBackup)return fail('No previous task list');h.items=h.taskBackup.items.map(x=>{const current=h.items.find(y=>y.id===x.id);return current?{...x,done:current.done,pk:current.pk,lootedPk:current.lootedPk,oncePaid:current.oncePaid,streak:current.streak,milestone:current.milestone}:x});h.taskBackup=null;message='Previous task list restored; rewards and village unchanged'}
 else if(action==='habitSettings'){h.settings={...h.settings,...value}}
 else if(action==='habitOrder'){if(!Array.isArray(value)||value.length!==h.items.length||new Set(value).size!==value.length||value.some(id=>!h.items.some(x=>x.id===id)))return fail('Invalid task order');h.items=value.map((id,i)=>({...h.items.find(x=>x.id===id),order:i}))}
 else if(action==='habitComplete'||action==='habitBatch'){
 const ids=action==='habitBatch'?value:[target];if(!Array.isArray(ids)||!ids.length||ids.length>1000||new Set(ids).size!==ids.length)return fail('Choose tasks once');if(ids.some(id=>!h.items.some(x=>x.id===id)))return fail('Task not found');
 for(const id of ids){const x=h.items.find(x=>x.id===id);if(x.done)continue;if(!habitDue(x,time))return fail('This task is not scheduled today');x.done=true;x.streak++;
 const pk=habitPeriod(x.freq,time);if(x.lootedPk!==pk&&!(x.freq==='once'&&x.oncePaid)&&!h.history.some(r=>r.id===id&&r.period===pk&&r.kind==='complete')){const credit=Math.min(points[x.diff]*h.settings.goldPerPoint,Math.max(0,h.settings.dailyGoldCap-(h.goldDays[day]||0)));gold+=credit;h.goldDays[day]=(h.goldDays[day]||0)+credit;x.lootedPk=pk;if(x.freq==='once')x.oncePaid=true;h.totals[x.domain].actions++;h.totals[x.domain].points+=points[x.diff];h.history.push({id:x.id,title:x.title,period:pk,day,at:time,gold:credit,points:points[x.diff],domain:x.domain,kind:'complete'});}
 for(const n of [3,7,14,30,60,100])if(x.streak>=n&&x.milestone<n){x.milestone=n;const badge='streak:'+id+':'+n;if(!h.badges.includes(badge))h.badges.push(badge)}
 }h.undo={at:time,gold,before};message='Completed · +'+gold+' Gold';
 }
 else if(action==='habitUncheck'){const x=h.items.find(x=>x.id===target);if(!x)return fail('Task not found');if(x.done){x.done=false;x.streak=Math.max(0,x.streak-1)}message='Reopened; this occurrence cannot reward twice'}
 else if(action==='habitUndo'){const u=base.habits.undo;if(!u||time-u.at>30000)return fail('Undo expired or another action followed');if(base.gold<u.gold||base.earned<u.gold)return fail('Reward already used');return {state:{...base,gold:base.gold-u.gold,earned:base.earned-u.gold,habits:{...u.before,lastNow:time,undo:null}},message:'Completion and its Gold reversed'}}
 else if(action==='habitCheck'){if(!int(+target,0,RESPONSIBILITIES.length-1)||!['good','attention','urgent'].includes(value))return fail('Invalid responsibility');const old=h.ownership[target];h.ownership[target]={status:value,day,at:time};if(old?.day!==day){h.totals[responsibilityDomain(+target)].actions++;h.totals[responsibilityDomain(+target)].points+=value==='good'?1:2;h.history.push({id:'area:'+target,title:RESPONSIBILITIES[+target],period:day,day,at:time,gold:0,points:value==='good'?1:2,domain:responsibilityDomain(+target),kind:'check'});}message='Responsibility checked'}
 else if(action==='habitPlan'){if(!int(+target,0,24)||!str(value,500))return fail('Invalid review plan');const week=habitPeriod('weekly',time),old=h.plans[target];h.plans[target]={week,text:value.trim(),taskId:old?.week===week?old.taskId:''}}
 else if(action==='habitFinishReview'){const week=habitPeriod('weekly',time);for(const [id,p]of Object.entries(h.plans)){if(p.week===week&&p.text&&!p.taskId){const taskId='h'+h.nextId++;h.items.push(normalize({title:(RESPONSIBILITIES[+id]+': '+p.text).slice(0,60),memo:p.text,notes:'Created from your weekly responsibility review.',freq:'once',diff:'med',domain:responsibilityDomain(+id)},taskId,time));p.taskId=taskId}}
 const ready=Object.entries(h.ownership).filter(([,v])=>v.status!=='good').every(([id])=>h.plans[id]?.week===week&&h.plans[id].text);if(ready&&!h.trustWeeks.includes(week))h.trustWeeks.push(week);message=ready?'Weekly review recorded; plans added once':'Plans added; some areas still need a plan'}
 else if(action==='habitImport'){h.taskBackup={items:structuredClone(h.items),at:time};const list=Array.isArray(value)?value:value?.dailies||value?.tasks;if(!Array.isArray(list)||list.length>1000)return fail('Choose a task-list JSON file');for(const spec of list){const key=String(spec?.title||'').trim().toLowerCase();const old=h.items.find(x=>x.title.trim().toLowerCase()===key);const id=old?.id||'h'+h.nextId++;const x=normalize(spec,id,time,old);if(old)h.items=h.items.map(y=>y.id===id?x:y);else h.items.push(x)}const retire=value?.retire;if(retire!==undefined){if(!Array.isArray(retire)||!retire.every(x=>str(x,60)))return fail('Invalid retire list');h.items=h.items.filter(x=>!retire.some(n=>n.trim().toLowerCase()===x.title.trim().toLowerCase()))}message='Task list merged; no rewards granted'}
 else return fail('Unknown tracker action');
 const week=habitPeriod('weekly',time),wk=h.history.filter(x=>habitPeriod('weekly',civil(x.day))===week&&x.kind!=='grace');const touched=new Set(wk.map(x=>x.domain).filter(x=>x!=='general'));const weight=wk.filter(x=>x.kind==='complete').reduce((n,x)=>n+x.points,0);for(const n of [25,50,75,90,100]){const key=week+':consistency:'+n;if(weight>=n&&!h.badges.includes(key))h.badges.push(key)}for(const n of [4,6,8]){const key=week+':balance:'+n;if(touched.size>=n&&!h.badges.includes(key)){h.badges.push(key);if(n===8)h.grace=Math.min(10000,h.grace+1)}}
 for(const goal of habitGoals(h,time)){const key=goal.period+':goal:'+goal.id;if(goal.current>=goal.target&&!h.badges.includes(key))h.badges.push(key)}
 h.history=h.history.slice(-20000);const next={...base,habits:h,gold:base.gold+gold,earned:base.earned+gold};if(!Number.isSafeInteger(next.gold)||!Number.isSafeInteger(next.earned)||!validHabits(next))return fail('Tracker storage limit or invalid fields');return {state:next,message};
 }catch(e){return fail(e.message||'Invalid tracker data')}
}
export function habitSummary(h,now){h=h||freshHabits(now);const day=habitDay(now),week=habitPeriod('weekly',now),month=habitPeriod('monthly',now),count=fn=>h.history.filter(x=>x.kind==='complete'&&fn(x));const today=count(x=>x.day===day),weekly=count(x=>habitPeriod('weekly',civil(x.day))===week),monthly=count(x=>habitPeriod('monthly',civil(x.day))===month);return {today,weekly,monthly,domains:Object.fromEntries(HABIT_DOMAINS.map(k=>[k,h.totals[k].points])),gold:h.goldDays[day]||0}}
export function exportHabitTasks(h){return {everkaiTasks:1,tasks:(h?.items||[]).map(({id,done,pk,lootedPk,streak,milestone,createdAt,oncePaid,...definition})=>definition)}}

export function responsibilityDomain(i){return i<=10?'household':i<=13?'parenting':i<=15?'relationship':i===16?'reflection':i===17?'health':i<=20?'career':i===21?'rest':'learning'}

export function habitGoals(h,now){const day=habitDay(now),week=habitPeriod('weekly',now),rows=h.history.filter(x=>x.kind!=='grace'),d=rows.filter(x=>x.day===day),w=rows.filter(x=>habitPeriod('weekly',civil(x.day))===week),count=(rs,keys)=>rs.filter(x=>keys.includes(x.domain)).length;return [
 {id:'start',label:'Record an action today',current:d.length,target:1,period:day},
 {id:'three',label:'Record three actions today',current:d.length,target:3,period:day},
 {id:'reflect',label:'Care for reflection or rest today',current:count(d,['reflection','rest']),target:1,period:day},
 {id:'connect',label:'Care for a relationship today',current:count(d,['relationship','parenting']),target:1,period:day},
 {id:'maintain',label:'Care for health or home today',current:count(d,['health','household']),target:1,period:day},
 {id:'breadth',label:'Visit four life areas this week',current:new Set(w.map(x=>x.domain).filter(x=>x!=='general')).size,target:4,period:week},
 {id:'family',label:'Four relationship or parenting actions',current:count(w,['relationship','parenting']),target:4,period:week},
 {id:'practical',label:'Six health, work or household actions',current:count(w,['health','career','household']),target:6,period:week},
 {id:'review',label:'Complete your weekly review',current:h.trustWeeks.includes(week)?1:0,target:1,period:week},
 {id:'home-chain',label:'Weekly combination: relationship ×2, parenting ×2, household ×1',current:Number(count(w,['relationship'])>=2)+Number(count(w,['parenting'])>=2)+Number(count(w,['household'])>=1),target:3,period:week},
 {id:'work-chain',label:'Weekly combination: work ×3, household ×1, review ×1',current:Number(count(w,['career'])>=3)+Number(count(w,['household'])>=1)+Number(h.trustWeeks.includes(week)),target:3,period:week}
 ]}
