import data from './inn-guest-data.json' with {type:'json'};
import {innRating} from './inn-progression.mjs';
export const INN_GUESTS=data.rules;const rules=new Map(INN_GUESTS.map(r=>[r.id,r]));
export const innGuest=id=>rules.get(id)||null;
export function innGuestReady(s,r){return !!s.inn&&!!r&&innRating(s.inn)>=r.rating&&s.inn.menu.includes(r.dish)&&(!r.fellow||Object.hasOwn(s.fellows,r.fellow));}
export const innGiftPolicy=id=>innGuest(id)?.kind?2:1;
export function validInnGuests(s){const receipts=s.inn?.guestGifts;if(receipts===undefined)return true;if(!receipts||typeof receipts!=='object'||Array.isArray(receipts))return false;return Object.entries(receipts).every(([id,r])=>{const rule=innGuest(id);if(!rule||!r||r.policyVersion!==innGiftPolicy(id)||!Number.isSafeInteger(r.completedAt)||r.completedAt<0||r.completedAt>s.lastAt)return false;if(r.claimedAt===null)return ['type','percent','kind','amount'].every(k=>r[k]===undefined);if(!Number.isSafeInteger(r.claimedAt)||r.claimedAt<r.completedAt||r.claimedAt>s.lastAt)return false;return rule.kind?r.kind===rule.kind&&Number.isInteger(r.amount)&&r.amount>0&&r.amount<=1000000&&r.type===undefined&&r.percent===undefined:r.type===rule.type&&Number.isInteger(r.percent)&&r.percent>0&&r.percent<=1000&&r.kind===undefined&&r.amount===undefined;});}
export const innGiftSchoolBonus=(s,kind)=>Object.values(s.inn?.guestGifts||{}).reduce((n,r)=>n+(r.claimedAt!==null&&r.policyVersion===2&&r.kind===kind?r.amount:0),0);
export const innGiftDescription=r=>r.kind==='graduationFlat'?`+${r.amount} future pupil graduation earnings`:r.kind==='teachAllXP'?`+${r.amount} Fellow EXP per Teach all round`:`+${r.percent}% ${r.type} employee earnings`;
export function innGiftEmployeePercent(s,type){if(!type)return 0;return Object.values(s.inn?.guestGifts||{}).reduce((sum,r)=>sum+(r.claimedAt!==null&&r.type===type?r.percent:0),0);}
export function claimInnGift(s,id){const r=s.inn?.guestGifts?.[id],rule=innGuest(id);if(!r||!rule||r.claimedAt!==null)return {state:s,error:'Serve this special visit and collect its treasure once.'};return {state:{...s,inn:{...s.inn,guestGifts:{...s.inn.guestGifts,[id]:{...r,claimedAt:s.lastAt,...(rule.kind?{kind:rule.kind,amount:rule.amount}:{type:rule.type,percent:rule.percent})}}}},message:`Collected ${rule.name}. ${innGiftDescription(rule)}.`};}
