import activation from './stella-activation-policy.json' with {type:'json'};
import data from './stella-data.json' with {type:'json'};
import {FELLOWS,fellowById} from './catalog.mjs';
export const STELLA_PROFILES=data.profiles;
export const stellaActivation=id=>activation.owners[id]||null;
export const STELLA_ACTIVATION_POLICY=activation.id;
export const stellaRule=id=>STELLA_PROFILES.find(p=>p.id===id);
export const stellaState=s=>s.stella||{policyVersion:1,seq:0,stock:{},grants:[],history:[]};
const cache=new WeakMap();
function entries(s){const h=stellaState(s).history;if(!cache.has(h)){const m=new Map();for(const r of h)m.set(r.owner,r);cache.set(h,m);}return cache.get(h);}
export const stellaEntry=(s,id)=>entries(s).get(id)||null;
export function stellaBonus(s,id){const own=stellaEntry(s,id),type=fellowById(id)?.type;let percent=0;for(const r of entries(s).values())if(r.type===type)percent+=r.percent;return {flat:own?.flat||0,percent};}
export function applyStella(s,id,power){const b=stellaBonus(s,id);return Math.floor((power+b.flat)*(1+b.percent/100));}
export function validStella(s){if(s?.stella===undefined)return true;const t=s.stella,int=(n,max=1e9)=>Number.isSafeInteger(n)&&n>=0&&n<=max;if(!t||t.policyVersion!==1||!int(t.seq)||!t.stock||Array.isArray(t.stock)||!Object.entries(t.stock).every(([id,n])=>STELLA_PROFILES.some(p=>p.itemId===id)&&int(n,1e6))||!Array.isArray(t.grants)||t.grants.length>10000||!Array.isArray(t.history)||t.history.length>STELLA_PROFILES.reduce((n,p)=>n+p.levels.length+1,0))return false;
 const balances={},ids=new Set(),levels={};for(const r of t.grants){if(!r||!int(r.id)||r.id>t.seq||ids.has(r.id)||!STELLA_PROFILES.some(p=>p.itemId===r.itemId)||!int(r.count,1e6)||!r.count||!int(r.at,Number.MAX_SAFE_INTEGER)||r.at>s.lastAt)return false;ids.add(r.id);balances[r.itemId]=(balances[r.itemId]||0)+r.count;}
 for(const r of t.history){const p=stellaRule(r?.owner);if(!r||!p||!s.fellows?.[r.owner]||!int(r.id)||r.id>t.seq||ids.has(r.id)||r.policyVersion!==1||(r.activationPolicy!==undefined&&(r.level!==0||r.activationPolicy!==(stellaActivation(r.owner)?.activationPolicy||activation.id)))||!int(r.level,p.levels.length)||r.level!==(levels[r.owner]===undefined?0:levels[r.owner]+1)||r.itemId!==p.itemId||r.type!==p.type||!int(r.paid,1e6)||(r.level===0?r.paid!==0:r.paid===0)||!int(r.flat,1e12)||!int(r.percent,10000)||!int(r.at,Number.MAX_SAFE_INTEGER)||r.at>s.lastAt)return false;ids.add(r.id);levels[r.owner]=r.level;balances[r.itemId]=(balances[r.itemId]||0)-r.paid;}
 return STELLA_PROFILES.every(p=>(balances[p.itemId]||0)===(t.stock[p.itemId]||0));
}
export function stellaPlan(s,id,count=/** @type {number|string} */ (1)){const p=stellaRule(id),entry=stellaEntry(s,id),t=stellaState(s);if(!p||!entry||![1,5,'max'].includes(count))return {rows:[],cost:0};const rows=[];let cost=0;for(const row of p.levels.slice(entry.level,entry.level+(count==='max'?40:count))){if(cost+row.cost>(t.stock[p.itemId]||0)||t.seq+rows.length+1>1e9)break;rows.push(row);cost+=row.cost;}return {rows,cost};}
export function stellaAction(s,action,target,value){if(!['stellaSupply','stellaActivate','stellaUpgrade'].includes(action))return null;const old=stellaState(s),p=stellaRule(target),fail=error=>({state:s,error});if(!p||!s.fellows[target]||fellowById(target)?.type!==p.type)return fail('Choose an owned Fellow with a supported Stella curve.');if(value?.seq!==old.seq||old.seq>=1e9)return fail('Stella changed. Use current controls.');const t={...old,seq:old.seq+1,stock:{...old.stock}},balance=t.stock[p.itemId]||0,entry=stellaEntry(s,target);
 if(action==='stellaSupply'){if(balance+1000>1e6||t.grants.length>=10000)return fail('Fragment supply storage is full.');t.stock[p.itemId]=balance+1000;t.grants=[...t.grants,{id:t.seq,itemId:p.itemId,count:1000,at:s.lastAt}];return {state:{...s,stella:t},message:`Prepared 1,000 ${p.name} fragments · free sandbox.`};}
 if(action==='stellaActivate'&&!stellaActivation(target))return fail('No private activation policy exists for this character.');if(action==='stellaActivate'&&entry)return fail('This Stella is already active.');const plan=action==='stellaActivate'?{rows:[{level:0,...stellaActivation(target)}],cost:0}:stellaPlan(s,target,value.count??1);if(!plan.rows.length)return fail('Activate first and prepare enough owner fragments; the documented cap is the supported limit.');t.stock[p.itemId]=balance-plan.cost;t.seq=old.seq+plan.rows.length;t.history=[...t.history,...plan.rows.map((row,i)=>({policyVersion:1,id:old.seq+i+1,owner:target,level:row.level,itemId:p.itemId,paid:row.cost,type:p.type,flat:row.flat,percent:row.percent,at:s.lastAt,...(row.level===0?{activationPolicy:stellaActivation(target)?.activationPolicy||activation.id}:{})}))];const row=plan.rows.at(-1);return {state:{...s,stella:t},message:`${p.name} Stella ${row.level} saved · +${row.flat.toLocaleString()} own Power · ${p.type} Power +${row.percent}%.`};
}
