import {OPENING_SCENES} from './opening-presentation.mjs';
import {SCENES} from './scenes.mjs';
export const STORY_SCENES=SCENES;
export const ALL_STORY_SCENES=[...STORY_SCENES,...OPENING_SCENES];
const scenes=new Map(ALL_STORY_SCENES.map(s=>[s.id,s]));
export const storyScene=id=>scenes.get(id)||null;
export const storyBookmark=(s,id)=>s.story?.bookmarks?.[id]||{line:0,read:false};
export function validStory(s){if(s?.story===undefined)return true;const b=s.story;if(!b||b.policyVersion!==1||!b.bookmarks||typeof b.bookmarks!=='object'||Array.isArray(b.bookmarks)||typeof b.current!=='string'||!scenes.has(b.current)||!Object.hasOwn(b.bookmarks,b.current))return false;return Object.entries(b.bookmarks).every(([id,x])=>scenes.has(id)&&x&&Number.isInteger(x.line)&&x.line>=0&&x.line<scenes.get(id).lines.length&&typeof x.read==='boolean')}
export function storyAction(s,action,target,value){if(!['storyOpen','storyNext','storyPrevious','storyFinish','storyRestart'].includes(action))return null;const scene=scenes.get(target),fail=error=>({state:s,error});if(!scene)return fail('Choose an available village encounter.');const old=storyBookmark(s,target),book=s.story||{policyVersion:1,current:target,bookmarks:{}};let mark={...old};if(action!=='storyOpen'){if(book.current!==target||!Object.hasOwn(book.bookmarks,target)||value!==old.line)return fail('This reading position changed. Use the current page.');if(action==='storyNext'){if(old.line>=scene.lines.length-1)return fail('You reached the final line.');mark.line++}if(action==='storyPrevious'){if(old.line<=0)return fail('You are at the beginning.');mark.line--}if(action==='storyFinish'){if(old.line!==scene.lines.length-1||old.read)return fail('Read the final line to finish this encounter.');mark.read=true}if(action==='storyRestart')mark.line=0}
return {state:{...s,story:{...book,current:target,bookmarks:{...book.bookmarks,[target]:mark}}},message:action==='storyFinish'?'Encounter read. Your bookmark is saved.':action==='storyRestart'?'Reading from the beginning.':'Bookmark saved.'}}
