import data from './trading-post-data.json' with {type:'json'};import {FELLOWS} from './catalog.mjs';import {bondedPower} from './adventure.mjs';
export const TRADE_OPPONENTS=data.localOpponents,TRADE_SHOP=data.shop;
const int=(n,max=1e9)=>Number.isSafeInteger(n)&&n>=0&&n<=max,day=s=>Math.floor(s.lastAt/86400000),defaultEnergy=s=>({day:day(s),energy:1,refills:0,recoverAt:null});
export function negotiationEnergy(s,id){const e=s.tradingPost?.energy[id];if(!e||e.day<day(s))return defaultEnergy(s);if(e.energy===0&&e.recoverAt!==null&&s.lastAt>=e.recoverAt&&e.refills<3)return {...e,energy:1,refills:e.refills+1,recoverAt:null};return e}
export function tradingPost(s){const t=s.tradingPost||{policyVersion:1,seq:0,coins:0,influence:0,energy:{},run:null,history:[],shop:{day:day(s),bought:0}};return t.shop.day<day(s)?{...t,shop:{day:day(s),bought:0}}:t}
function validRun(r,s){return r&&r.policyVersion===1&&int(r.id)&&r.simulated===true&&r.opponent&&TRADE_OPPONENTS.some(x=>x.id===r.opponent.id)&&int(r.opponent.power,1e15)&&typeof r.opponent.name==='string'&&r.opponent.name.length<80&&Array.isArray(r.team)&&r.team.length>0&&r.team.length<=6&&new Set(r.team.map(p=>p?.id)).size===r.team.length&&r.team.every(p=>p&&s.fellows?.[p.id]&&typeof p.name==='string'&&p.name.length<80&&int(p.power,1e15)&&p.paidEnergy===1&&p.won===(p.power>=r.opponent.power))&&r.wins===r.team.filter(p=>p.won).length&&int(r.coinPerWin,1e6)&&int(r.influencePerWin,1e6)&&r.coins===r.wins*r.coinPerWin&&r.influence===r.wins*r.influencePerWin&&Number.isSafeInteger(r.startedAt)&&r.startedAt>=0&&r.startedAt<=s.lastAt&&Number.isSafeInteger(r.readyAt)&&r.readyAt>r.startedAt}
export function validTradingPost(s){if(s?.tradingPost===undefined)return true;const t=s.tradingPost;if(!t||t.policyVersion!==1||!int(t.seq)||!int(t.coins)||!int(t.influence)||!t.energy||Array.isArray(t.energy)||!Object.entries(t.energy).every(([id,e])=>s.fellows?.[id]&&e&&int(e.day)&&e.day<=day(s)&&int(e.energy,1)&&int(e.refills,3)&&(e.recoverAt===null||e.energy===0&&e.refills<3&&Number.isSafeInteger(e.recoverAt)&&e.recoverAt>=0))||!Array.isArray(t.history)||t.history.length>10000||!t.shop||!int(t.shop.day)||t.shop.day>day(s)||!int(t.shop.bought,10))return false;const ids=new Set();for(const r of t.history){if(!validRun(r,s)||r.id>t.seq||ids.has(r.id)||!Number.isSafeInteger(r.completedAt)||r.completedAt<r.readyAt||r.completedAt>s.lastAt)return false;ids.add(r.id)}return t.run===null||validRun(t.run,s)&&t.run.id<=t.seq&&!ids.has(t.run.id)}
export function tradingAction(s,action,target,value){if(!['tradeBegin','tradeComplete','tradeBuy'].includes(action))return null;const old=tradingPost(s),fail=error=>({state:s,error});if(value?.seq!==old.seq||old.seq>=1e9)return fail('The Trading Post changed. Use current controls.');const t={...old,seq:old.seq+1,energy:{...old.energy}};
 if(action==='tradeBegin'){const opponent=TRADE_OPPONENTS.find(x=>x.id===target),ids=value.team;if(t.run)return fail('Complete your saved negotiation first.');if(t.history.length>=10000)return fail('Negotiation record capacity reached.');if(!opponent||!Array.isArray(ids)||ids.length<1||ids.length>6||new Set(ids).size!==ids.length||!ids.every(id=>Object.hasOwn(s.fellows,id)))return fail('Choose one to six different owned Fellows.');if(ids.some(id=>negotiationEnergy(s,id).energy<1))return fail('A selected Fellow needs Negotiation Energy. No Energy spent.');const team=ids.map(id=>{const e=negotiationEnergy(s,id);t.energy[id]={...e,energy:0,recoverAt:e.refills<3?s.lastAt+3600000:null};return {id,name:FELLOWS.find(f=>f.id===id).name,power:bondedPower(s,id),paidEnergy:1,won:bondedPower(s,id)>=opponent.power}}),wins=team.filter(p=>p.won).length;t.run={policyVersion:1,id:t.seq,simulated:true,opponent:{...opponent},team,wins,coinPerWin:30,influencePerWin:2,coins:wins*30,influence:wins*2,startedAt:s.lastAt,readyAt:s.lastAt+3000};return {state:{...s,tradingPost:t},message:'Negotiation saved · opponents are simulated offline merchants.'};}
 if(action==='tradeComplete'){const r=t.run;if(!r||r.id!==target||s.lastAt<r.readyAt)return fail('Wait until this negotiation is ready.');if(t.coins+r.coins>1e9||t.influence+r.influence>1e9)return fail('Reward balance is full. Paid negotiation retained.');t.coins+=r.coins;t.influence+=r.influence;t.history=[...t.history,{...r,completedAt:s.lastAt}];t.run=null;return {state:{...s,tradingPost:t},message:`${r.wins}/${r.team.length} duels won · ${r.coins} Trade Coins · ${r.influence} Influence.`};}
 const q=value.count;if(target!==TRADE_SHOP.id||![1,5].includes(q)||t.coins<TRADE_SHOP.price*q||t.shop.bought+q>10||s.inventory[target]+q>1e6)return fail('Choose an affordable exchange with daily and Bag space.');t.coins-=TRADE_SHOP.price*q;t.shop={...t.shop,bought:t.shop.bought+q};return {state:{...s,tradingPost:t,inventory:{...s.inventory,[target]:s.inventory[target]+q}},message:`Bought ${q} Basic Earnings Card. Use in Bag for village gold.`};
}
