import data from './treasure-data.json' with {type:'json'};
export const TREASURE_AREAS=data.areas,TREASURE_RELICS=data.relics;
const areaById=new Map(TREASURE_AREAS.map(a=>[a.id,a])),relicIds=new Set(TREASURE_RELICS.map(r=>r.id));
const day=s=>Math.floor(s.lastAt/86400000),int=(n,max=1e9)=>Number.isSafeInteger(n)&&n>=0&&n<=max,record=x=>x&&typeof x==='object'&&!Array.isArray(x);
export const restorationLevel=r=>r?.restorations?.length||0;
export const restorationIncome=r=>(r?.restorations||[]).reduce((n,x)=>n+x.goldPerSecond,0);
export const treasureIncome=s=>Object.values(s.treasure?.relics||{}).reduce((n,r)=>n+restorationIncome(r),0);
const validRestorations=r=>r.restorations===undefined||r.donated&&Array.isArray(r.restorations)&&r.restorations.length<=20&&r.restorations.every(x=>record(x)&&x.policyVersion===1&&int(x.materials,1e6)&&x.materials>0&&int(x.goldPerSecond,1e6)&&x.goldPerSecond>0);
export const treasureLevel=t=>Math.min(100,1+Math.floor(t.xp/120));
export function treasureState(s){const t=s.treasure||{policyVersion:1,seq:0,seed:123456789,day:day(s),stamina:12,xp:0,trip:null,gems:{},relics:{}};return t.day<day(s)?{...t,day:day(s),stamina:12}:t}
export function validTreasure(s){if(s?.treasure===undefined)return true;const t=s.treasure;if(!record(t)||t.policyVersion!==1||!int(t.seq)||!int(t.seed,4294967295)||!int(t.day)||t.day>day(s)||!int(t.stamina,12)||!int(t.xp)||!record(t.gems)||!record(t.relics))return false;
 if(!Object.entries(t.gems).every(([id,n])=>areaById.has(id)&&int(n,1e6)))return false;
 if(!Object.entries(t.relics).every(([id,r])=>relicIds.has(id)&&record(r)&&validRestorations(r)&&int(r.materials,1e6)&&typeof r.donated==='boolean'&&typeof r.displayed==='boolean'&&(!r.displayed||r.donated)))return false;
 const p=t.trip;return p===null||record(p)&&int(p.id)&&p.id<=t.seq&&areaById.has(p.area)&&treasureLevel(t)>=areaById.get(p.area).level&&Array.isArray(p.tiles)&&new Set(p.tiles).size===p.tiles.length&&p.tiles.every(n=>int(n,11));}
export const tileGem=i=>i%3===2;
export function appraisalPick(area,roll){let v=roll*area.totalPercent;for(const row of area.pool){v-=row.percent;if(v<0)return row.id}return area.pool.at(-1).id}
export function treasureAction(s,action,target,value){if(!['treasureRestore','treasureStart','treasureDig','treasureReturn','treasureAppraise','treasureDonate','treasureDisplay'].includes(action))return null;
 const old=treasureState(s),fail=error=>({state:s,error});if(value!==old.seq)return fail('This expedition changed. Use the current controls.');if(old.seq>=1e9)return fail('Expedition action limit reached.');
 const t={...old,seq:old.seq+1,gems:{...old.gems},relics:{...old.relics}};let message='';
 if(action==='treasureStart'){const a=areaById.get(target);if(!a||treasureLevel(t)<a.level)return fail('Raise Steeltooth’s level to visit this region.');if(t.trip)return fail('Return to camp first.');if((t.gems[a.id]||0)>999996||t.xp>999999880)return fail('Make room at camp before starting another expedition.');t.trip={id:t.seq,area:a.id,tiles:[]};message=`Exploring ${a.name}. Radar marks gemstones.`;}
 if(action==='treasureDig'){if(!t.trip||!int(target,11)||t.trip.tiles.includes(target))return fail('Choose an undug tile.');if(!t.stamina)return fail('Refill Steeltooth’s stamina at camp.');t.trip={...t.trip,tiles:[...t.trip.tiles,target]};t.stamina--;message=tileGem(target)?'Gemstone found! Return to camp to unload it.':'Stone stored. Return to camp to gain EXP.';}
 if(action==='treasureReturn'){if(!t.trip)return fail('You are already at camp.');const gems=t.trip.tiles.filter(tileGem).length,xp=t.trip.tiles.length*10,id=t.trip.area;if((t.gems[id]||0)+gems>1e6||t.xp+xp>1e9)return fail('Camp storage is full.');t.gems[id]=(t.gems[id]||0)+gems;t.xp+=xp;t.trip=null;message=`Returned: ${gems} gemstones and ${xp} Steeltooth EXP.`;}
 if(action==='treasureAppraise'){if(t.trip)return fail('Return to camp for appraisal.');const a=areaById.get(target);if(!a||!(t.gems[target]>0))return fail('Find a gemstone in this region first.');t.seed=(Math.imul(t.seed,1664525)+1013904223)>>>0;const id=appraisalPick(a,t.seed/4294967296),r=t.relics[id];if(r?.materials>=1e6)return fail('This relic’s material storage is full.');t.gems[target]--;t.relics[id]=r?{...r,materials:r.materials+1}:{materials:0,donated:false,displayed:false};message=`${TREASURE_RELICS.find(x=>x.id===id).name}${r?' · duplicate converted to its own material.':' discovered! Donate it to the relic collection.'}`;}
 if(action==='treasureRestore'){const r=t.relics[target];if(!r?.donated)return fail('Donate this relic first.');const level=restorationLevel(r);if(level>=20)return fail('This relic is fully restored.');const cost=level+1;if(r.materials<cost)return fail(`Requires ${cost} of this relic’s duplicate materials.`);t.relics[target]={...r,materials:r.materials-cost,restorations:[...(r.restorations||[]),{policyVersion:1,materials:cost,goldPerSecond:1}]};message='Sandbox restoration complete · +1 gold/s from museum visitors.';}
 if(action==='treasureDonate'||action==='treasureDisplay'){const r=t.relics[target];if(!r)return fail('Appraise this relic first.');if(action==='treasureDonate'){if(r.donated)return fail('Already donated.');t.relics[target]={...r,donated:true,displayed:true};message='Relic donated and displayed.'}else{if(!r.donated)return fail('Donate this relic first.');t.relics[target]={...r,displayed:!r.displayed};message=r.displayed?'Relic stored.':'Relic displayed.';}}
 return {state:{...s,treasure:t},message};}
