"""Build app content from the read-only APK extraction. Fails on missing/ambiguous effects."""
import argparse,json,re,hashlib
from pathlib import Path
p=Path(__file__).resolve();parser=argparse.ArgumentParser();parser.add_argument('--source',type=Path,default=p.parents[3]/'outputs/component-research/datasets');args=parser.parse_args();root=args.source
read=lambda n:json.loads((root/n).read_text())
characters=read('characters.json');items=read('Item.json');rules=read('core-rules.json');lookup={r['id']:r['en'] for r in items}
def item(id):
 return {'id':id,'name':lookup['Item:name:'+id],'description':lookup['Item:description:'+id],'originalSources':lookup.get('Item:source:'+id),'sourceKeys':[x['id'] for x in items if x['id'].endswith(':'+id)]}
gifts=[]
for id in ['gift1','gift2','gift3','gift4','gift5']:
 x=item(id);m=re.search(r'increase their (Intimacy|Blessing Power) by (\d+)\.',x['description']);assert m,id;x.update(stat='intimacy' if m[1]=='Intimacy' else 'blessingPower',amount=int(m[2]));gifts.append(x)
gear=[]
gear_pattern=r'^(?:Aptitude \+?(\d+)|(\d+) Aptitude)\.'
for id in sorted(k.removeprefix('Item:description:') for k,v in lookup.items() if k.startswith('Item:description:Item_Weapon_Equipment_') and re.match(gear_pattern,v)):
 x=item(id);m=re.match(gear_pattern,x['description']);assert m,id;x['aptitude']=int(m[1] or m[2]);gear.append(x)
consumables=[]
for id in ['Item_HeroEXP_Resources_'+str(i) for i in range(1,5)]:
 x=item(id);m=re.search(r'Used to obtain ([\d,]+) Fellow EXP\.',x['description']);assert m,id
 x.update(stat='fellowXP',amount=int(m[1].replace(',','')),target='player');consumables.append(x)
for id in ['Item_ES_information_'+s+'_'+t for s in ['charm','intimacy'] for t in ['A','S']]+['Item_Monopoly0'+str(i)+'_Wife'+s for i in range(1,4) for s in ['Charm','Intimacy']]:
 x=item(id);m=re.search(r'(Intimacy|Blessing Power).*? by (\d+)\.',x['description'],re.I);assert m and '{' not in x['description'],id
 x.update(stat='intimacy' if m[1].lower()=='intimacy' else 'blessingPower',amount=int(m[2]),target='family');consumables.append(x)
for id in ['Item_Gcoin_YieldPack_1','Item_Gcoin_YieldPack_3']:
 x=item(id);m=re.fullmatch(r'Used to immediately obtain (\d+) (minute|hour) of Gold Earnings\.',x['description']);assert m,id
 x.update(stat='gold',amount=int(m[1])*(60 if m[2]=='minute' else 3600),target='player',effect='earningsSeconds');consumables.append(x)
x=item('Item_WifeBlessExp_extradd_01');m=re.fullmatch(r'Used to increase (\d+) Blessing Points of a family member\.',x['description']);assert m
x.update(stat='points',amount=int(m[1]),target='family');consumables.append(x)
x=item('Item_GetCE_10');m=re.search(r'Used to gain (\d+) Education Point in the current classroom\.',x['description']);assert m
x.update(stat='points',amount=int(m[1]),target='school');consumables.append(x)
rule=next(x for x in rules if x['id']=='Rule:text:FosterChild_8');m=re.search(r'1 point every (\d+) minutes',rule['en']);assert m
assert len({x['id'] for x in characters})==len(characters)
content={'characters':characters,'gifts':gifts,'gear':gear,'consumables':consumables,'rules':rules,'educationRecoveryMs':int(m[1])*60000,'sourceHashes':{name:hashlib.sha256((root/name).read_bytes()).hexdigest() for name in ['characters.json','Item.json','core-rules.json']}}
(p.parents[1]/'lib/original-content.mjs').write_text('// Generated by scripts/import-original-content.py from unprotected APK TextAssets. Do not hand-edit.\nexport default '+json.dumps(content,ensure_ascii=False,separators=(',',':'))+';\n')
print('Imported',len(characters),'characters,',len(rules),'rules,',len(gifts)+len(gear)+len(consumables),'items; explicit effects parsed from source text.')
